import type { LocalizedText, QuestChoice, QuestQuestion, QuestSection } from "./types";

const t = (en: string, nb: string): LocalizedText => ({ en, nb });
const choices = (...items: readonly (readonly [string, string])[]): readonly QuestChoice[] =>
  items.map(([en, nb], score) => ({ id: String.fromCharCode(65 + score) as QuestChoice["id"], score: score as QuestChoice["score"], text: t(en, nb) }));
const q = (order: number, prompt: LocalizedText, answers: readonly QuestChoice[], context?: LocalizedText): QuestQuestion =>
  ({ id: `Q${order}`, order, prompt, choices: answers, ...(context ? { context } : {}) });

export const NUTRITION_ASSESSMENT_VERSION = "1.0";

export const nutritionAssessmentSections: readonly QuestSection[] = [
  {
    id: "section-1", order: 1,
    title: t("Fuel & Macro Fitness", "Drivstoff- og makrofitness"),
    description: t("How intentionally do you give your body the amount and type of fuel it currently needs?", "Hvor bevisst gir du kroppen mengden og typen drivstoff den trenger akkurat nå?"),
    questions: [
      q(1, t("When putting together a normal meal, how much do you consider protein, carbohydrate and fat?", "Når du setter sammen et vanlig måltid, hvor mye tenker du på protein, karbohydrat og fett?"), choices(
        ["I mostly choose based on what I want or what is available.", "Jeg velger for det meste ut fra hva jeg har lyst på eller hva som er tilgjengelig."], ["I know the balance matters, but I rarely make deliberate changes.", "Jeg vet at balansen betyr noe, men gjør sjelden bevisste endringer."], ["I intentionally consider the balance when putting together many of my meals.", "Jeg vurderer bevisst balansen når jeg setter sammen mange av måltidene mine."], ["I consistently build meals around an appropriate balance for my current needs.", "Jeg setter konsekvent sammen måltider med en balanse som passer mine nåværende behov."], ["I comfortably change that balance when my activity, goals or circumstances change.", "Jeg endrer enkelt denne balansen når aktiviteten, målene eller omstendighetene mine endrer seg."])),
      q(2, t("How intentionally do you manage your protein intake?", "Hvor bevisst styrer du proteininntaket ditt?"), choices(
        ["I rarely think specifically about protein.", "Jeg tenker sjelden spesifikt på protein."], ["I know I should probably get enough, but my intake varies a lot.", "Jeg vet at jeg trolig bør få i meg nok, men inntaket varierer mye."], ["I deliberately include a meaningful protein source in most meals.", "Jeg inkluderer bevisst en god proteinkilde i de fleste måltider."], ["I consistently eat an amount that supports my activity, recovery and goals.", "Jeg spiser konsekvent en mengde som støtter aktiviteten, restitusjonen og målene mine."], ["I adjust my protein intake when my training, recovery, age or goals change.", "Jeg justerer proteininntaket når treningen, restitusjonen, alderen eller målene mine endrer seg."])),
      q(3, t("How do you adjust your carbohydrate intake when your physical activity changes?", "Hvordan justerer du karbohydratinntaket når den fysiske aktiviteten din endrer seg?"), choices(
        ["I generally eat the same amount regardless of activity.", "Jeg spiser stort sett samme mengde uansett aktivitet."], ["I notice I sometimes want more or less carbohydrate when activity changes.", "Jeg merker at jeg av og til ønsker mer eller mindre karbohydrat når aktiviteten endrer seg."], ["I occasionally adjust the amount deliberately.", "Jeg justerer av og til mengden bevisst."], ["I consistently match carbohydrate intake reasonably well to my activity and performance needs.", "Jeg tilpasser konsekvent karbohydratinntaket rimelig godt til aktivitets- og prestasjonsbehovene mine."], ["I comfortably move between lower and higher carbohydrate intake based on what my body is being asked to do.", "Jeg veksler enkelt mellom lavere og høyere karbohydratinntak ut fra hva kroppen min skal gjøre."])),
      q(4, t("How do you adjust dietary fat as part of your overall energy intake?", "Hvordan justerer du fett i kosten som del av det totale energiinntaket ditt?"), choices(
        ["I rarely think about how much fat I eat.", "Jeg tenker sjelden på hvor mye fett jeg spiser."], ["I know fat contributes energy, but I do not usually adjust it intentionally.", "Jeg vet at fett bidrar med energi, men justerer det vanligvis ikke bevisst."], ["I sometimes change fat intake depending on the rest of my diet.", "Jeg endrer noen ganger fettinntaket avhengig av resten av kostholdet."], ["I consistently consider fat alongside carbohydrate and my total energy needs.", "Jeg vurderer konsekvent fett sammen med karbohydrat og det totale energibehovet mitt."], ["I comfortably change the balance between fat and carbohydrate depending on my current needs rather than feeling attached to one approach.", "Jeg endrer enkelt balansen mellom fett og karbohydrat etter mine nåværende behov, uten å være bundet til én tilnærming."])),
      q(5, t("When your overall activity changes substantially for several weeks, what happens to the total amount you eat?", "Når det samlede aktivitetsnivået ditt endrer seg betydelig i flere uker, hva skjer med den totale mengden du spiser?"), choices(
        ["I usually eat roughly the same amount.", "Jeg spiser vanligvis omtrent samme mengde."], ["My intake changes mainly because my appetite changes.", "Inntaket mitt endres hovedsakelig fordi appetitten endrer seg."], ["I sometimes deliberately eat more or less when my activity changes.", "Jeg spiser noen ganger bevisst mer eller mindre når aktiviteten endrer seg."], ["I consistently adjust my total intake when my energy needs clearly change.", "Jeg justerer konsekvent totalinntaket når energibehovet tydelig endrer seg."], ["I proactively adjust intake when I know demand is changing, then refine it based on energy, hunger, recovery and performance.", "Jeg justerer inntaket på forhånd når jeg vet at behovet endrer seg, og finjusterer deretter ut fra energi, sult, restitusjon og prestasjon."]))
    ]
  },
  {
    id: "section-2", order: 2,
    title: t("Nutrition Adaptability & Metabolic Flexibility", "Ernæringsmessig tilpasningsevne og metabolsk fleksibilitet"),
    description: t("Can you function well when food timing, fuel availability and your normal routine change?", "Kan du fungere godt når tidspunkt for mat, tilgang på drivstoff og den vanlige rutinen din endrer seg?"),
    questions: [
      q(6, t("Your normal meal is unexpectedly delayed by several hours. What best describes you?", "Det vanlige måltidet ditt blir uventet flere timer forsinket. Hva beskriver deg best?"), choices(["My mood, concentration or energy usually deteriorates quickly.", "Humøret, konsentrasjonen eller energien min blir vanligvis raskt dårligere."], ["I can manage it, but the hunger becomes very distracting.", "Jeg klarer det, men sulten blir svært distraherende."], ["I am usually able to continue normally even though I am hungry.", "Jeg klarer vanligvis å fortsette som normalt selv om jeg er sulten."], ["I am consistently comfortable adjusting meal timing when needed.", "Jeg er konsekvent komfortabel med å justere måltidstidspunktet ved behov."], ["Meal timing is flexible for me, and unexpected changes rarely determine how well I function.", "Måltidstidspunktene mine er fleksible, og uventede endringer avgjør sjelden hvor godt jeg fungerer."])),
      q(7, t("You feel like eating between meals. What usually happens next?", "Du får lyst til å spise mellom måltidene. Hva skjer vanligvis videre?"), choices(["I normally eat something without thinking much about why.", "Jeg spiser vanligvis noe uten å tenke særlig over hvorfor."], ["I sometimes recognize that it may not be physical hunger.", "Jeg innser noen ganger at det kanskje ikke er fysisk sult."], ["I usually identify whether it is hunger, habit, stress, boredom or opportunity.", "Jeg identifiserer vanligvis om det er sult, vane, stress, kjedsomhet eller anledning."], ["I consistently use that awareness when deciding whether or not to eat.", "Jeg bruker konsekvent denne bevisstheten når jeg avgjør om jeg skal spise eller ikke."], ["I respond appropriately to the reason, including eating when genuine hunger or increased need tells me that food would be useful.", "Jeg responderer hensiktsmessig på årsaken, også ved å spise når reell sult eller økt behov forteller meg at mat vil være nyttig."])),
      q(8, t("What best describes your relationship with fasting or intentionally extending the time between meals?", "Hva beskriver best forholdet ditt til faste eller det å bevisst forlenge tiden mellom måltider?"), choices(["I rarely do it and generally feel I need to eat on my normal schedule.", "Jeg gjør det sjelden og føler vanligvis at jeg må spise til vanlig tid."], ["I have experimented with it but mainly see it as a diet or weight-control strategy.", "Jeg har eksperimentert med det, men ser det hovedsakelig som en diett- eller vektkontrollstrategi."], ["I can comfortably extend the time between meals when I choose to.", "Jeg kan komfortabelt forlenge tiden mellom måltider når jeg velger det."], ["I use fasting selectively when it fits my circumstances or goals.", "Jeg bruker faste selektivt når det passer omstendighetene eller målene mine."], ["I am equally comfortable fasting or eating more frequently and choose between them based on what best serves my current needs.", "Jeg er like komfortabel med å faste som å spise oftere, og velger mellom dem ut fra hva som best tjener mine nåværende behov."])),
      q(9, t("Your normal way of eating suddenly becomes difficult to follow because of travel, work or family commitments. What usually happens?", "Den vanlige måten din å spise på blir plutselig vanskelig å følge på grunn av reise, arbeid eller familieforpliktelser. Hva skjer vanligvis?"), choices(["My eating becomes fairly random.", "Spisingen min blir ganske tilfeldig."], ["I try to keep following the same rules even when they no longer fit well.", "Jeg prøver å følge de samme reglene selv når de ikke lenger passer godt."], ["I make some practical adjustments.", "Jeg gjør noen praktiske justeringer."], ["I maintain the important principles while changing the structure around them.", "Jeg beholder de viktige prinsippene mens jeg endrer strukturen rundt dem."], ["I can change meal timing, food choices or macro balance without feeling that I have abandoned my approach.", "Jeg kan endre måltidstidspunkt, matvalg eller makrobalanse uten å føle at jeg har forlatt tilnærmingen min."])),
      q(10, t("How comfortable are you functioning across different fuel situations?", "Hvor komfortabel er du med å fungere i ulike drivstoffsituasjoner?"), choices(["I function best only when I eat in a fairly specific way.", "Jeg fungerer best bare når jeg spiser på en ganske bestemt måte."], ["I can tolerate some variation, but noticeable changes often affect how I feel.", "Jeg tåler noe variasjon, men merkbare endringer påvirker ofte hvordan jeg føler meg."], ["I generally function reasonably well across different patterns.", "Jeg fungerer generelt rimelig godt med ulike mønstre."], ["I can consistently adapt to different fuel and meal-timing situations.", "Jeg kan konsekvent tilpasse meg ulike drivstoff- og måltidssituasjoner."], ["I am comfortable moving between different patterns and deliberately choose the one that best fits the situation.", "Jeg er komfortabel med å veksle mellom ulike mønstre og velger bevisst det som passer situasjonen best."]), t("Examples: a higher-carbohydrate day, a lower-carbohydrate day, a long gap between meals or eating more frequently.", "Eksempler: en dag med mer karbohydrat, en dag med mindre karbohydrat, et langt opphold mellom måltider eller hyppigere spising."))
    ]
  },
  {
    id: "section-3", order: 3,
    title: t("Nutrient Coverage & Internal Health", "Næringsdekning og indre helse"),
    description: t("Are you giving your body what it needs beyond simply providing calories?", "Gir du kroppen det den trenger utover bare å tilføre kalorier?"),
    questions: [
      q(11,t("When deciding whether your overall diet is working nutritionally, what do you consider?","Når du vurderer om kostholdet ditt fungerer ernæringsmessig, hva tar du hensyn til?"),choices(["Mostly whether I am eating enough or controlling my weight.","Mest om jeg spiser nok eller kontrollerer vekten min."],["I also think generally about whether I eat healthy foods.","Jeg tenker også generelt på om jeg spiser sunn mat."],["I deliberately think about macros and some important nutrients.","Jeg tenker bevisst på makroer og noen viktige næringsstoffer."],["I consistently consider whether my diet provides a broad range of nutrients.","Jeg vurderer konsekvent om kostholdet gir et bredt spekter av næringsstoffer."],["I regularly look for potential gaps and adjust my food choices when my needs or eating pattern change.","Jeg ser jevnlig etter mulige mangler og justerer matvalgene når behovene eller spisemønsteret mitt endrer seg."])),
      q(12,t("How intentionally do you think about the types of fat you eat?","Hvor bevisst tenker du på hvilke typer fett du spiser?"),choices(["I rarely distinguish between different fat sources.","Jeg skiller sjelden mellom ulike fettkilder."],["I know some fats are considered better choices than others.","Jeg vet at noen typer fett regnes som bedre valg enn andre."],["I deliberately include several good fat sources, including omega-3 foods.","Jeg inkluderer bevisst flere gode fettkilder, inkludert mat med omega-3."],["I consistently think about the overall mix of fats in my diet.","Jeg tenker konsekvent på den samlede blandingen av fett i kostholdet mitt."],["I adjust my food choices when needed to improve the balance of essential fats, including omega-3.","Jeg justerer matvalgene ved behov for å forbedre balansen av essensielle fettsyrer, inkludert omega-3."])),
      q(13,t("How do you approach vitamins, minerals and other micronutrients?","Hvordan forholder du deg til vitaminer, mineraler og andre mikronæringsstoffer?"),choices(["I generally assume my normal diet covers them.","Jeg antar generelt at det vanlige kostholdet dekker dem."],["I am aware that gaps can exist but rarely look for them.","Jeg er klar over at mangler kan finnes, men ser sjelden etter dem."],["I intentionally choose nutrient-rich foods to help cover my needs.","Jeg velger bevisst næringsrik mat for å dekke behovene mine."],["I consistently consider whether my overall diet may be missing something important.","Jeg vurderer konsekvent om kostholdet som helhet kan mangle noe viktig."],["I adjust my foods or other nutrition strategies when my diet, lifestyle or individual needs create a likely gap.","Jeg justerer mat eller andre ernæringsstrategier når kosthold, livsstil eller individuelle behov sannsynligvis skaper en mangel."])),
      q(14,t("How intentionally do you use supplements to cover persistent nutrient gaps created by your diet, food quality, lifestyle and individual needs?","Hvor bevisst bruker du kosttilskudd for å dekke vedvarende næringsmangler som kan oppstå på grunn av kosthold, matkvalitet, livsstil og individuelle behov?"),choices(["I do not use supplements consistently or follow a plan for covering nutrient gaps.","Jeg bruker ikke kosttilskudd konsekvent eller følger en plan for å dekke næringsmangler."],["I take some general supplements, but I am not sure which persistent gaps they are intended to cover.","Jeg tar noen generelle kosttilskudd, men er usikker på hvilke vedvarende mangler de skal dekke."],["I use specific supplements to address common or likely gaps in my nutrition.","Jeg bruker bestemte kosttilskudd for å dekke vanlige eller sannsynlige mangler i ernæringen min."],["I follow a consistent supplement plan based on the likely gaps created by my diet, food quality, lifestyle and individual needs.","Jeg følger en konsekvent tilskuddsplan basert på sannsynlige mangler som skyldes kosthold, matkvalitet, livsstil og individuelle behov."],["I use a targeted supplement plan and review it using relevant assessment, testing or qualified guidance so persistent needs remain covered as my circumstances change.","Jeg bruker en målrettet tilskuddsplan og vurderer den jevnlig ved hjelp av relevant kartlegging, testing eller kvalifisert veiledning, slik at vedvarende behov forblir dekket når omstendighetene endrer seg."])),
      q(15,t("You repeatedly notice that a food that is generally considered healthy does not seem to agree with you. What are you most likely to do?","Du merker gjentatte ganger at en matvare som generelt regnes som sunn, ikke ser ut til å passe deg. Hva gjør du mest sannsynlig?"),choices(["Keep eating it because it is supposed to be good for me.","Fortsette å spise den fordi den skal være bra for meg."],["Wonder whether it might be affecting me but make no deliberate change.","Lure på om den påvirker meg, men ikke gjøre noen bevisst endring."],["Pay attention to whether the pattern repeats.","Følge med på om mønsteret gjentar seg."],["Adjust the amount, frequency or preparation and observe what happens.","Justere mengden, hyppigheten eller tilberedningen og observere hva som skjer."],["Use my response to decide how that food fits into my own diet rather than assuming the same foods work equally well for everyone.","Bruke min egen respons til å avgjøre hvordan matvaren passer i mitt kosthold, i stedet for å anta at samme mat fungerer like godt for alle."]))
    ]
  },
  {
    id:"section-4",order:4,title:t("Feedback, Recovery & Individualization","Tilbakemelding, restitusjon og individualisering"),description:t("Do you notice what is happening and change course before simply pushing harder?","Legger du merke til hva som skjer og endrer kurs før du bare presser hardere?"),questions:[
      q(16,t("How do you normally judge whether your nutrition approach is working?","Hvordan vurderer du vanligvis om ernæringstilnærmingen din fungerer?"),choices(["Mainly by weight or appearance.","Hovedsakelig ut fra vekt eller utseende."],["I notice some other things, such as energy or hunger.","Jeg legger merke til noen andre ting, som energi eller sult."],["I deliberately look at several signals, such as energy, digestion, recovery or performance.","Jeg ser bevisst på flere signaler, som energi, fordøyelse, restitusjon eller prestasjon."],["I consistently look for patterns across several relevant signals.","Jeg ser konsekvent etter mønstre på tvers av flere relevante signaler."],["I adapt my nutrition when the overall pattern suggests my current approach is no longer serving me well.","Jeg tilpasser ernæringen når helhetsmønsteret tyder på at den nåværende tilnærmingen ikke lenger fungerer godt for meg."])),
      q(17,t("You know the coming week will involve much more training or physical work than normal. What are you most likely to do?","Du vet at den kommende uken vil innebære mye mer trening eller fysisk arbeid enn normalt. Hva gjør du mest sannsynlig?"),choices(["Eat normally and see what happens.","Spise som normalt og se hva som skjer."],["Expect that I will probably become hungrier.","Forvente at jeg sannsynligvis blir mer sulten."],["Plan to increase food somewhat.","Planlegge å øke matinntaket noe."],["Deliberately adjust my intake before recovery or performance begins to suffer.","Bevisst justere inntaket før restitusjon eller prestasjon begynner å lide."],["Plan the increase in fuel around the additional demand, then refine it based on how my energy, hunger and recovery respond.","Planlegge økningen i drivstoff rundt det ekstra behovet, og deretter finjustere ut fra hvordan energi, sult og restitusjon responderer."])),
      q(18,t("During a period of poor sleep or high stress, your appetite changes noticeably. How do you usually handle it?","I en periode med dårlig søvn eller mye stress endrer appetitten din seg merkbart. Hvordan håndterer du det vanligvis?"),choices(["I mostly react to whatever my appetite is doing.","Jeg reagerer stort sett bare på det appetitten gjør."],["I recognize what is happening but try to keep eating exactly as normal.","Jeg forstår hva som skjer, men prøver å spise akkurat som normalt."],["I make some adjustments while trying to improve the underlying sleep or stress problem.","Jeg gjør noen justeringer samtidig som jeg prøver å forbedre det underliggende søvn- eller stressproblemet."],["I consistently adapt my food choices or meal structure while prioritizing recovery.","Jeg tilpasser konsekvent matvalgene eller måltidsstrukturen samtidig som jeg prioriterer restitusjon."],["I treat nutrition, stress, sleep and recovery as connected and adjust my expectations and strategy until the situation improves.","Jeg behandler ernæring, stress, søvn og restitusjon som sammenhengende, og justerer forventninger og strategi til situasjonen bedrer seg."])),
      q(19,t("How do you use measurements or nutrition-related testing?","Hvordan bruker du målinger eller ernæringsrelaterte tester?"),choices(["I rarely use objective information unless something is clearly wrong.","Jeg bruker sjelden objektiv informasjon med mindre noe tydelig er galt."],["I mainly use whatever measurements happen to be available.","Jeg bruker hovedsakelig de målingene som tilfeldigvis er tilgjengelige."],["I use relevant measurements when I have a specific question.","Jeg bruker relevante målinger når jeg har et konkret spørsmål."],["I use appropriate data when it can help confirm or challenge what I think is happening.","Jeg bruker passende data når de kan bidra til å bekrefte eller utfordre det jeg tror skjer."],["I choose measurements because the result could change a decision, then use that information alongside how I feel and function.","Jeg velger målinger fordi resultatet kan endre en beslutning, og bruker deretter informasjonen sammen med hvordan jeg føler meg og fungerer."])),
      q(20,t("Something you have been doing nutritionally for months begins producing different results. What are you most likely to do?","Noe du har gjort ernæringsmessig i flere måneder begynner å gi andre resultater. Hva gjør du mest sannsynlig?"),choices(["Continue because it worked before.","Fortsette fordi det fungerte før."],["Try doing the same thing more consistently.","Prøve å gjøre det samme mer konsekvent."],["Change one obvious part of the strategy.","Endre én åpenbar del av strategien."],["Review what else has changed and adjust the most likely cause.","Gjennomgå hva annet som har endret seg og justere den mest sannsynlige årsaken."],["Reassess the situation without attachment to the old strategy and adapt based on what the current feedback is telling me.","Revurdere situasjonen uten å være bundet til den gamle strategien, og tilpasse meg ut fra det dagens tilbakemeldinger forteller."]))
    ]
  },
  {
    id:"section-5",order:5,title:t("Longevity & Healthspan","Lang levetid og helseår"),description:t("Are your current choices helping you remain strong, capable and healthy for as much of your life as possible?","Hjelper valgene dine nå deg med å forbli sterk, funksjonell og frisk gjennom så mye av livet som mulig?"),questions:[
      q(21,t("When you think about successful nutrition, what matters most to you?","Når du tenker på vellykket ernæring, hva betyr mest for deg?"),choices(["Weight.","Vekt."],["Weight and appearance.","Vekt og utseende."],["Appearance, energy and performance.","Utseende, energi og prestasjon."],["Current performance plus maintaining good health and physical capability.","Nåværende prestasjon samt å opprettholde god helse og fysisk funksjon."],["I consider both how I function today and whether my habits support strength, metabolic health, brain health and independence later in life.","Jeg vurderer både hvordan jeg fungerer i dag og om vanene mine støtter styrke, metabolsk helse, hjernehelse og selvstendighet senere i livet."])),
      q(22,t("How much does preserving muscle influence your nutrition?","Hvor mye påvirker det å bevare muskelmasse ernæringen din?"),choices(["I rarely think about it.","Jeg tenker sjelden på det."],["I mainly think about muscle in relation to appearance.","Jeg tenker hovedsakelig på muskler i forbindelse med utseende."],["I deliberately support muscle when I am training.","Jeg støtter bevisst musklene når jeg trener."],["I consistently support muscle through protein, enough food, training and recovery.","Jeg støtter konsekvent musklene gjennom protein, nok mat, trening og restitusjon."],["I treat preserving muscle and strength as a lifelong priority and adapt my nutrition as my needs change with age and activity.","Jeg behandler bevaring av muskler og styrke som en livslang prioritet, og tilpasser ernæringen når behovene endrer seg med alder og aktivitet."])),
      q(23,t("How much do your nutrition choices take metabolic health into account?","Hvor mye tar ernæringsvalgene dine hensyn til metabolsk helse?"),choices(["I mainly think about whether my weight is acceptable.","Jeg tenker hovedsakelig på om vekten min er akseptabel."],["I know metabolic health matters but rarely make choices specifically around it.","Jeg vet at metabolsk helse er viktig, men tar sjelden valg spesifikt ut fra den."],["I deliberately make some choices that support stable energy and metabolic health.","Jeg tar bevisst noen valg som støtter stabil energi og metabolsk helse."],["I consistently consider how nutrition, activity, sleep and body composition affect metabolic health over time.","Jeg vurderer konsekvent hvordan ernæring, aktivitet, søvn og kroppssammensetning påvirker metabolsk helse over tid."],["I adapt my habits with the goal of maintaining good metabolic function across different ages, activity levels and circumstances.","Jeg tilpasser vanene mine med mål om å opprettholde god metabolsk funksjon gjennom ulike aldre, aktivitetsnivåer og omstendigheter."])),
      q(24,t("You are choosing between two approaches. One gives faster visible results but is harder to sustain. The other is slower but fits your life better. What most influences your choice?","Du velger mellom to tilnærminger. Den ene gir raskere synlige resultater, men er vanskeligere å opprettholde. Den andre er langsommere, men passer livet ditt bedre. Hva påvirker valget ditt mest?"),choices(["I usually choose the faster result.","Jeg velger vanligvis det raskere resultatet."],["I usually try the faster option first and change later if needed.","Jeg prøver vanligvis det raskere alternativet først og endrer senere ved behov."],["I consider both speed and sustainability.","Jeg vurderer både hastighet og bærekraft."],["I usually choose the option I believe I can maintain without harming energy, recovery or quality of life.","Jeg velger vanligvis alternativet jeg tror jeg kan opprettholde uten å skade energi, restitusjon eller livskvalitet."],["I judge both approaches by the result they produce now and the likely effect of repeating them for months or years.","Jeg vurderer begge tilnærmingene ut fra resultatet de gir nå og den sannsynlige effekten av å gjenta dem i måneder eller år."])),
      q(25,t("Your nutrition goal is working on paper, but over time you notice that your strength, energy or quality of life is moving in the wrong direction. What are you most likely to do?","Ernæringsmålet ditt fungerer på papiret, men over tid merker du at styrken, energien eller livskvaliteten beveger seg i feil retning. Hva gjør du mest sannsynlig?"),choices(["Continue while the main goal is still improving.","Fortsette så lenge hovedmålet fortsatt forbedres."],["Keep going for a while longer before changing anything.","Fortsette en stund til før jeg endrer noe."],["Reduce the intensity of the approach.","Redusere intensiteten i tilnærmingen."],["Adjust the strategy so the goal can continue without unnecessarily sacrificing function or recovery.","Justere strategien slik at målet kan fortsette uten unødvendig å ofre funksjon eller restitusjon."],["Reconsider both the strategy and the goal, then choose an approach that better balances the result I want with the health and capability I want to preserve.","Revurdere både strategien og målet, og deretter velge en tilnærming som bedre balanserer ønsket resultat med helsen og funksjonsevnen jeg vil bevare."]))
    ]
  }
] as const;

export const nutritionAssessmentQuestions = nutritionAssessmentSections.flatMap((section) => section.questions);
export const NUTRITION_ASSESSMENT_TOTAL_QUESTIONS = 25;
export const NUTRITION_ASSESSMENT_MAX_SCORE = 100;
