import { supabaseAdmin } from '@/lib/supabase/server'
import { FAST_OCCURRENCES, londonDateOnly } from '@/lib/quest/fasting-content'

// The open assessment has no facilitator and no account. A response is owned by
// a random token the browser holds in both a cookie and localStorage, which is
// what lets someone reload, lose signal, or close the tab and carry on where
// they were. It is device-bound by nature: a different phone starts fresh.
export type OpenResponse = {
  token: string
  created_at: string
  updated_at: string
  answers: Record<string, string>
  section_scores: number[]
  total_score: number
  submitted_at?: string
  email?: string
  display_name?: string
  fasting_challenge?: { opted_in: boolean; track?: string; status: string; updated_at: string }
}

const openKey = (token: string) => `nutrition_open_${token}`

async function read<T>(key: string): Promise<T | null> {
  const { data, error } = await supabaseAdmin.from('app_config').select('value').eq('key', key).maybeSingle()
  if (error) throw error
  if (!data?.value) return null
  return (typeof data.value === 'string' ? JSON.parse(data.value) : data.value) as T
}
async function write(key: string, value: unknown) {
  const { error } = await supabaseAdmin.from('app_config').upsert({ key, value: JSON.stringify(value) }, { onConflict: 'key' })
  if (error) throw error
}

/** Tokens are generated by the client but never trusted as given. */
export const isValidToken = (token: unknown): token is string =>
  typeof token === 'string' && /^[a-zA-Z0-9_-]{16,64}$/.test(token)

export const getOpenResponse = (token: string) => read<OpenResponse>(openKey(token))
export const saveOpenResponse = (response: OpenResponse) => write(openKey(response.token), response)

export async function listOpenResponses(): Promise<OpenResponse[]> {
  const { data, error } = await supabaseAdmin.from('app_config').select('value').like('key', 'nutrition_open_%')
  if (error) throw error
  return (data || []).map((row: { value: unknown }) => (typeof row.value === 'string' ? JSON.parse(row.value) : row.value) as OpenResponse)
}

export function blankResponse(token: string): OpenResponse {
  const now = new Date().toISOString()
  return { token, created_at: now, updated_at: now, answers: {}, section_scores: [0, 0, 0, 0, 0], total_score: 0 }
}

/** Same rules as the facilitated submit route, so the two can never disagree. */
export function scoreAnswers(answers: Record<string, string>) {
  const section_scores = [0, 0, 0, 0, 0]
  for (const [id, key] of Object.entries(answers)) {
    const index = Math.ceil(Number(id.slice(1)) / 5) - 1
    if (index < 0 || index > 4) continue
    section_scores[index] += Math.max(0, 'ABCDE'.indexOf(key))
  }
  return { section_scores, total_score: section_scores.reduce((a, b) => a + b, 0) }
}

/**
 * The challenge is tied to fixed September dates, so it stops being offered
 * once the last fast has begun rather than inviting a stranger months later to
 * something that already happened.
 */
export function challengeStillOpen(now = new Date()): boolean {
  const last = FAST_OCCURRENCES.map((o) => o.startDate).sort().pop()
  if (!last) return false
  return londonDateOnly(now) <= last
}
