export const no = {
  // Navigation & Common
  nav: {
    products: "Kasser",
    cuts: "Kutt",
    myOrders: "Min side",
    admin: "Admin",
    breeds: "Raser",
    hatchingTips: "Rugetips",
    oppdelingsplan: "Oppdelingsplan",
    minebestillinger: "Mine bestillinger",
    logout: "Logg ut",
    login: "Logg inn",
    order: "Bestill",
    goToEggs: "GÃ¥ til Rugeegg",
    goToPigs: "GÃ¥ til Ullgris",
    back: "Tilbake",
    backToHome: "Tilbake til forsiden",
  },

  // Common words/actions
  common: {
    close: "Lukk",
    save: "Lagre",
    cancel: "Avbryt",
    loading: "Laster...",
    error: "Noe gikk galt",
    confirm: "Bekreft",
    edit: "Endre",
    delete: "Slett",
    add: "Legg til",
    remove: "Fjern",
    continue: "Fortsett",
    processing: "Behandler...",
    free: "Gratis",
    total: "Totalt",
    kr: "kr",
    kg: "kg",
    stk: "stk",
    week: "uke",
    year: "Ã¥r",
    currency: "kr",
    backTo: "Tilbake til",
    languageCodeNo: "NO",
    languageCodeEn: "EN",
  },

  // Hero section
  hero: {
    season: "Sesong 2026",
    seasonOnce: "Kun Ã©n sesong i Ã¥ret",
    porkFrom: "Ullgris fra",
    headline: "Ullgris fra",
    title: "Rugeegg fra Tinglum Gard",
    farmName: "Tinglum GÃ¥rd",
    subtitle: "Gris fra Tinglum GÃ¥rd i Namdalseid. Grisene vokser opp pÃ¥ gÃ¥rden gjennom 2026, slaktes lokalt i nov/des, og hentes fersk eller frossen.",
    cta: "Reserver nÃ¥",
    reserveNow: "Reserver nÃ¥",
    learnMore: "Les mer om produktet",
    joinWaitlist: "Bli med pÃ¥ venteliste",
    qualityHeadline: "Norsk kvalitet",
    tagline: "Vakuumpakket, fryseklart, levert uke 48.",
    reserveBeforeLate: "Reserver din pakke fÃ¸r det er for sent",
    description: "Gris fra Tinglum GÃ¥rd i Namdalseid. Grisene vokser opp pÃ¥ gÃ¥rden gjennom 2026, slaktes lokalt i nov/des, og hentes fersk eller frossen.",
    localRaised: "Lokalt oppvokst",
    qualityGuarantee: "Kvalitetsgaranti",
    limitedOffer: "Begrenset tilbud",
    limitedProduction: "Vi produserer kun det vi har kapasitet til. NÃ¥r sesongens kasser er reservert, stenger vi bestillingen til 2027.",
    reservePackageNow: "Reserver din kasse nÃ¥",
  },

  // Eggs hero
  eggsHero: {
    title: "Rugeegg fra Tinglum Gard",
    subtitle:
      "Rugeegg fra Tinglum GÃ¥rd i Namdalseid. Ferske, nÃ¸ye utvalgte egg fra flere raser og vakre eggfarger, levert uke for uke i sesong.",
  },

  // Eggs browse
  browse: {
    byBreed: "Etter rase",
    byWeek: "Etter uke",
    week: "Uke",
    soldOut: "Utsolgt",
    eggsAvailable: "egg tilgjengelig",
  },

  // Egg breed detail labels
  breed: {
    deliveryFrom: "Sending fra",
    pricePerEgg: "kr/egg",
    calculatedAtCheckout: "beregnes i kassen",
    viewDetails: "Se detaljer",
    eggColor: "Eggfarge",
    production: "Produksjon",
    minOrder: "Minimum",
    eggs: "egg",
    characteristics: "Egenskaper",
    size: "Storrelse",
    minEggWeight: "Minste eggvekt",
    temperament: "Temperament",
    hatchingInfo: "Klekkinfo",
    incubation: "Ruging",
    days: "dager",
    temperature: "Temperatur",
    humidity: "Fuktighet",
    qualityNote: "Ferske egg fra frittgaende honer. Sending og frakt beregnes i kassen.",
    selectWeek: "Velg uke",
    available: "Tilgjengelig",
  },

  // Quantity selector
  quantity: {
    available: "tilgjengelig",
    numberOfEggs: "Antall egg",
    min: "Min",
    max: "Maks",
    eggs: "egg",
    subtotal: "Subtotal",
    shippingCalculated: "frakt beregnes i kassen",
    addToCart: "Legg i handlekurv",
  },

  // Product/Box selection
  product: {
    chooseYourBox: "Velg din kasse",
    choosePackage: "Velg din kasse",
    twoSizes: "To stÃ¸rrelser Ã¥ velge mellom",
    sameQuality: "Samme hÃ¸ye kvalitet uansett stÃ¸rrelse. Velg kassen som passer best for din husholdning.",
    smallBox: "Mindre kasse",
    smallerPackage: "Mindre kasse",
    largeBox: "StÃ¸rre kasse",
    largerPackage: "StÃ¸rre kasse",
    mostPopular: "Mest populÃ¦r",
    betterPricePerKg: "Bedre pris per kg",
    perfectFor2to3: "Perfekt for 2-3 personer eller mindre forbruk",
    idealFor4to6: "Ideell for 4-6 personer eller stÃ¸rre forbruk",
    inEach8kgBox: "I hver 8 kg kasse:",
    inEach8kg: "I hver 8 kg kasse",
    inEach12kgBox: "I hver 12 kg kasse:",
    inEach12kg: "I hver 12 kg kasse",
    reserve8kg: "Reserver 8 kg kasse",
    reserve12kg: "Reserver 12 kg kasse",
    boxesLeft: "bokser igjen",
    lowStock: "FÃ¥ igjen",
    soldOut: "Utsolgt",
    priceDeposit: "Betales nÃ¥",
    priceRemainder: "Rest ved levering",
    deposit50: "Forskudd (50%)",
    remainderAtDelivery: "Rest ved levering",
    balanceOnDelivery: "Rest ved levering",
    totalPrice: "Totalpris",
    seeDetails: "Se innhold",
    kg: "kg",
    orderNow: "Reserver nÃ¥",
    joinWaitlist: "Bli med pÃ¥ venteliste",
    box8: "8 kg kasse",
    box12: "12 kg kasse",
  },

  // Product detail page
  productDetail: {
    title: "Ullgris KjÃ¸ttpakke",
    variation: "Innholdet varierer med tilgjengelighet, men dette er alltid med:",
    categories: {
      ribbe: "Ribbe",
      sausages: "PÃ¸lser",
      bacon: "Bacon",
      chops: "Koteletter",
      stew: "Skinkesteik",
    },
    addons: {
      title: "Tillegg",
      disabled: "Tillegg kan velges i bestillingsprosessen",
      delivery: "Henting Trondheim",
      highway: "Henting langs E6",
      fresh: "Fersk levering (uke 50-51)",
    },
  },

  // Availability section
  availability: {
    title: "Tilgjengelighet",
    boxesAvailable: "Kasser tilgjengelig",
    remainingBoxes: "FÃ¥ igjen",
    fewLeft: "FÃ¥ igjen",
    soldOut: "Utsolgt",
    soldOutComplete: "Utsolgt",
    reserveBeforeTooLate: "Reserver fÃ¸r det er for sent",
    reserveBeforeLate: "Reserver fÃ¸r det er for sent",
    seasonProductionComplete: "Sesongproduksjon fullfÃ¸rt",
    seasonComplete: "Sesongproduksjon fullfÃ¸rt",
  },

  // Timeline/How it works
  timeline: {
    title: "Slik fungerer det",
    subtitle: "Fra bestilling til levering",
    tagline: "Grisene vokser gjennom 2026 â€¢ Fersk levering i desember",
    reserveNow: "Reserver din pakke nÃ¥",
    howItWorks: "Slik fungerer det",
    fromOrderToDelivery: "Fra bestilling til levering",
    step1Title: "Reserver din pakke nÃ¥",
    step1Desc: "Betal forskudd (50%) med Vipps. Din plass er sikret nÃ¥r betalingen er gjennomfÃ¸rt.",
    step1Time: "Uke 45",
    step2Title: "Restsum betales",
    step2Desc: "Innen uke 46 betaler du resterende 50% av totalbelÃ¸pet. Du fÃ¥r betalingsinformasjon pÃ¥ e-post.",
    step2Time: "Uke 46-47",
    step3Title: "Slakting og frossen levering",
    step3Desc: "Grisene slaktes profesjonelt og pakkes fersk. Deretter fryses alt ned for optimal holdbarhet og leveres i uke 48-49.",
    step3Time: "Uke 48-49",
    step4Title: "Fersk levering (tilvalg)",
    step4Desc: "Mot et lite tillegg kan du velge fersk levering i uke 50-51. Perfekt hvis du Ã¸nsker kjÃ¸ttet helt ferskt!",
    step4Time: "Uke 50-51",
    optional: "Valgfritt",
    week44: "Uke 45: Betaling fullfÃ¸res",
    week46: "Uke 47: Siste frist for endringer",
    week48: "Uke 49: Levering og utlevering",
    week44Desc: "Du fÃ¥r beskjed og fullfÃ¸rer betaling fÃ¸r levering.",
    week46Desc: "Endre stÃ¸rrelse og tillegg frem til fristen, etterpÃ¥ lÃ¥ses bestillingen.",
    week48Desc: "Henting eller levering etter valgt alternativ.",
  },

  // FAQ
  faq: {
    title: "SpÃ¸rsmÃ¥l og svar",
    badge: "OSS",
    commonQuestions: "Vanlige spÃ¸rsmÃ¥l",
    q1: "Hva fÃ¥r jeg i kassen?",
    a1: "Fast struktur, smÃ¥ variasjoner er normalt. Du fÃ¥r ribbe, bacon, pÃ¸lser, nakkekoteletter og skinkesteik. I tillegg legger vi med gode biter avhengig av tilgjengelighet. Alt er porsjonert, merket og vakuumpakket.",
    q2: "NÃ¥r fÃ¥r jeg leveringen?",
    a2: "Frossen kasse leveres i uke 48. Fersk kasse kan velges mot tillegg og leveres i slutten av uke 50 eller starten av uke 51.",
    q3: "Kan jeg endre bestillingen?",
    a3: "Ja, frem til uke 46. Etter fristen lÃ¥ses bestillingen slik at vi kan planlegge produksjon og pakking.",
    q4: "Hvordan henter jeg eller fÃ¥r levert?",
    a4: "Du kan velge levering langs E6 mellom StjÃ¸rdal og Namsos, eller i Trondheim sentrum. Pris vises i kassen fÃ¸r du bekrefter.",
  },

  // Checkout/Order page
  checkout: {
    title: "Bestill",
    pageTitle: "Reserver din kasse",
    subtitle: "Reserver din kasse med Vipps",
    selectSize: "Velg stÃ¸rrelse, ribbe-type og ekstra tillegg. Du betaler med VIPPS. Forskuddet nÃ¥ og tillegg og restbelÃ¸pet innen uke 46.",

    // Steps
    stepSize: "StÃ¸rrelse",
    stepRibbe: "Ribbe",
    stepExtras: "Ekstra",
    stepDelivery: "Levering",

    step1Title: "1. Velg kassestÃ¸rrelse",
    step2Title: "2. Velg ribbe-type",
    step3Title: "3. Ekstra kjÃ¸ttprodukter (valgfritt)",
    step4Title: "4. Levering og tillegg",

    // Size selection
    persons2to3: "2-3 personer",
    persons4to6: "4-6 personer",
    inBox: "I kassen:",
    moreItems: "mer",
    
    payNow: "Betal nÃ¥",
    payLater: "Betal senere",
    totalLabel: "Totalt",
    summary: "Sammendrag",

    // Ribbe selection
    selectRibbeType: "Velg ribbe-type",
    boxContains: "Din kasse inneholder ca. {size} kg ribbe. Velg hvilken type:",
    tynnribbe: "Tynnribbe",
    tynnribbeDesc: "Klassisk ribbe med ribbein - perfekt sprÃ¸stekt svor",
    familieribbe: "Familieribbe",
    familieribbeDesc: "Inkluderer kotelettkammen med ytrefileten - mer og litt magrere kjÃ¸tt",
    porchetta: "Porchetta",
    porchettaDesc: "Beinfri nedre mage - italiensk stil",
    butchersChoice: "Slakterens valg",
    butchersChoiceDesc: "Vi velger en god ribbe til deg basert pÃ¥ tilgjengelighet",
    preSelected: "ForhÃ¥ndsvalgt",
    recommended: "Anbefalt",

    // Extras
    extrasTitle: "Ekstra kjÃ¸ttprodukter (valgfritt)",
    extrasWarning: "Ekstra produkter kan ikke garanteres, og tilgangen er meget begrenset. Ved Ã¥ betale restbelÃ¸pet/ferdigstille ordren sikrer du din plass i kÃ¸en. Vi oppfyller bestillingene etter nÃ¥r restordre/ekstra bestillinger blir betalt.",
    quantity: "Mengde:",

    // Delivery
    deliveryOptions: "Leveringsalternativ",
    extraOptions: "Ekstra tilvalg",
    pickupFarm: "Henting pÃ¥ gÃ¥rden",
    pickupFarmAddress: "Tinglemsvegen 91, Namdalseid",
    pickupTrondheim: "Henting i Trondheim",
    pickupTrondheimAddress: "Veita Mat AS, Jomfrugata 17B",
    deliveryE6: "Levering langs E6",
    deliveryE6Address: "StjÃ¸rdal-Namsos",
    freshDelivery: "Fersk levering (uke 50/51)",
    freshDeliveryDesc: "Motta kassen fersk i stedet for frossen - kun pÃ¥ gÃ¥rden",

    // Summary
    deposit50Percent: "Forskudd (50%)",
    friendDiscount: "Vennerabatt (-20%)",
    discountCode: "Rabattkode",
    remainderBeforeDelivery: "Rest fÃ¸r levering",
    extraProducts: "Ekstra produkter",
    onlyOneDiscount: "Kun Ã©n rabattkode kan brukes per bestilling",
    hasDiscountCode: "Rabattkode?",

    // Terms
    depositNotRefundable: "Jeg forstÃ¥r at forskuddet ikke refunderes.",
    triggersProd: "Vi jobber med levende dyr, og bestilling av en kasse starter produksjonsplanlegging.",
    agreeToTerms: "Jeg godtar",
    termsLink: "vilkÃ¥rene for kjÃ¸pet",

    // Payment
    payWith: "Betal med",
    securePayment: "Sikker betaling med Vipps",
    contactInfoFromVipps: "Dine kontaktopplysninger hentes automatisk fra Vipps",

    // Navigation
    goToRibbeChoice: "GÃ¥ videre til ribbe-valg",
    goToExtras: "GÃ¥ videre til ekstra tillegg",
    goToDelivery: "GÃ¥ videre til levering",

    // Confirmation
    orderReceived: "Bestilling mottatt!",
    thankYou: "Takk for din bestilling. Vi har mottatt din reservasjon og vil sende deg en Vipps-betalingsforespÃ¸rsel for forskuddet pÃ¥ 50%.",
    expectedDelivery: "Forventet levering: uke 48-49.",
    orderNumber: "Bestillingsnummer",
    nextSteps: "Neste steg:",
    step1: "Du vil motta en Vipps-betalingsforespÃ¸rsel for forskuddet (50% av totalbelÃ¸pet)",
    step2: "Du fÃ¥r en bekreftelse pÃ¥ e-post nÃ¥r forskuddet er mottatt",
    step3: "Resterende belÃ¸p betales ved levering",
    seeMyOrders: "Se mine bestillinger",

    // Errors
    somethingWentWrong: "Noe gikk galt. Vennligst prÃ¸v igjen.",
  },

  // Eggs flows (browse, cart, checkout, orders)
  eggs: {
    common: {
      loading: "Laster...",
      loadingBreeds: "Laster raser...",
      loadingWeeks: "Laster uker...",
      loadingBreed: "Laster rase...",
      loadingOrder: "Laster ordre...",
      close: "Lukk",
      backToBreeds: "Tilbake til raser",
      backToCart: "Tilbake til handlekurv",
      backToShipment: "Tilbake til forsendelse",
      backToOrders: "Til mine bestillinger",
      cartAria: "Handlekurv",
      toggleLanguageAria: "Bytt sprÃ¥k",
      order: "Ordre",
      orderNumber: "Ordrenummer",
      breed: "Rase",
      breeds: "Raser",
      week: "Uke",
      shipment: "Forsendelse",
      shippingDate: "Sendingsdato",
      eggs: "egg",
      totalEggs: "Antall egg",
      summary: "Sammendrag",
      subtotal: "Subtotal",
      additions: "Tillegg",
      alreadyPaid: "Allerede betalt",
      deposit: "Forskudd",
      remainder: "RestbelÃ¸p",
      total: "Totalt",
      dueDate: "Forfallsdato",
      dueNow: "Ã… betale nÃ¥",
      notPaid: "Ikke betalt",
      daysLeft: "dager igjen",
      continueToPayment: "Fortsett til betaling",
      payWithVipps: "Betal med Vipps",
      addEggs: "Legg til egg",
      fallbackBreed: "Rugeegg",
    },
    errors: {
      loadEggData: "Kunne ikke laste eggdata.",
      loadBreeds: "Kunne ikke laste raser.",
      loadBreed: "Kunne ikke laste rase.",
      orderNotFound: "Fant ikke bestillingen.",
      couldNotFindOrder: "Bestillingen ble ikke funnet.",
      couldNotFetchOrders: "Kunne ikke hente bestillinger",
      couldNotFetchOrder: "Kunne ikke hente ordre",
      couldNotFetchInventory: "Kunne ikke hente tilgjengelige uker",
      couldNotSaveAdditions: "Kunne ikke lagre tillegg",
      couldNotStartPayment: "Kunne ikke starte betaling",
      shippingAddressMissing: "Leveringsadresse mangler. GÃ¥ tilbake og fyll ut adressen.",
      vippsLoginFailed: "Kunne ikke starte Vipps-innlogging. PrÃ¸v igjen.",
    },
    breedsPage: {
      subtitle:
        "Fire unike raser med distinkte egenskaper. Alle hÃ¸nene vÃ¥re gÃ¥r fritt og fores med Ã¸kologisk fÃ´r.",
      browseBreeds: "Se raser",
      breedNotFound: "Rase ikke funnet",
      pricePerEgg: "Pris per egg",
    },
    activeOrderPrompt: {
      title: "Du har en aktiv bestilling",
      description: "Vil du legge flere egg til samme bestilling og uke?",
      activeWeek: "Aktiv uke",
      eggsInOrderAndLeft: "{inOrder} egg i bestillingen Â· {left} igjen",
      yesContinue: "Ja, fortsett",
      noNewOrder: "Nei, ny bestilling",
    },
    cart: {
      title: "Handlekurv",
      emptyTitle: "Handlekurven er tom",
      emptyDescription: "Legg til egg for Ã¥ komme i gang",
      cartEmptyMessage: "Handlekurven er tom",
      weekLabel: "Uke",
      perEgg: "egg",
      minimum: "Minimum",
      summaryTitle: "Sammendrag",
      shippingCalculatedNext: "forsendelse beregnes i neste steg",
      addMoreEggs: "Legg til flere egg",
      readyForCheckout: "Klar for betaling!",
      mixedInfo:
        "Du kan endre antall per rase nÃ¥r som helst. Bestillingen gÃ¥r videre nÃ¥r alle kravene er oppfylt.",
      goToCheckout: "GÃ¥ til kassen",
      continueShopping: "Fortsett Ã¥ handle",
      mixedOrderTitle: "Bygg en blandet bestilling",
      mixedOrderDescription: "Legg til egg fra flere raser for Ã¥ nÃ¥ minimum 12 egg.",
      leftThisWeek: "Igjen denne uken",
      done: "Ferdig",
      ayamMinimum: "Ayam Cemani: minimum 6 egg (du har {count})",
      singleBreedMinimum: "Minimum 10 egg for en rase (du har {count})",
      mixedMinimum:
        "Minimum 12 egg totalt nÃ¥r du blander raser (med mindre en rase har 10 egg, Ayam Cemani 6). Du har {count}",
      mixedWeeks: "Velg egg fra samme uke for en samlet forsendelse.",
      onlyEggsLeftThisWeek: "Kun {count} egg igjen denne uken. Vi har foreslÃ¥tt {count} egg.",
    },
    delivery: {
      title: "Forsendelse",
      subtitle: "Velg hvordan rugeeggene skal sendes eller hentes.",
      postenTitle: "Sending med Posten",
      postenDescription: "Sendes trygt med Posten til nÃ¦rmeste hentested.",
      farmPickupTitle: "Henting pÃ¥ gÃ¥rden",
      farmPickupDescription: "Hent pÃ¥ Tinglum gÃ¥rd etter avtale.",
      e6PickupTitle: "E6 mÃ¸tepunkt",
      e6PickupDescription: "Avhenting ved avtalt mÃ¸tepunkt langs E6.",
      recommended: "Anbefalt",
      unavailableThisWeek: "Ikke tilgjengelig denne uken.",
      shippingAddressTitle: "Leveringsadresse",
      shippingAddressDescription: "Vi trenger adresse for Posten-forsendelse.",
      address: "Adresse",
      addressPlaceholder: "Gateadresse og nummer",
      postalCode: "Postnummer",
      city: "Poststed",
      cityPlaceholder: "Poststed",
      country: "Land",
      countryPlaceholder: "Norge",
      addressRequired: "Fyll ut alle adressefeltene for Ã¥ fortsette.",
      methodInfo:
        "Henting pÃ¥ gÃ¥rden og levering langs E6 Namsos-Trondheim er Ã¸nskelÃ¸sninger som kan avtales etter at forskuddet er betalt. Send en melding etter innbetalt forskudd, sÃ¥ ser vi om det er mulig Ã¥ ordne.",
    },
    payment: {
      title: "Betaling",
      subtitleFullPayment: "Betal hele belÃ¸pet for Ã¥ bekrefte bestillingen.",
      subtitleDeposit: "Betal forskuddet for eggene for Ã¥ bekrefte bestillingen.",
      fullPaymentTitle: "Full betaling",
      depositTitle: "Forskudd",
      fullPaymentDescription: "Bestillingen sendes snart, sÃ¥ hele belÃ¸pet betales nÃ¥.",
      depositDescription: "Du betaler 50% av eggene nÃ¥, resten fÃ¸r sending.",
      nonRefundableNote:
        "Forskuddet refunderes ikke. Vi jobber med levende dyr, og bestillingen setter i gang produksjonsplanlegging.",
      dueNow: "Ã… betale nÃ¥",
      depositDue: "Forskudd Ã¥ betale",
      securePaymentTitle: "Trygg betaling",
      securePaymentDescription: "Vi bruker Vipps for raske og sikre betalinger.",
      orderTitle: "Bestilling",
      packingAndShipment: "Pakking og forsendelse",
      fullPayment: "Full betaling",
      deposit: "Forskudd",
    },
    confirmation: {
      orderNotFoundTitle: "Fant ingen ordre",
      orderNotFoundDescription: "Bestillingen ble ikke funnet.",
      titleCompleted: "Bestilling mottatt!",
      titleFailed: "Betaling feilet",
      titlePending: "Venter pÃ¥ betalingsbekreftelse",
      leadCompleted: "Vi har registrert forskuddsbetalingen.",
      leadFailed: "Vipps-betalingen ble ikke fullfÃ¸rt.",
      leadPending: "Vi venter fortsatt pÃ¥ bekreftelse fra Vipps.",
      failedHelp:
        "Betalingen ble ikke registrert som fullfÃ¸rt. GÃ¥ til \"Mine bestillinger\" og prÃ¸v betaling pÃ¥ nytt.",
      pendingHelp:
        "Hvis betaling er gjennomfÃ¸rt i Vipps, oppdateres status automatisk nÃ¥r bekreftelsen kommer.",
      goToMyOrders: "Til mine bestillinger",
    },
    myOrders: {
      authTitle: "Logg inn med Vipps",
      authDescription: "For Ã¥ se dine rugeegg-bestillinger mÃ¥ du logge inn.",
      pageTitle: "Mine bestillinger",
      pageDescription: "Oversikt over dine rugeegg-bestillinger.",
      tabOrders: "Bestillinger",
      tabMessages: "Meldinger",
      noOrders: "Ingen bestillinger funnet ennÃ¥.",
      browseBreeds: "Se raser",
      quantity: "Mengde",
      total: "Total",
      delivery: "Forsendelse",
      payRemainder: "Betal rest",
      addEggs: "Legg til egg",
      timeline: "Statuslinje",
      duePrefix: "Forfaller",
      shipmentPrefix: "Forsendelse",
      additionsSuffix: "+{count} tillegg",
      statusPending: "Venter",
      statusRemainderDue: "Restbetaling",
      statusDepositPaid: "Forskudd betalt",
      statusPaid: "Betalt",
      statusPreparing: "KlargjÃ¸res",
      statusShipped: "Sendt",
      statusDelivered: "Levert",
      statusForfeited: "Forfalt",
      statusCancelled: "Kansellert",
      stepPlaced: "Bestilling",
      stepDeposit: "Forskudd",
      stepRemainder: "Restbetaling",
      stepShipment: "Sending",
      deliveryPosten: "Sending med Posten",
      deliveryE6: "E6 mÃ¸tepunkt",
      deliveryFarm: "Henting pÃ¥ gÃ¥rden",
    },
    remainderPayment: {
      unavailable: "Restbetaling er ikke tilgjengelig for denne bestillingen.",
      title: "Betal restbelÃ¸p",
      orderLabel: "Bestilling {orderNumber}",
      depositPaidEggs: "Forskudd betalt (egg)",
      addMoreEggsOptional: "Legg til flere egg (valgfritt)",
      sameShipmentWeek: "Samme sendingsuke",
      additionsClosed: "Tillegg er stengt etter kl 23:59 dagen for sending.",
      discountToday: "30% rabatt pÃ¥ ekstra egg i dag.",
      noEggsThisWeek: "Ingen tilgjengelige egg for denne uken.",
      eggsLeft: "egg igjen",
      paymentSummaryTitle: "Betalingsoversikt",
      paymentSummaryDescription: "RestbelÃ¸pet inkluderer pakking og sending.",
    },
    remainderConfirmation: {
      paymentReceivedTitle: "Betaling mottatt!",
      confirmingTitle: "Bekrefter betaling...",
      paymentReceivedLead: "Restbetalingen er registrert.",
      confirmingLead: "Dette kan ta et minutt. Siden oppdateres automatisk.",
      backToOrders: "Til mine bestillinger",
      addEggs: "Legg til egg",
    },
    weekSelector: {
      chooseMonth: "Velg mÃ¥ned",
      through: "Frem til {date}",
      weeks: "uker",
      eggs: "egg",
      weekShort: "Uke",
      weekShortAbbr: "Uke",
      eggShort: "Egg",
      backToMonths: "Tilbake til mÃ¥neder",
      available: "Tilgjengelig",
      status: "Status",
      shipsIn: "Sendes om",
      days: "dager",
      statusSoldOut: "Utsolgt",
      statusLowStock: "FÃ¥ igjen",
      statusClosed: "Stengt",
      statusLocked: "LÃ¥st",
      statusAvailable: "Tilgjengelig",
      statusNotScheduled: "Ikke planlagt",
      dayLabels: ["Man", "Tir", "Ons", "Tor", "Fre", "LÃ¸r", "SÃ¸n"],
    },
    hatchingTips: {
      title: "Rugetips",
      subtitle: "Praktiske rÃ¥d for en trygg og vellykket klekking.",
      note: "Har du spÃ¸rsmÃ¥l? Ta kontakt - vi hjelper gjerne.",
      sections: [
        {
          title: "FÃ¸r ruging",
          items: [
            "Oppbevar eggene kjÃ¸lig (12-16Â°C) og med spissen ned.",
            "Rugg helst innen 7 dager etter lagt egg for best resultat.",
            "La eggene hvile i romtemperatur 6-8 timer fÃ¸r de legges i rugemaskin.",
            "Vask ikke egg - rengjÃ¸r bare lett med tÃ¸rr klut ved behov.",
          ],
        },
        {
          title: "Under ruging",
          items: [
            "Stabil temperatur: 37,5Â°C for de fleste raser.",
            "Hold riktig fuktighet (ca. 50-55% dag 1-18).",
            "Vend eggene 3-5 ganger daglig (automatisk vending er best).",
            "Luft rugemaskinen kort daglig etter uke 2.",
          ],
        },
        {
          title: "Klekking (dag 19-21)",
          items: [
            "Ã˜k fuktigheten til 65-70% fra dag 19.",
            "Stopp vending nÃ¥r klekking starter.",
            "Ikke Ã¥pne rugemaskinen unÃ¸dvendig.",
            "La kyllingene tÃ¸rke helt fÃ¸r de flyttes.",
          ],
        },
        {
          title: "Etter klekking",
          items: [
            "Hold kyllingene varmt (32-35Â°C fÃ¸rste uke).",
            "Gi tilgang til vann og startfÃ´r umiddelbart.",
            "Senk temperaturen gradvis 2-3Â°C per uke.",
            "Observer aktivitet og appetitt - det er beste helsesignal.",
          ],
        },
      ],
    },
  },

  terms: {
    back: "Tilbake",
    title: "VilkÃ¥r for kjÃ¸p hos Tinglum GÃ¥rd",
    intro:
      "Disse vilkÃ¥rene gjelder for kjÃ¸p av varer fra Tinglum GÃ¥rd gjennom vÃ¥re nettsider. Ved Ã¥ gjennomfÃ¸re et kjÃ¸p bekrefter du at du har lest og akseptert vilkÃ¥rene.",
    sellerLabel: "Selger er:",
    buyerParagraph:
      "KjÃ¸per er den personen som gjennomfÃ¸rer bestillingen og omtales som \"kunde\".",
    sections: [
      {
        title: "1. Parter",
        bullets: [
          "Tinglum GÃ¥rd",
          "Organisasjonsnummer: 995 752 328",
          "Adresse: Tinglemsvegen 91, 7750 NAMDALSEID",
          "E-post: post@tinglum.com",
        ],
      },
      {
        title: "2. Betaling",
        paragraphs: [
          "Betaling skjer via Vipps.",
          "Forskuddet fungerer som en reservasjon av en begrenset produksjonsbatch og er bindende.",
        ],
        bullets: [
          "Ved bestilling betales et forskudd pÃ¥ 50 % av totalbelÃ¸pet.",
          "Resterende belÃ¸p betales fÃ¸r levering, i henhold til informasjon gitt ved bestilling.",
        ],
      },
      {
        title: "3. Levering",
        paragraphs: [
          "Varene leveres i henhold til valgt leveringsalternativ ved bestilling, for eksempel:",
          "Leveringstidspunkt oppgis pÃ¥ produktsiden og kan variere basert pÃ¥ sesong og produksjon.",
          "Varene leveres som hovedregel frosne og vakuumpakkede, med mindre annet er avtalt.",
        ],
        bullets: [
          "Henting pÃ¥ gÃ¥rden",
          "Levering til angitte omrÃ¥der",
          "Eventuell levering i Trondheim",
        ],
      },
      {
        title: "4. Angrerett",
        paragraphs: [
          "I henhold til angrerettloven Â§ 22 gjelder ikke angrerett for varer som:",
          "KjÃ¸p av kjÃ¸tt og kjÃ¸ttprodukter fra Tinglum GÃ¥rd omfattes derfor ikke av angrerett.",
        ],
        bullets: [
          "er produsert etter kundens spesifikasjoner, eller",
          "har et tydelig personlig preg, eller",
          "er lett bedervelige nÃ¦ringsmidler.",
        ],
      },
      {
        title: "5. Retur",
        paragraphs: [
          "Retur av varer er ikke mulig, da dette gjelder nÃ¦ringsmidler som leveres frosne eller ferske etter bestilling.",
          "Dersom Tinglum GÃ¥rd ikke er i stand til Ã¥ levere som avtalt, refunderes innbetalt belÃ¸p i sin helhet.",
        ],
      },
      {
        title: "6. Reklamasjon",
        paragraphs: [
          "Dersom varen har en mangel, mÃ¥ kunden gi beskjed innen rimelig tid etter at mangelen ble oppdaget eller burde vÃ¦rt oppdaget.",
          "Reklamasjon sendes skriftlig til e-postadressen oppgitt under punkt 1, og bÃ¸r inneholde:",
          "Reklamasjon behandles i henhold til forbrukerkjÃ¸psloven.",
        ],
        bullets: [
          "Bestillingsnummer",
          "Beskrivelse av mangelen",
          "Eventuell dokumentasjon (bilder)",
        ],
      },
      {
        title: "7. KonfliktlÃ¸sning",
        paragraphs: [
          "Eventuelle tvister forsÃ¸kes lÃ¸st i minnelighet.",
          "Dersom dette ikke lykkes, kan kunden ta saken videre til Forbrukertilsynet eller Forbrukerklageutvalget.",
        ],
      },
    ],
    legalNotice:
      "Disse vilkÃ¥rene er ment som informasjon til kunder og utgjÃ¸r ikke juridisk rÃ¥dgivning.",
  },

  // My Orders / Customer Portal
  minSide: {
    title: "Min side",
    myOrders: "Mine bestillinger",
    orders: "Bestillinger",
    referrals: "Vennerabatt",
    loginRequired: "Logg inn for Ã¥ se dine bestillinger",
    loginDesc: "Du mÃ¥ logge inn med Vipps for Ã¥ se og administrere dine bestillinger.",
    loginWithVipps: "Logg inn med Vipps",
    canEditUntil: "Du kan endre bestillingen din frem til uke {week}, {year}",
    editPeriodExpired: "Endringsperioden er utlÃ¸pt (uke {week}, {year})",
    noOrders: "Ingen bestillinger",
    noOrdersDesc: "Du har ikke lagt inn noen bestillinger ennÃ¥.",
    goToOrder: "GÃ¥ til bestilling",
    newOrder: "Legg inn ny bestilling",

    // Order status
    completed: "FullfÃ¸rt",
    depositPaid: "Forskudd betalt",
    waitingForPayment: "Venter pÃ¥ betaling",
    payRemainder: "Betal restbelÃ¸p",
    seeDetails: "Se detaljer",

    // Order details
    order: "BESTILLING",
    orderNo: "Ordre",
    box: "Kasse",
    ribbe: "Ribbe",
    delivery: "Levering",
    freshDeliveryIncluded: "Fersk levering",
    extraProductsTitle: "EKSTRA PRODUKTER",
    deposit: "Forskudd",
    remainder: "RestbelÃ¸p",
    dueDate: "Forfallsdato",
  },

  // Oppdelingsplan (Butcher diagram)
  oppdelingsplan: {
    title: "Oppdelingsplan",
    subtitle: "Trykk pÃ¥ hver del for Ã¥ se hva som er i kassen og hva du kan bestille ekstra",
    titleFull: "Oppdelingsplan - Gris",
    clickInfo: "Klikk pÃ¥ de forskjellige delene for Ã¥ se hvilke produkter som er inkludert i kassen og hva som kan bestilles ekstra",
    ourProducts: "VÃ¥re produkter",
    inBox: "I kassen",
    inBoxDesc: "Disse produktene er inkludert i standardkassen:",
    canOrder: "Kan bestilles ekstra",
    canOrderDesc: "Disse produktene kan legges til bestillingen (begrenset tilgjengelighet):",
    clickForInfo: "Klikk pÃ¥ en del av grisen for Ã¥ se produktinformasjon",
    allCuts: "Alle kutt - Oversikt",
    inBoxShort: "I kassen:",
    extraShort: "Ekstra:",
    noProductsInBox: "Ingen produkter fra denne delen i standardkassen",
    noExtraProducts: "Ingen ekstra produkter tilgjengelig fra denne delen",
    chooseRibbeType: "Velg din ribbe-type",
    ribbeTypeInfo: "Alle tre varianter bruker forskjellige deler av ribbeside og mage",
    butchersChoiceFull: "Slakterens valg: Ikke sikker? Velg 'Slakterens valg' ved bestilling, sÃ¥ velger vi basert pÃ¥ tilgjengelighet.",
    quickSummary: "Rask oversikt",
    seeDetailsBelow: "Se detaljert informasjon om hver del nedenfor",

    // Cut names and descriptions
    nakke: "Nakke",
    nakkeDesc: "Nakken er marmorert med fett og gir saftige koteletter og steik.",
    indrefilet: "Indrefilet",
    indrefiletDesc: "Indrefileten er det aller mÃ¸reste kjÃ¸ttet fra grisen.",
    kotelettkam: "Kotelettkam",
    kotelettkamDesc: "Kotelettkammen er fra ryggen og gir mÃ¸re koteletter. Dette omrÃ¥det brukes ogsÃ¥ i Familieribbe.",
    ribbeside: "Ribbeside",
    ribbesideDesc: "Ribbeside og mage gir ulike typer ribbe. Velg mellom Tynnribbe (med ribbein), Familieribbe (inkl. kotelettkam), eller Porchetta (beinfri nedre mage).",
    svinebog: "Svinebog",
    svinebogDesc: "Bogen passer perfekt til pulled pork, gryter og steik. Dette er et av de mest allsidige stykkene.",
    skinke: "Skinke/LÃ¥r",
    skinkeDesc: "Skinken/lÃ¥ret kan brukes fersk som steik, gryte, eller spekkes. Dette er en stor, mager muskelgruppe.",
    knoke: "Knoke",
    knokeDesc: "Knoken passer til kraft og gryter, eller til steik. Hver kasse inneholder 1 knoke.",
    labb: "Labb",
    labbDesc: "Labben brukes ofte til sylte og kraftsuppe.",
    polserFarse: "PÃ¸lser & Farse",
    polserFarseDesc: "Laget av trim og mindre stykker. Perfekt til hverdagsmiddag og julemat.",
  },

  // Referrals
  referrals: {
    createCode: "Opprett vennerabattkode",
    getCredit: "FÃ¥ 10% kreditt for hver venn som bruker din kode",
    howItWorks: "Slik fungerer det:",
    step1: "Du oppretter en personlig rabattkode",
    step2: "Venner fÃ¥r 20% rabatt pÃ¥ forskuddet nÃ¥r de bruker din kode",
    step3: "Du fÃ¥r 10% kreditt av deres kjÃ¸p som kan brukes pÃ¥ ditt restbelÃ¸p",
    step4: "Maks 5 venner per bestilling kan gi deg kreditt",
    chooseCode: "Velg din unike kode (4-20 tegn, kun bokstaver og tall)",
    exampleCode: "f.eks. KENNETH2026",
    creating: "Oppretter...",
    createButton: "Opprett kode",
    yourCode: "Din vennerabattkode",
    shareCode: "Del denne koden med venner og familie",
    code: "Din kode:",
    copied: "Kopiert!",
    copyCode: "Kopier kode",
    shareButton: "Del kode",
    friendsGet20: "Venner fÃ¥r 20% rabatt pÃ¥ forskuddet â€¢ Du fÃ¥r 10% kreditt per henvisning",
    totalReferrals: "Totale henvisninger",
    availableCredit: "Tilgjengelig kreditt",
    creditRemaining: "Kredittering igjen",
    of: "av",
    unusedBonuses: "Du har {count} ubrukte bonuser!",
    moreReferrals: "Du har henvist flere venner enn du kan fÃ¥ kreditt for med din nÃ¥vÃ¦rende bestilling...",
    orderNew: "Bestill ny kasse",
    yourReferrals: "Dine henvisninger",
    used: "Brukt",
    available: "Tilgjengelig",

    // Input
    haveCode: "Har du en vennerabattkode?",
    haveRebateCode: "Har du en rabattkode?",
    enterCode: "Skriv inn kode",
    checking: "Sjekker...",
    useCode: "Bruk kode",
    newCustomersGet20: "Nye kunder fÃ¥r 20% rabatt pÃ¥ forskuddet ved bruk av vennerabattkode",
    codeActivated: "Kode aktivert: {code}",
    youGet20Off: "Du fÃ¥r 20% rabatt pÃ¥ forskuddet ({amount} kr)",
    youSave: "Du sparer {amount} kr",
    remove: "Fjern",
    invalidCode: "Ugyldig kode",
    pleaseEnterCode: "Vennligst skriv inn en kode",
    couldNotValidate: "Kunne ikke validere koden",
    couldNotCreate: "Kunne ikke opprette kode",

    // Share message
    shareMessage: "Bestill ullgris fra Tinglum GÃ¥rd og fÃ¥ 20% rabatt pÃ¥ forskuddet med min vennerabattkode: {code}",
  },

  // Admin
  admin: {
    title: "TinglumgÃ¥rd - Admin",
    login: "Admin Login",
    password: "Passord",
    wrongPassword: "Feil passord. PrÃ¸v igjen.",
    loginButton: "Logg inn",
    logout: "Logg ut",
    dashboard: "Dashboard",
    refresh: "Oppdater",
    noData: "Ingen data tilgjengelig",

    // Tabs
    overview: "Oversikt",
    orders: "Bestillinger",
    boxConfig: "Boksinnhold",
    rebateCodes: "Rabattkoder",
    extras: "Ekstraprodukter",
    notifications: "Varsler",
    analytics: "Analyse",
    emails: "E-poster",

    // Order management
    searchOrders: "SÃ¸k etter ordre, navn eller e-post...",
    filter: "Filtrer",
    exportCSV: "Eksporter CSV",
    ordersSelected: "{count} ordre(r) valgt",
    markReady: "Marker klar",
    lock: "LÃ¥s",
    productionPlan: "Produksjonsplan",
    noOrdersFound: "Ingen bestillinger funnet",
    adjustFilters: "PrÃ¸v Ã¥ justere filtrene dine",

    // Table headers
    select: "Velg",
    orderNo: "Ordre",
    customer: "Kunde",
    box: "Boks",
    status: "Status",
    payment: "Betaling",
    actions: "Handlinger",

    // Status options
    pending: "Venter",
    depositPaid: "Forskudd betalt",
    paid: "Betalt",
    locked: "LÃ¥st",
    ready: "Klar",
    delivered: "Levert",

    // Actions
    changeStatusTo: "Endre status til '{status}' for {count} ordrer?",
    lockOrders: "LÃ¥se {count} ordrer? Dette kan ikke angres.",
    ordersUpdated: "{count} ordrer oppdatert",
    ordersLocked: "{count} ordrer lÃ¥st",
    couldNotUpdate: "Kunne ikke oppdatere ordrer",
    couldNotLock: "Kunne ikke lÃ¥se ordrer",
    couldNotExport: "Kunne ikke eksportere CSV",
    selectOrders: "Velg ordrer Ã¥ eksportere",
    couldNotExportPlan: "Kunne ikke eksportere produksjonsplan",
    couldNotUpdateStatus: "Kunne ikke oppdatere status",
    couldNotSaveNotes: "Kunne ikke lagre notater",
    noOrdersSelected: "Ingen ordrer valgt",

    // Analytics
    keyMetrics: "NÃ¸kkeltall",
    totalOrders: "Totale bestillinger",
    uniqueCustomers: "Unike kunder",
    repeatCustomers: "Gjentakende kunder",
    repeatRate: "Gjentakelsesrate",
    conversionFunnel: "Konverteringstrakt",
    popularCombos: "PopulÃ¦re produktkombinasjoner",
    loadingAnalytics: "Laster analysedata...",

    // Email
    sendEmail: "Send e-post",
    history: "Historikk",
  },

  // Footer
  footer: {
    farm: "Tinglum GÃ¥rd",
    location: "Namdalseid, TrÃ¸ndelag",
    quality: "Kvalitet fra Namdalseid",
    description: "Vi leverer norsk griskjÃ¸tt av hÃ¸yeste kvalitet, oppvokst pÃ¥ gÃ¥rden og behandlet med omtanke fra start til slutt.",
    localRaised: "Lokalt oppvokst",
    seasonBased: "Sesongbasert",
    organic: "Ullgris, ute pÃ¥ beite, rÃ¥varer fra Ã¸kologisk produksjon i fÃ´ringen",
    links: "Lenker",
    productInfo: "Produktinformasjon",
    myOrders: "Min side",
    myPage: "Min side",
    admin: "Admin",
    contact: "Kontakt",
    legal: "VilkÃ¥r og personvern",
    allRightsReserved: "Alle rettigheter reservert.",
    rights: "Alle rettigheter reservert",
    norwegianQuality: "Norsk kvalitet",
    season2026: "Sesong 2026",
    season: "Sesong 2026",
  },

  // Contact
  contact: {
    contactUs: "Kontakt oss",
    regardingOrder: "AngÃ¥ende ordre {orderNumber}",
    otherWays: "Andre mÃ¥ter Ã¥ kontakte oss pÃ¥:",
    email: "E-post: post@tinglum.no",
    phone: "Telefon: +47 123 45 678",
    yourMessage: "Din melding",
    messagePlaceholder: "f.eks:\n- SpÃ¸rsmÃ¥l om leveringstidspunkt\n- Endre leveringsadresse\n- SpÃ¸rsmÃ¥l om produktene",
    responseTime: "Vi svarer vanligvis innen 24 timer",
    orderDetails: "Ordredetaljer:",
    sending: "Sender...",
    sendMessage: "Send melding",
    messageSent: "Meldingen din er sendt! Vi kontakter deg snart.",
    couldNotSend: "Kunne ikke sende melding. PrÃ¸v igjen senere.",
    pleaseWriteMessage: "Vennligst skriv en melding",
  },

  // Box contents (fixed items in every box)
  boxContents: {
    ribbe8kg: "ca. 2.0 kg ribbe",
    ribbe12kg: "ca. 3.0 kg ribbe",
    nakkekoteletter8kg: "ca. 0.75 kg nakkekoteletter",
    nakkekoteletter12kg: "ca. 1.0 kg nakkekoteletter",
    julepolse8kg: "ca. 0.5 kg julepolse",
    julepolse12kg: "ca. 1.0 kg julepolse",
    svinesteik8kg: "ca. 1.0 kg svinesteik",
    svinesteik12kg: "ca. 1.0 kg svinesteik",
    medisterfarse8kg: "ca. 1.0 kg medisterfarse",
    medisterfarse12kg: "ca. 1.5 kg medisterfarse",
    knoke: "1 knoke",
    butchersChoice8kg: "+ Slakterens valg (ca. 2-3 kg)",
    butchersChoice12kg: "+ Slakterens valg (ca. 3.5-4.5 kg)",
  },

  // Product list items (shown in boxes)
  products: {
    ribbe: "Ribbe",
    nakkekoteletter: "Nakkekoteletter",
    julepolse: "julepolse",
    svinesteik: "Svinesteik",
    medisterfarse: "Medisterfarse",
    knoke: "Knoke",
    butchersChoice: "Slakterens valg",
  },

  // Cuts page
  cuts: {
    title: "Oppdelingsplan",
    hover: "Hold over et kutt for info",
    inBox: "I kassen",
    extraOrder: "Ekstra",
    shoulder: "Bog",
    loin: "Kam",
    belly: "Mage/Ribbe",
    leg: "LÃ¥r",
  },

  // Messaging/Admin
  messaging: {
    sendMessage: "Send melding",
    chooseRecipients: "Velg mottakere og send en melding til deres innboks.",
    allClients: "Alle klienter",
    selectClients: "Velg klienter",
    filters: "Filtre",
    subject: "Emne",
    category: "Kategori",
    support: "StÃ¸tte",
    inquiry: "SpÃ¸rsmÃ¥l",
    complaint: "Klage",
    message: "Melding",
    writeAnnouncement: "Skriv din kunngjÃ¸ring...",
    awaitingFinalPayment: "Venter pÃ¥ sluttbetaling",
    boxSize: "BokssstÃ¸rrelse",
    all: "Alle",
    hasExtras: "Har tillegg",
    extrasFilter: "Filter for tillegg",
    previewRecipients: "ForhÃ¥ndsvis mottakere",
    exclude: "Ekskluder",
    clearAll: "Fjern alt",
    send: "Send",
    sendingBroadcast: "Sender...",
    broadcastSent: "Melding sendt til alle mottakere!",
    replies: "Svar",
    replyPlaceholder: "Skriv ditt svar her...",
    sendReply: "Send svar",
    open: "Ã…pen",
    inProgress: "PÃ¥gÃ¥r",
    resolved: "LÃ¸st",
    closed: "Lukket",
    status: "Status",
    priority: "Prioritet",
    low: "Lav",
    normal: "Normal",
    high: "HÃ¸y",
    urgent: "Haster",
    noMessages: "Ingen meldinger",
  },
  // Countdown timer
  countdownTimer: {
    defaultLabel: "Levering i uke 48",
    expired: "Leveringstid!",
    days: "Dager",
    hours: "Timer",
    minutes: "Min",
    seconds: "Sek",
  },

  // Extra products selector
  extraProductsSelector: {
    quantity: "Antall",
    unitPieces: "stk",
    importantInfo: "Viktig informasjon om ekstra produkter",
    warning:
      "Ekstra produkter kan ikke garanteres, og tilgangen er meget begrenset. Ved a betale restbelopet/ferdigstille ordren sikrer du din plass i koen. Vi oppfyller bestillingene etter nar restordre/ekstra bestillinger blir betalt.",
    onlyLeft: "Bare {count} igjen",
    totalExtras: "Totalt ekstra produkter",
  },

  // Extra product card
  extraProductCard: {
    soldOut: "Utsolgt",
    onlyLeft: "Bare {count} igjen",
    unitPieces: "stk",
  },

  // Instagram feed
  instagramFeed: {
    badge: "Folg oss pa Instagram",
    title: "Se hverdagen pa garden",
    description: "Folg med pa grisene som vokser opp, livet pa garden og oppdateringer gjennom sesongen",
    fallback: "Kunne ikke laste Instagram-innlegg. Besok oss pa Instagram:",
  },

  // Product card
  productCard: {
    waitlistTitle: "Skriv deg pa venteliste",
    waitlistDescription: "Vi varsler deg nar vi har mer pa lager.",
    waitlistSuccess: "Takk! Du er na pa ventelisten.",
    emailLabel: "E-post *",
    emailPlaceholder: "din@epost.no",
    nameLabel: "Navn (valgfritt)",
    namePlaceholder: "Ditt navn",
    submitWaitlist: "Meld meg pa",
    sending: "Sender...",
  },

  // Product page
  productPage: {
    productLabel: "Produkt",
    packageContents: "Innhold i pakken",
    ribbeItem: "2-3 kg ribbe, vakuumpakket",
    sausageItem: "1 kg polser, frosset",
    baconItem: "500 g bacon, skiver",
    chopsItem: "1.5 kg nakkekoteletter",
    stewItem: "1-2 kg kokkekutt",
  },

  // Cuts page
  cutsPage: {
    diagramLead: "Se hvor kuttene sitter, og hva som normalt ligger i kassen versus hva som kan bestilles ekstra.",
    howToUse: "Hvordan bruke dette",
    howToUse1: "Trykk pa et omrade for a se navn og bruksomrade.",
    howToUse2: 'Bytt mellom "I kassen" og "Ekstra" i diagrammet dersom stottet av komponenten.',
    howToUse3: "Se produktsiden for innhold og struktur.",
    terminology: "Terminologi",
  },

  // Confirmation page
  confirmationPage: {
    orderNotFoundTitle: "Ordre ikke funnet",
    orderNotFoundDescription: "Vi kunne ikke finne ordren din.",
    backHome: "Tilbake til forsiden",
    paymentReceived: "Betaling mottatt!",
    paymentFailed: "Betaling feilet",
    paymentWaiting: "Venter pa betalingsbekreftelse...",
    orderNumberLabel: "Ordrenummer",
    detailsTitle: "Ordredetaljer",
    boxSizeLabel: "Kassestorrelse",
    depositLabel: "Forskudd",
    statusLabel: "Status",
    nextStepsTitle: "Neste steg",
    statusDraft: "Venter pa forskudd",
    statusDepositPaid: "Forskudd betalt - venter pa rest",
    statusPaid: "Fullstendig betalt",
    statusReadyForPickup: "Klar for henting",
    statusCompleted: "Fullfort",
    statusCancelled: "Kansellert",
    statusUnknown: "Ukjent status",
    pendingTitle: "Venter pa betalingsbekreftelse",
    pendingBody: "Vi har ikke mottatt bekreftelse pa at forskuddsbetalingen pa {amount} kr er fullfort.",
    pendingReasonsTitle: "Dette kan bety:",
    pendingReason1: "Betalingen er under behandling (vanligvis tar dette noen sekunder)",
    pendingReason2: "Du avbrot betalingen i Vipps",
    pendingReason3: "Banken din blokkerte transaksjonen",
    pendingFooter:
      "Siden oppdateres automatisk nar vi mottar bekreftelse. Hvis betalingen ikke gar gjennom innen fa minutter, sjekk Vipps-appen din eller kontakt oss.",
    failedBannerTitle: "Betaling feilet",
    failedBannerBody: "Forskuddsbetalingen pa {amount} kr kunne ikke gjennomfores.",
    failedBannerHelp: "Vennligst prov igjen eller kontakt oss for hjelp.",
    syncingTitle: "Oppdaterer ordrestatus...",
    syncingBody: "Betalingen er mottatt, oppdaterer ordredetaljene...",
    depositConfirmedTitle: "Forskudd bekreftet!",
    depositConfirmedBody:
      "Vi har mottatt forskudd. Du vil motta en paminnelse om restbetaling ca. 2 uker for henting.",
    fullyPaidTitle: "Fullstendig betalt!",
    fullyPaidBody: "Takk for full betaling. Din bestilling vil bli klargjort for henting.",
    step1DoneTitle: "Forskudd betalt",
    step1TodoTitle: "Betal forskudd",
    step1DoneBody: "Forskudd mottatt. Du har mottatt en e-postbekreftelse.",
    step1TodoBody: "Betal forskudd pa {amount} kr via Vipps.",
    step2Title: "Del vennerabatt",
    step2Body: "Gi {give}% rabatt til venner og fa {earn}% kreditt selv. Finn din kode pa Min side.",
    myPage: "Min side",
    step3Title: "Grisene vokser opp",
    step3Body: "Grisene lever pa garden gjennom {year} og blir slaktet lokalt i desember.",
    step4Title: "Betaling av rest og levering",
    step4Body: "Restbelopet betales ved levering i desember {year}.",
    myOrders: "Se mine ordrer",
  },

  // Order status timeline
  orderStatusTimeline: {
    created: "Bestilling opprettet",
    deposit: "Forskudd betalt",
    remainder: "Fullstendig betalt",
    locked: "Ordre last",
    ready: "Klar for henting",
    completed: "Fullfort",
  },

  // Order timeline modal
  orderTimelineModal: {
    title: "Ordrehistorikk",
    orderPrefix: "Ordre",
    close: "Lukk",
    orderCreated: "Ordre opprettet",
    orderCreatedDesc: "Ordre {orderNumber} ble opprettet",
    depositPaid: "Forskudd betalt",
    depositPending: "Forskudd venter",
    orderModified: "Ordre endret",
    orderModifiedDesc: "Bestillingen ble oppdatert",
    orderLocked: "Ordre last",
    orderLockedDesc: "Bestillingen kan ikke lenger endres",
    remainderPaid: "Restbelop betalt",
    remainderPending: "Restbelop venter",
    inProduction: "I produksjon",
    inProductionDesc: "Bestillingen blir forberedt",
    readyForPickup: "Klar for henting",
    readyForPickupDesc: "Bestillingen er klar",
    delivered: "Levert",
    deliveredDesc: "Bestillingen er fullfort",
    paymentDeadlinePassed: "Betalingsfrist passert",
    paymentDeadlinePassedDesc: "Vennligst betal restbelopet sa snart som mulig",
  },

  // Payment history modal
  paymentHistoryModal: {
    title: "Betalingshistorikk",
    orderPrefix: "Ordre",
    totalPaid: "Totalt betalt",
    extrasTitle: "Ekstra produkter (inkludert i restbelop)",
    extrasTotal: "Totalt ekstra",
    noPayments: "Ingen betalinger registrert",
    notPaid: "Ikke betalt",
    transactionId: "Transaksjons-ID",
    close: "Lukk",
    receipt: "Kvittering",
    receiptDesc: "Kvittering vil bli sendt til din e-post",
    downloadReceipt: "Last ned kvittering",
    paymentTypeDeposit: "Forskudd",
    paymentTypeRemainder: "Restbelop",
    statusCompleted: "Betalt",
    statusPending: "Venter",
    statusFailed: "Feilet",
  },

  // Extras upsell modal
  extrasUpsellModal: {
    removeWarning:
      "Du fjerner: {items}.\n\nProduksjonen er stram etter fristdato. Du vil IKKE kunne legge disse tilbake. Er du sikker?",
    noChanges: "Ingen endringer",
    title: "Legg til ekstra produkter",
    subtitle: "Ok din bestilling for du betaler restbelopet. Alle priser legges til restbelopet.",
    noExtrasAvailable: "Ingen ekstra produkter tilgjengelig for oyeblikket",
    quantity: "Antall",
    unitPieces: "stk",
    selectedExtras: "Ekstra produkter valgt:",
    change: "Endring",
    addedToRemainder: "Dette belopet legges til restbelopet ditt",
    cancel: "Avbryt",
    updating: "Oppdaterer...",
    saving: "Lagrer...",
    updateExtrasOrder: "Oppdater ekstra bestilling ({delta})",
  },

  // Order modification modal
  orderModificationModal: {
    title: "Endre bestilling",
    boxSize: "Boksstorrelse",
    priceFromAdmin: "Pris fra admin-innstillinger",
    ribChoice: "Ribbevalg",
    deliveryMethod: "Hentemate",
    pickupFarm: "Henting pa garden",
    pickupFarmFee: "Ingen ekstra kostnad",
    pickupE6: "Henting langs E6",
    pickupE6Note: "Hentedag avtales",
    trondheimPickup: "Henting i Trondheim",
    trondheimNote: "Hentedag den uken",
    deliveryType: "Type levering",
    frozenPickup: "Frossen henting",
    frozenStandard: "Standard henting",
    freshPickup: "Fersk henting",
    freshPickupNote: "Henting pa garden uke 50/51",
    freshOnlyFarm: "Kun tilgjengelig ved henting pa garden",
    extrasTitle: "Legg til ekstra produkter (valgfritt)",
    extrasWarning:
      'Du har endret ekstra produkter. Endringene vil bli lagret nar du klikker "Lagre endringer".',
    cancel: "Avbryt",
    saveChanges: "Lagre endringer",
    saving: "Lagrer...",
    noChanges: "Ingen endringer gjort",
    confirmChanges: "Bekreft endringer",
    confirmDescription: "Er du sikker pa at du vil endre ordren? Dette kan pavirke prisen.",
    confirm: "Bekreft",
    saveSuccessTitle: "Endringer lagret",
    saveSuccessDescription: "Ordren din har blitt oppdatert",
    saveErrorTitle: "Feil",
    saveErrorDescription: "Kunne ikke lagre endringer. Prov igjen.",
    extrasError: "Kunne ikke oppdatere ekstra produkter",
    quantity: "Antall",
    unitPieces: "stk",
    ribOptionTynnribbe: "Tynnribbe",
    ribOptionFamilieribbe: "Familieribbe",
    ribOptionPorchetta: "Porchetta",
    ribOptionButchersChoice: "Slakterens valg",
  },

  // Customer messaging panel
  customerMessagingPanel: {
    loadError: "Kunne ikke laste meldinger",
    emptyReplyTitle: "Tom melding",
    emptyReplyDescription: "Svar kan ikke vaere tomt",
    replySentTitle: "Svar sendt",
    replySentDescription: "Svaret ditt har blitt sendt",
    errorTitle: "Feil",
    sendReplyFailed: "Kunne ikke sende svar",
    missingInfoTitle: "Manglende informasjon",
    missingInfoDescription: "Emne og melding maa fylles ut",
    messageSentTitle: "Melding sendt",
    messageSentDescription: "Din melding har blitt sendt til administratoren",
    sendFailedTitle: "Feil ved sending",
    sendFailedDescription: "Kunne ikke sende melding",
    panelTitle: "Send oss en melding",
    category: "Kategori",
    subject: "Emne",
    message: "Melding",
    subjectPlaceholder: "f.eks. Sporsmaal om ordre #12345",
    messagePlaceholder: "Hva kan vi hjelpe deg med?",
    successMessage: "Meldingen er sendt!",
    sending: "Sender...",
    sendMessage: "Send melding",
    yourMessages: "Dine meldinger",
    loadingMessages: "Laster meldinger...",
    noMessages: "Ingen meldinger ennaa",
    fromYou: "Du",
    fromFarm: "Svar fra Tinglum Gard",
    replyPlaceholder: "Skriv et svar...",
    categorySupport: "Support",
    categoryInquiry: "Sporsmaal",
    categoryComplaint: "Klage",
    categoryFeedback: "Tilbakemelding",
    categoryReferralQuestion: "Vennerabatt",
    statusOpen: "Apen",
    statusInProgress: "Under behandling",
    statusResolved: "Lost",
    statusClosed: "Lukket",
  },

  // Order details card
  orderDetailsCard: {
    nextActionCompleted: "Ordren er fullfort",
    nextActionReady: "Klar for henting - se detaljer nedenfor",
    nextActionPaymentDue: "Restbetaling pa {currency} {amount} ma betales",
    nextActionLocked: "Ordre last - venter pa restbetaling",
    nextActionWaitingDeposit: "Venter pa forskuddsbetaling",
    nextActionProcessing: "Alt er i orden - vi holder deg oppdatert",
    deliveryTypePickupFarm: "Henting pa gard",
    deliveryTypePickupE6: "Henting ved E6",
    deliveryTypePickupTrondheim: "Henting i Trondheim",
    ribChoiceTynnribbe: "Tynnribbe",
    ribChoiceFamilieribbe: "Familieribbe",
    ribChoicePorchetta: "Porchetta",
    ribChoiceButchersChoice: "Slakterens valg",
    updateError: "Kunne ikke oppdatere ekstra produkter",
    updatedTitle: "Oppdatert",
    updatedExtras: "Oppdatert ekstra produkter ({count}).",
    errorTitle: "Feil",
    addExtrasError: "Kunne ikke legge til ekstra produkter. Prov igjen.",
    saveModificationsError: "Kunne ikke lagre endringer",
    reorderConfirm: "Onsker du a bestille samme boks pa nytt?",
    reorderFailed: "Kunne ikke opprette ny ordre. Prov igjen.",
    reorderCreatedTitle: "Ny ordre opprettet",
    reorderCreatedDescription: "Ordrenummer: {orderNumber}",
    estimatedReadyNow: "Klar na!",
    estimatedWeekRange: "Uke 47-48, 2026",
    payRemainder: "Betal restbelop",
    dueDate: "Forfallsdato",
    earlyPaymentHint:
      "Jo tidligere du betaler restbelopet, jo storre er sjansen for ekstra produkter.",
    statusPaymentRemaining: "Betaling gjenstar",
    statusPaid: "Betalt",
    statusDelivered: "Levert",
    statusCompleted: "Fullfort",
    statusWaitingDeposit: "Venter pa forskudd",
    locked: "Last",
    ordered: "Bestilt",
    downloadReceipt: "Last ned kvittering",
    print: "Skriv ut",
    paymentSummary: "Betalingsoversikt",
    depositBoxLabel: "Forskudd ({size}kg boks)",
    boxRemainder: "Restbelop kasse",
    extraProducts: "Ekstra produkter",
    remainderTotal: "Restbetaling totalt",
    remainderDueDate: "Forfallsdato restbetaling",
    total: "Totalt",
    orderContents: "Bestillingsinnhold",
    porkBoxLabel: "{size}kg Griskasse",
    ribChoice: "Ribbe",
    freshDeliveryAddon: "Fersk levering (+{currency} 200)",
    addExtraProducts: "Legg til ekstra produkter",
    deliveryInfo: "Hente-/leveringsinformasjon",
    type: "Type",
    farmName: "Tinglum Gard",
    addressByEmail: "Adresse kommer i e-post nar ordren er klar",
    whatToBring: "Hva du ma ta med:",
    bringCooler: "Kjolebag eller kjoleboks",
    yourNotes: "Dine notater:",
    orderActions: "Ordre-handlinger",
    paymentHistory: "Betalingshistorikk",
    orderHistory: "Ordrehistorikk",
    contactUs: "Kontakt oss",
    estimatedDeliveryDate: "Estimert leveringsdato",
    notifyReady: "Vi sender varsel nar ordren er klar for henting",
    canStillEdit: "Du kan fortsatt endre bestillingen din",
    changesBeforeLock: "Endringer ma gjores for lasetidspunktet",
    editOrder: "Endre bestilling",
    orderLocked: "Bestillingen er last",
    noMoreChanges: "- ingen flere endringer mulig",
    happyWithOrder: "Fornoyd med ordren?",
    creatingOrder: "Oppretter ordre...",
    orderAgain: "Bestill igjen",
    reorderSameContents: "Opprett en ny ordre med samme innhold",
    contactDetailsBoxSize: "Boksstorrelse",
    contactDetailsRibChoice: "Ribbevalg",
    contactDetailsDeliveryType: "Leveringstype",
    contactDetailsStatus: "Status",
    contactDetailsTotalAmount: "Totalbelop",
    contactEmail: "post@tinglum.no",
    contactPhone: "+47 123 45 678",
  },

  // Remainder payment page
  remainderPaymentPage: {
    fetchOrderError: "Kunne ikke hente ordre",
    unknownError: "Ukjent feil",
    backToMyPage: "Tilbake til Min side",
    updatedTitle: "Oppdatert",
    soldOutRemovedWithCredit: "Utsolgte produkter fjernet og kreditt lagt til.",
    soldOutRemoved: "Utsolgte produkter fjernet fra bestillingen.",
    couldNotUpdate: "Kunne ikke oppdatere",
    tryAgain: "Prov igjen.",
    missingOrderId: "Mangler ordre-ID",
    updateExtrasError: "Kunne ikke oppdatere ekstra produkter",
    updateDeliveryError: "Kunne ikke oppdatere leveringsdetaljer",
    changesSaved: "Endringer lagret",
    startingPayment: "Starter betaling...",
    startPaymentError: "Kunne ikke starte betaling (status {status})",
    paymentErrorTitle: "Betalingsfeil",
    paymentErrorDescription: "Kunne ikke starte betaling. Prov igjen.",
    soldOutTitle: "Beklager, noen ekstra varer er utsolgt",
    soldOutBody:
      "Vi har ikke nok lager til alle ekstra varer du valgte ved forskuddsbestilling. Du kan fjerne varene eller fa 110% kreditt som kan brukes pa andre ekstra produkter. Ubrukt kreditt refunderes ikke.",
    ordered: "Bestilt",
    available: "Tilgjengelig",
    removeSoldOut: "Fjern utsolgte produkter",
    takeCredit110: "Ta 110% kreditt",
    payRemainderTitle: "Betal restbelop",
    orderLabel: "Ordre",
    dueDate: "Forfallsdato",
    earlyPaymentHint:
      "Jo tidligere du betaler restbelopet, jo storre er sjansen for a fa ekstra produkter.",
    back: "Tilbake",
    extrasTitle: "Ekstra produkter (valgfritt)",
    extrasSubtitle:
      "Legg til ekstra produkter for du betaler. Prisen legges til restbelopet.",
    quantity: "Antall",
    unitPieces: "stk",
    unitKg: "kg",
    youAdd: "Du legger til",
    youReduce: "Du reduserer bestillingen med",
    toOriginalOrder: "til den opprinnelige bestillingen",
    unsavedChangesWarning:
      'Du har endringer som ikke er lagret. De vil bli lagret nar du klikker "Betal med Vipps".',
    soldOutCreditTitle: "Kreditt for utsolgte produkter",
    soldOutCreditNote:
      "Kreditten kan brukes pa ekstra produkter og refunderes ikke.",
    pickupDeliveryTitle: "Henting og levering",
    deliveryMethod: "Leveringsmetode",
    pickupFarm: "Henting pa garden",
    pickupFarmLocation: "Tinglum Gard, Sjofossen",
    free: "Gratis",
    pickupE6: "Henting ved E6",
    pickupE6Point: "Hentested ved E6",
    deliveryTrondheim: "Levering i Trondheim",
    deliveryAddress: "Levering til din adresse",
    extraOption: "Ekstra alternativ",
    freshDelivery: "Fersk levering",
    freshDeliveryDescription: "Produktene leveres ferske (ikke frosset)",
    forDeliveryChange: "for leveringsendring",
    saveOnDeliveryChange: "pa leveringsendring",
    deliveryChangesWarning:
      'Du har endret leveringsdetaljene. De vil bli lagret nar du klikker "Betal med Vipps".',
    paymentSummary: "Betalingsoversikt",
    depositPaid: "Forskudd (betalt)",
    boxRemainder: "Restbelop kasse",
    extraProducts: "Ekstra produkter",
    extraProductsCredit: "Kreditt ekstra produkter",
    deliveryChange: "Leveringsendring",
    payNow: "A betale na",
    savingExtras: "Lagrer ekstra produkter...",
    payWithVipps: "Betal {currency} {amount} med Vipps",
  },
};


