export const no = {
  // Navigation & Common
  nav: {
    products: "Kasser",
    cuts: "Kutt",
    myOrders: "Min side",
    admin: "Admin",
    oppdelingsplan: "Oppdelingsplan",
    minebestillinger: "Mine bestillinger",
    logout: "Logg ut",
    login: "Logg inn",
    order: "Bestill",
    back: "Tilbake",
    backToHome: "Tilbake til forsiden",
  },

  // Common words/actions
  common: {
    close: "Lukk",
    save: "Lagre",
    cancel: "Avbryt",
    loading: "Laster...",
    error: "Noe gikk galt",
    confirm: "Bekreft",
    edit: "Endre",
    delete: "Slett",
    add: "Legg til",
    remove: "Fjern",
    continue: "Fortsett",
    processing: "Behandler...",
    free: "Gratis",
    total: "Totalt",
    kr: "kr",
    kg: "kg",
    stk: "stk",
    week: "uke",
    year: "Ã¥r",
    currency: "kr",
  },

  // Hero section
  hero: {
    season: "Sesong 2026",
    seasonOnce: "Kun Ã©n sesong i Ã¥ret",
    porkFrom: "Ullgris fra",
    headline: "Ullgris fra",
    farmName: "Tinglum GÃ¥rd",
    subtitle: "Gris fra Tinglum GÃ¥rd i Namdalseid. Grisene vokser opp pÃ¥ gÃ¥rden gjennom 2026, slaktes lokalt i nov/des, og hentes fersk eller frossen.",
    cta: "Reserver nÃ¥",
    reserveNow: "Reserver nÃ¥",
    learnMore: "Les mer om produktet",
    joinWaitlist: "Bli med pÃ¥ venteliste",
    qualityHeadline: "Norsk kvalitet",
    tagline: "Vakuumpakket, fryseklart, levert uke 48.",
    reserveBeforeLate: "Reserver din pakke før det er for sent",
    description: "Gris fra Tinglum GÃ¥rd i Namdalseid. Grisene vokser opp pÃ¥ gÃ¥rden gjennom 2026, slaktes lokalt i nov/des, og hentes fersk eller frossen.",
    localRaised: "Lokalt oppvokst",
    qualityGuarantee: "Kvalitetsgaranti",
    limitedOffer: "Begrenset tilbud",
    limitedProduction: "Vi produserer kun det vi har kapasitet til. NÃ¥r sesongens kasser er reservert, stenger vi bestillingen til 2027.",
    reservePackageNow: "Reserver din kasse nÃ¥",
  },

  // Product/Box selection
  product: {
    chooseYourBox: "Velg din kasse",
    choosePackage: "Velg din kasse",
    twoSizes: "To størrelser Ã¥ velge mellom",
    sameQuality: "Samme høye kvalitet uansett størrelse. Velg kassen som passer best for din husholdning.",
    smallBox: "Mindre kasse",
    smallerPackage: "Mindre kasse",
    largeBox: "Større kasse",
    largerPackage: "Større kasse",
    mostPopular: "Mest populÃ¦r",
    betterPricePerKg: "Bedre pris per kg",
    perfectFor2to3: "Perfekt for 2-3 personer eller mindre forbruk",
    idealFor4to6: "Ideell for 4-6 personer eller større forbruk",
    inEach8kgBox: "I hver 8 kg kasse:",
    inEach8kg: "I hver 8 kg kasse",
    inEach12kgBox: "I hver 12 kg kasse:",
    inEach12kg: "I hver 12 kg kasse",
    reserve8kg: "Reserver 8 kg kasse",
    reserve12kg: "Reserver 12 kg kasse",
    boxesLeft: "bokser igjen",
    lowStock: "FÃ¥ igjen",
    soldOut: "Utsolgt",
    priceDeposit: "Betales nÃ¥",
    priceRemainder: "Rest ved levering",
    deposit50: "Forskudd (50%)",
    remainderAtDelivery: "Rest ved levering",
    balanceOnDelivery: "Rest ved levering",
    totalPrice: "Totalpris",
    seeDetails: "Se innhold",
    kg: "kg",
    orderNow: "Reserver nÃ¥",
    joinWaitlist: "Bli med pÃ¥ venteliste",
    box8: "8 kg kasse",
    box12: "12 kg kasse",
  },

  // Product detail page
  productDetail: {
    title: "Ullgris Kjøttpakke",
    variation: "Innholdet varierer med tilgjengelighet, men dette er alltid med:",
    categories: {
      ribbe: "Ribbe",
      sausages: "Pølser",
      bacon: "Bacon",
      chops: "Koteletter",
      stew: "Skinkesteik",
    },
    addons: {
      title: "Tillegg",
      disabled: "Tillegg kan velges i bestillingsprosessen",
      delivery: "Henting Trondheim",
      highway: "Henting langs E6",
      fresh: "Fersk levering (uke 50-51)",
    },
  },

  // Availability section
  availability: {
    title: "Tilgjengelighet",
    boxesAvailable: "Kasser tilgjengelig",
    remainingBoxes: "FÃ¥ igjen",
    fewLeft: "FÃ¥ igjen",
    soldOut: "Utsolgt",
    soldOutComplete: "Utsolgt",
    reserveBeforeTooLate: "Reserver før det er for sent",
    reserveBeforeLate: "Reserver før det er for sent",
    seasonProductionComplete: "Sesongproduksjon fullført",
    seasonComplete: "Sesongproduksjon fullført",
  },

  // Timeline/How it works
  timeline: {
    title: "Slik fungerer det",
    subtitle: "Fra bestilling til levering",
    tagline: "Grisene vokser gjennom 2026 â€¢ Fersk levering i desember",
    reserveNow: "Reserver din pakke nÃ¥",
    howItWorks: "Slik fungerer det",
    fromOrderToDelivery: "Fra bestilling til levering",
    step1Title: "Reserver din pakke nÃ¥",
    step1Desc: "Betal forskudd (50%) med Vipps. Din plass er sikret nÃ¥r betalingen er gjennomført.",
    step1Time: "Uke 45",
    step2Title: "Restsum betales",
    step2Desc: "Innen uke 46 betaler du resterende 50% av totalbeløpet. Du fÃ¥r betalingsinformasjon pÃ¥ e-post.",
    step2Time: "Uke 46-47",
    step3Title: "Slakting og frossen levering",
    step3Desc: "Grisene slaktes profesjonelt og pakkes fersk. Deretter fryses alt ned for optimal holdbarhet og leveres i uke 48-49.",
    step3Time: "Uke 48-49",
    step4Title: "Fersk levering (tilvalg)",
    step4Desc: "Mot et lite tillegg kan du velge fersk levering i uke 50-51. Perfekt hvis du ønsker kjøttet helt ferskt!",
    step4Time: "Uke 50-51",
    optional: "Valgfritt",
    week44: "Uke 45: Betaling fullføres",
    week46: "Uke 47: Siste frist for endringer",
    week48: "Uke 49: Levering og utlevering",
    week44Desc: "Du fÃ¥r beskjed og fullfører betaling før levering.",
    week46Desc: "Endre størrelse og tillegg frem til fristen, etterpÃ¥ lÃ¥ses bestillingen.",
    week48Desc: "Henting eller levering etter valgt alternativ.",
  },

  // FAQ
  faq: {
    title: "SpørsmÃ¥l og svar",
    badge: "OSS",
    commonQuestions: "Vanlige spørsmÃ¥l",
    q1: "Hva fÃ¥r jeg i kassen?",
    a1: "Fast struktur, smÃ¥ variasjoner er normalt. Du fÃ¥r ribbe, bacon, pølser, nakkekoteletter og skinkesteik. I tillegg legger vi med gode biter avhengig av tilgjengelighet. Alt er porsjonert, merket og vakuumpakket.",
    q2: "NÃ¥r fÃ¥r jeg leveringen?",
    a2: "Frossen kasse leveres i uke 48. Fersk kasse kan velges mot tillegg og leveres i slutten av uke 50 eller starten av uke 51.",
    q3: "Kan jeg endre bestillingen?",
    a3: "Ja, frem til uke 46. Etter fristen lÃ¥ses bestillingen slik at vi kan planlegge produksjon og pakking.",
    q4: "Hvordan henter jeg eller fÃ¥r levert?",
    a4: "Du kan velge levering langs E6 mellom Stjørdal og Namsos, eller i Trondheim sentrum. Pris vises i kassen før du bekrefter.",
  },

  // Checkout/Order page
  checkout: {
    title: "Bestill",
    pageTitle: "Reserver din kasse",
    subtitle: "Reserver din kasse med Vipps",
    selectSize: "Velg størrelse, ribbe-type og ekstra tillegg. Du betaler med VIPPS. Forskuddet nÃ¥ og tillegg og restbeløpet innen uke 46.",

    // Steps
    stepSize: "Størrelse",
    stepRibbe: "Ribbe",
    stepExtras: "Ekstra",
    stepDelivery: "Levering",

    step1Title: "1. Velg kassestørrelse",
    step2Title: "2. Velg ribbe-type",
    step3Title: "3. Ekstra kjøttprodukter (valgfritt)",
    step4Title: "4. Levering og tillegg",

    // Size selection
    persons2to3: "2-3 personer",
    persons4to6: "4-6 personer",
    inBox: "I kassen:",
    moreItems: "mer",
    
    payNow: "Betal nÃ¥",
    payLater: "Betal senere",
    totalLabel: "Totalt",
    summary: "Sammendrag",

    // Ribbe selection
    selectRibbeType: "Velg ribbe-type",
    boxContains: "Din kasse inneholder ca. {size} kg ribbe. Velg hvilken type:",
    tynnribbe: "Tynnribbe",
    tynnribbeDesc: "Klassisk ribbe med ribbein - perfekt sprøstekt svor",
    familieribbe: "Familieribbe",
    familieribbeDesc: "Inkluderer kotelettkammen med ytrefileten - mer og litt magrere kjøtt",
    porchetta: "Porchetta",
    porchettaDesc: "Beinfri nedre mage - italiensk stil",
    butchersChoice: "Slakterens valg",
    butchersChoiceDesc: "Vi velger en god ribbe til deg basert pÃ¥ tilgjengelighet",
    preSelected: "ForhÃ¥ndsvalgt",
    recommended: "Anbefalt",

    // Extras
    extrasTitle: "Ekstra kjøttprodukter (valgfritt)",
    extrasWarning: "Obs: Ekstra produkter er avhengig av tilgjengelighet og grisestørrelse ved slakt. Vi gjør vÃ¥rt beste for Ã¥ oppfylle ønskene dine.",
    quantity: "Mengde:",

    // Delivery
    deliveryOptions: "Leveringsalternativ",
    extraOptions: "Ekstra tilvalg",
    pickupFarm: "Henting pÃ¥ gÃ¥rden",
    pickupFarmAddress: "Tinglemsvegen 91, Namdalseid",
    pickupTrondheim: "Henting i Trondheim",
    pickupTrondheimAddress: "Veita Mat AS, Jomfrugata 17B",
    deliveryE6: "Levering langs E6",
    deliveryE6Address: "Stjørdal-Namsos",
    freshDelivery: "Fersk levering (uke 50/51)",
    freshDeliveryDesc: "Motta kassen fersk i stedet for frossen - kun pÃ¥ gÃ¥rden",

    // Summary
    deposit50Percent: "Forskudd (50%)",
    friendDiscount: "Vennerabatt (-20%)",
    discountCode: "Rabattkode",
    remainderBeforeDelivery: "Rest før levering",
    extraProducts: "Ekstra produkter",
    onlyOneDiscount: "Kun Ã©n rabattkode kan brukes per bestilling",
    hasDiscountCode: "Rabattkode?",

    // Terms
    depositNotRefundable: "Jeg forstÃ¥r at forskuddet ikke refunderes.",
    triggersProd: "Vi jobber med levende dyr, og bestilling av en kasse starter produksjonsplanlegging.",
    agreeToTerms: "Jeg godtar",
    termsLink: "vilkÃ¥rene for kjøpet",

    // Payment
    payWith: "Betal med",
    securePayment: "Sikker betaling med Vipps",
    contactInfoFromVipps: "Dine kontaktopplysninger hentes automatisk fra Vipps",

    // Navigation
    goToRibbeChoice: "GÃ¥ videre til ribbe-valg",
    goToExtras: "GÃ¥ videre til ekstra tillegg",
    goToDelivery: "GÃ¥ videre til levering",

    // Confirmation
    orderReceived: "Bestilling mottatt!",
    thankYou: "Takk for din bestilling. Vi har mottatt din reservasjon og vil sende deg en Vipps-betalingsforespørsel for forskuddet pÃ¥ 50%.",
    orderNumber: "Bestillingsnummer",
    nextSteps: "Neste steg:",
    step1: "Du vil motta en Vipps-betalingsforespørsel for forskuddet (50% av totalbeløpet)",
    step2: "Du fÃ¥r en bekreftelse pÃ¥ e-post nÃ¥r forskuddet er mottatt",
    step3: "Resterende beløp betales ved levering",
    seeMyOrders: "Se mine bestillinger",

    // Errors
    somethingWentWrong: "Noe gikk galt. Vennligst prøv igjen.",
  },

  // My Orders / Customer Portal
  minSide: {
    title: "Min side",
    myOrders: "Mine bestillinger",
    orders: "Bestillinger",
    referrals: "Vennerabatt",
    loginRequired: "Logg inn for Ã¥ se dine bestillinger",
    loginDesc: "Du mÃ¥ logge inn med Vipps for Ã¥ se og administrere dine bestillinger.",
    loginWithVipps: "Logg inn med Vipps",
    canEditUntil: "Du kan endre bestillingen din frem til uke {week}, {year}",
    editPeriodExpired: "Endringsperioden er utløpt (uke {week}, {year})",
    noOrders: "Ingen bestillinger",
    noOrdersDesc: "Du har ikke lagt inn noen bestillinger ennÃ¥.",
    goToOrder: "GÃ¥ til bestilling",
    newOrder: "Legg inn ny bestilling",

    // Order status
    completed: "Fullført",
    depositPaid: "Forskudd betalt",
    waitingForPayment: "Venter pÃ¥ betaling",
    payRemainder: "Betal restbeløp",
    seeDetails: "Se detaljer",

    // Order details
    order: "BESTILLING",
    orderNo: "Ordre",
    box: "Kasse",
    ribbe: "Ribbe",
    delivery: "Levering",
    freshDeliveryIncluded: "Fersk levering",
    extraProductsTitle: "EKSTRA PRODUKTER",
    deposit: "Forskudd",
    remainder: "Restbeløp",
  },

  // Oppdelingsplan (Butcher diagram)
  oppdelingsplan: {
    title: "Oppdelingsplan",
    subtitle: "Trykk pÃ¥ hver del for Ã¥ se hva som er i kassen og hva du kan bestille ekstra",
    titleFull: "Oppdelingsplan - Gris",
    clickInfo: "Klikk pÃ¥ de forskjellige delene for Ã¥ se hvilke produkter som er inkludert i kassen og hva som kan bestilles ekstra",
    ourProducts: "VÃ¥re produkter",
    inBox: "I kassen",
    inBoxDesc: "Disse produktene er inkludert i standardkassen:",
    canOrder: "Kan bestilles ekstra",
    canOrderDesc: "Disse produktene kan legges til bestillingen (begrenset tilgjengelighet):",
    clickForInfo: "Klikk pÃ¥ en del av grisen for Ã¥ se produktinformasjon",
    allCuts: "Alle kutt - Oversikt",
    inBoxShort: "I kassen:",
    extraShort: "Ekstra:",
    noProductsInBox: "Ingen produkter fra denne delen i standardkassen",
    noExtraProducts: "Ingen ekstra produkter tilgjengelig fra denne delen",
    chooseRibbeType: "Velg din ribbe-type",
    ribbeTypeInfo: "Alle tre varianter bruker forskjellige deler av ribbeside og mage",
    butchersChoiceFull: "Slakterens valg: Ikke sikker? Velg 'Slakterens valg' ved bestilling, sÃ¥ velger vi basert pÃ¥ tilgjengelighet.",
    quickSummary: "Rask oversikt",
    seeDetailsBelow: "Se detaljert informasjon om hver del nedenfor",

    // Cut names and descriptions
    nakke: "Nakke",
    nakkeDesc: "Nakken er marmorert med fett og gir saftige koteletter og steik.",
    indrefilet: "Indrefilet",
    indrefiletDesc: "Indrefileten er det aller møreste kjøttet fra grisen.",
    kotelettkam: "Kotelettkam",
    kotelettkamDesc: "Kotelettkammen er fra ryggen og gir møre koteletter. Dette omrÃ¥det brukes ogsÃ¥ i Familieribbe.",
    ribbeside: "Ribbeside",
    ribbesideDesc: "Ribbeside og mage gir ulike typer ribbe. Velg mellom Tynnribbe (med ribbein), Familieribbe (inkl. kotelettkam), eller Porchetta (beinfri nedre mage).",
    svinebog: "Svinebog",
    svinebogDesc: "Bogen passer perfekt til pulled pork, gryter og steik. Dette er et av de mest allsidige stykkene.",
    skinke: "Skinke/LÃ¥r",
    skinkeDesc: "Skinken/lÃ¥ret kan brukes fersk som steik, gryte, eller spekkes. Dette er en stor, mager muskelgruppe.",
    knoke: "Knoke",
    knokeDesc: "Knoken passer til kraft og gryter, eller til steik. Hver kasse inneholder 1 knoke.",
    labb: "Labb",
    labbDesc: "Labben brukes ofte til sylte og kraftsuppe.",
    polserFarse: "Pølser & Farse",
    polserFarseDesc: "Laget av trim og mindre stykker. Perfekt til hverdagsmiddag og julemat.",
  },

  // Referrals
  referrals: {
    createCode: "Opprett vennerabattkode",
    getCredit: "FÃ¥ 10% kreditt for hver venn som bruker din kode",
    howItWorks: "Slik fungerer det:",
    step1: "Du oppretter en personlig rabattkode",
    step2: "Venner fÃ¥r 20% rabatt pÃ¥ forskuddet nÃ¥r de bruker din kode",
    step3: "Du fÃ¥r 10% kreditt av deres kjøp som kan brukes pÃ¥ ditt restbeløp",
    step4: "Maks 5 venner per bestilling kan gi deg kreditt",
    chooseCode: "Velg din unike kode (4-20 tegn, kun bokstaver og tall)",
    exampleCode: "f.eks. KENNETH2026",
    creating: "Oppretter...",
    createButton: "Opprett kode",
    yourCode: "Din vennerabattkode",
    shareCode: "Del denne koden med venner og familie",
    code: "Din kode:",
    copied: "Kopiert!",
    copyCode: "Kopier kode",
    shareButton: "Del kode",
    friendsGet20: "Venner fÃ¥r 20% rabatt pÃ¥ forskuddet â€¢ Du fÃ¥r 10% kreditt per henvisning",
    totalReferrals: "Totale henvisninger",
    availableCredit: "Tilgjengelig kreditt",
    creditRemaining: "Kredittering igjen",
    of: "av",
    unusedBonuses: "Du har {count} ubrukte bonuser!",
    moreReferrals: "Du har henvist flere venner enn du kan fÃ¥ kreditt for med din nÃ¥vÃ¦rende bestilling...",
    orderNew: "Bestill ny kasse",
    yourReferrals: "Dine henvisninger",
    used: "Brukt",
    available: "Tilgjengelig",

    // Input
    haveCode: "Har du en vennerabattkode?",
    enterCode: "Skriv inn kode",
    checking: "Sjekker...",
    useCode: "Bruk kode",
    newCustomersGet20: "Nye kunder fÃ¥r 20% rabatt pÃ¥ forskuddet ved bruk av vennerabattkode",
    codeActivated: "Kode aktivert: {code}",
    youGet20Off: "Du fÃ¥r 20% rabatt pÃ¥ forskuddet ({amount} kr)",
    remove: "Fjern",
    invalidCode: "Ugyldig kode",
    pleaseEnterCode: "Vennligst skriv inn en kode",
    couldNotValidate: "Kunne ikke validere koden",
    couldNotCreate: "Kunne ikke opprette kode",

    // Share message
    shareMessage: "Bestill ullgris fra Tinglum GÃ¥rd og fÃ¥ 20% rabatt pÃ¥ forskuddet med min vennerabattkode: {code}",
  },

  // Admin
  admin: {
    title: "TinglumgÃ¥rd - Admin",
    login: "Admin Login",
    password: "Passord",
    wrongPassword: "Feil passord. Prøv igjen.",
    loginButton: "Logg inn",
    logout: "Logg ut",
    dashboard: "Dashboard",
    refresh: "Oppdater",
    noData: "Ingen data tilgjengelig",

    // Tabs
    overview: "Oversikt",
    orders: "Bestillinger",
    boxConfig: "Boksinnhold",
    rebateCodes: "Rabattkoder",
    extras: "Ekstraprodukter",
    notifications: "Varsler",
    analytics: "Analyse",
    emails: "E-poster",

    // Order management
    searchOrders: "Søk etter ordre, navn eller e-post...",
    filter: "Filtrer",
    exportCSV: "Eksporter CSV",
    ordersSelected: "{count} ordre(r) valgt",
    markReady: "Marker klar",
    lock: "LÃ¥s",
    productionPlan: "Produksjonsplan",
    noOrdersFound: "Ingen bestillinger funnet",
    adjustFilters: "Prøv Ã¥ justere filtrene dine",

    // Table headers
    select: "Velg",
    orderNo: "Ordre",
    customer: "Kunde",
    box: "Boks",
    status: "Status",
    payment: "Betaling",
    actions: "Handlinger",

    // Status options
    pending: "Venter",
    depositPaid: "Forskudd betalt",
    paid: "Betalt",
    locked: "LÃ¥st",
    ready: "Klar",
    delivered: "Levert",

    // Actions
    changeStatusTo: "Endre status til '{status}' for {count} ordrer?",
    lockOrders: "LÃ¥se {count} ordrer? Dette kan ikke angres.",
    ordersUpdated: "{count} ordrer oppdatert",
    ordersLocked: "{count} ordrer lÃ¥st",
    couldNotUpdate: "Kunne ikke oppdatere ordrer",
    couldNotLock: "Kunne ikke lÃ¥se ordrer",
    couldNotExport: "Kunne ikke eksportere CSV",
    selectOrders: "Velg ordrer Ã¥ eksportere",
    couldNotExportPlan: "Kunne ikke eksportere produksjonsplan",
    couldNotUpdateStatus: "Kunne ikke oppdatere status",
    couldNotSaveNotes: "Kunne ikke lagre notater",
    noOrdersSelected: "Ingen ordrer valgt",

    // Analytics
    keyMetrics: "Nøkkeltall",
    totalOrders: "Totale bestillinger",
    uniqueCustomers: "Unike kunder",
    repeatCustomers: "Gjentakende kunder",
    repeatRate: "Gjentakelsesrate",
    conversionFunnel: "Konverteringstrakt",
    popularCombos: "PopulÃ¦re produktkombinasjoner",
    loadingAnalytics: "Laster analysedata...",

    // Email
    sendEmail: "Send e-post",
    history: "Historikk",
  },

  // Footer
  footer: {
    farm: "Tinglum GÃ¥rd",
    location: "Namdalseid, Trøndelag",
    quality: "Kvalitet fra Namdalseid",
    description: "Vi leverer norsk griskjøtt av høyeste kvalitet, oppvokst pÃ¥ gÃ¥rden og behandlet med omtanke fra start til slutt.",
    localRaised: "Lokalt oppvokst",
    seasonBased: "Sesongbasert",
    organic: "Ullgris, ute pÃ¥ beite, rÃ¥varer fra økologisk produksjon i fÃ´ringen",
    links: "Lenker",
    productInfo: "Produktinformasjon",
    myOrders: "Min side",
    myPage: "Min side",
    admin: "Admin",
    contact: "Kontakt",
    legal: "VilkÃ¥r og personvern",
    allRightsReserved: "Alle rettigheter reservert.",
    rights: "Alle rettigheter reservert",
    norwegianQuality: "Norsk kvalitet",
    season2026: "Sesong 2026",
    season: "Sesong 2026",
  },

  // Contact
  contact: {
    contactUs: "Kontakt oss",
    regardingOrder: "AngÃ¥ende ordre {orderNumber}",
    otherWays: "Andre mÃ¥ter Ã¥ kontakte oss pÃ¥:",
    email: "E-post: post@tinglum.no",
    phone: "Telefon: +47 123 45 678",
    yourMessage: "Din melding",
    messagePlaceholder: "f.eks:\n- SpørsmÃ¥l om leveringstidspunkt\n- Endre leveringsadresse\n- SpørsmÃ¥l om produktene",
    responseTime: "Vi svarer vanligvis innen 24 timer",
    orderDetails: "Ordredetaljer:",
    sending: "Sender...",
    sendMessage: "Send melding",
    messageSent: "Meldingen din er sendt! Vi kontakter deg snart.",
    couldNotSend: "Kunne ikke sende melding. Prøv igjen senere.",
    pleaseWriteMessage: "Vennligst skriv en melding",
  },

  // Box contents (fixed items in every box)
  boxContents: {
    ribbe8kg: "ca. 2.0 kg ribbe",
    ribbe12kg: "ca. 3.0 kg ribbe",
    nakkekoteletter8kg: "ca. 0.75 kg nakkekoteletter",
    nakkekoteletter12kg: "ca. 1.0 kg nakkekoteletter",
    julepølse8kg: "ca. 0.5 kg julepølse",
    julepølse12kg: "ca. 1.0 kg julepølse",
    svinesteik8kg: "ca. 1.0 kg svinesteik",
    svinesteik12kg: "ca. 1.0 kg svinesteik",
    medisterfarse8kg: "ca. 1.0 kg medisterfarse",
    medisterfarse12kg: "ca. 1.5 kg medisterfarse",
    knoke: "1 knoke",
    butchersChoice8kg: "+ Slakterens valg (ca. 2-3 kg)",
    butchersChoice12kg: "+ Slakterens valg (ca. 3.5-4.5 kg)",
  },

  // Product list items (shown in boxes)
  products: {
    ribbe: "Ribbe",
    nakkekoteletter: "Nakkekoteletter",
    julepølse: "Julepølse",
    svinesteik: "Svinesteik",
    medisterfarse: "Medisterfarse",
    knoke: "Knoke",
    butchersChoice: "Slakterens valg",
  },

  // Cuts page
  cuts: {
    title: "Oppdelingsplan",
    hover: "Hold over et kutt for info",
    inBox: "I kassen",
    extraOrder: "Ekstra",
    shoulder: "Bog",
    loin: "Kam",
    belly: "Mage/Ribbe",
    leg: "LÃ¥r",
  },

  // Messaging/Admin
  messaging: {
    sendMessage: "Send melding",
    chooseRecipients: "Velg mottakere og send en melding til deres innboks.",
    allClients: "Alle klienter",
    selectClients: "Velg klienter",
    filters: "Filtre",
    subject: "Emne",
    category: "Kategori",
    support: "Støtte",
    inquiry: "SpørsmÃ¥l",
    complaint: "Klage",
    message: "Melding",
    writeAnnouncement: "Skriv din kunngjøring...",
    awaitingFinalPayment: "Venter pÃ¥ sluttbetaling",
    boxSize: "Bokssstørrelse",
    all: "Alle",
    hasExtras: "Har tillegg",
    extrasFilter: "Filter for tillegg",
    previewRecipients: "ForhÃ¥ndsvis mottakere",
    exclude: "Ekskluder",
    clearAll: "Fjern alt",
    send: "Send",
    sendingBroadcast: "Sender...",
    broadcastSent: "Melding sendt til alle mottakere!",
    replies: "Svar",
    replyPlaceholder: "Skriv ditt svar her...",
    sendReply: "Send svar",
    open: "Ã…pen",
    inProgress: "PÃ¥gÃ¥r",
    resolved: "Løst",
    closed: "Lukket",
    status: "Status",
    priority: "Prioritet",
    low: "Lav",
    normal: "Normal",
    high: "Høy",
    urgent: "Haster",
    noMessages: "Ingen meldinger",
  },
};


