export const en = {
  // Navigation & Common
  nav: {
    products: "Boxes",
    cuts: "Cuts",
    myOrders: "My page",
    admin: "Admin",
    breeds: "Breeds",
    hatchingTips: "Hatching tips",
    oppdelingsplan: "Butcher diagram",
    minebestillinger: "My orders",
    logout: "Log out",
    login: "Log in",
    order: "Order",
    goToEggs: "Go to Eggs",
    goToPigs: "Go to Pork",
    back: "Back",
    backToHome: "Back to home",
  },

  // Common words/actions
  common: {
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    error: "Something went wrong",
    confirm: "Confirm",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    remove: "Remove",
    continue: "Continue",
    processing: "Processing...",
    free: "Free",
    total: "Total",
    kr: "NOK",
    kg: "kg",
    stk: "pcs",
    week: "week",
    year: "year",
    currency: "NOK",
    backTo: "Back to",
    languageCodeNo: "NO",
    languageCodeEn: "EN",
  },

  // Hero section
  hero: {
    season: "Season 2026",
    seasonOnce: "Only once a year",
    porkFrom: "Woolly Pig from",
    headline: "Woolly Pig from",
    title: "Hatching eggs from Tinglum Farm",
    farmName: "Tinglum GÃ¥rd",
    subtitle: "Pork from Tinglum GÃ¥rd in Namdalseid. The pigs grow up on the farm throughout 2026, are slaughtered locally in December, and delivered fresh to your door.",
    cta: "Reserve now",
    reserveNow: "Reserve now",
    learnMore: "Learn more about the product",
    joinWaitlist: "Join waiting list",
    qualityHeadline: "Norwegian quality",
    tagline: "Vacuum packed, freezer-ready, delivered week 48.",
    reserveBeforeLate: "Reserve your box before it's too late",
    description: "Pork from Tinglum GÃ¥rd in Namdalseid. The pigs grow up on the farm throughout 2026, are slaughtered locally in December, and delivered fresh to your door.",
    localRaised: "Locally raised",
    qualityGuarantee: "Quality guarantee",
    limitedOffer: "Limited offer",
    limitedProduction: "We only produce what we have capacity for. When the season's boxes are reserved, we close ordering until 2027.",
    reservePackageNow: "Reserve your box now",
  },

  // Eggs hero
  eggsHero: {
    title: "Hatching eggs from Tinglum Farm",
    subtitle:
      "Hatching eggs from Tinglum GÃ¥rd in Namdalseid. Fresh, carefully selected eggs from multiple breeds and beautiful egg colors, delivered week by week in season.",
  },

  // Eggs browse
  browse: {
    byBreed: "By breed",
    byWeek: "By week",
    week: "Week",
    soldOut: "Sold out",
    eggsAvailable: "eggs available",
  },

  // Egg breed detail labels
  breed: {
    deliveryFrom: "Shipping from",
    pricePerEgg: "per egg",
    calculatedAtCheckout: "calculated at checkout",
    viewDetails: "View details",
    eggColor: "Egg color",
    production: "Production",
    minOrder: "Minimum",
    eggs: "eggs",
    characteristics: "Characteristics",
    size: "Size",
    minEggWeight: "Min egg weight",
    temperament: "Temperament",
    hatchingInfo: "Hatching info",
    incubation: "Incubation",
    days: "days",
    temperature: "Temperature",
    humidity: "Humidity",
    qualityNote: "Fresh eggs from free-range hens. Shipping is calculated at checkout.",
    selectWeek: "Select week",
    available: "Available",
  },

  // Quantity selector
  quantity: {
    available: "available",
    numberOfEggs: "Number of eggs",
    min: "Min",
    max: "Max",
    eggs: "eggs",
    subtotal: "Subtotal",
    shippingCalculated: "shipping calculated at checkout",
    addToCart: "Add to cart",
  },

  // Product/Box selection
  product: {
    chooseYourBox: "Choose your box",
    choosePackage: "Choose your package",
    twoSizes: "Two sizes to choose from",
    sameQuality: "Same high quality regardless of size. Choose the box that best fits your household.",
    smallBox: "Smaller box",
    smallerPackage: "Smaller package",
    largeBox: "Larger box",
    largerPackage: "Larger package",
    mostPopular: "Most popular",
    betterPricePerKg: "Better price per kg",
    perfectFor2to3: "Perfect for 2-3 people or smaller consumption",
    idealFor4to6: "Ideal for 4-6 people or larger consumption",
    inEach8kgBox: "In each 8 kg box:",
    inEach8kg: "In each 8 kg box",
    inEach12kgBox: "In each 12 kg box:",
    inEach12kg: "In each 12 kg box",
    reserve8kg: "Reserve 8 kg box",
    reserve12kg: "Reserve 12 kg box",
    boxesLeft: "boxes left",
    lowStock: "Low stock",
    soldOut: "Sold out",
    priceDeposit: "Pay now",
    priceRemainder: "Balance at delivery",
    deposit50: "Advance payment (50%)",
    remainderAtDelivery: "Balance at delivery",
    balanceOnDelivery: "Balance at delivery",
    totalPrice: "Total price",
    seeDetails: "See contents",
    kg: "kg",
    orderNow: "Reserve now",
    joinWaitlist: "Join waitlist",
    box8: "8 kg box",
    box12: "12 kg box",
  },

  // Product detail page
  productDetail: {
    title: "Woolly Pig Meat Package",
    variation: "Contents vary slightly, but this is approximately what you get:",
    categories: {
      ribbe: "Pork Ribs",
      sausages: "Sausages",
      bacon: "Bacon",
      chops: "Chops",
      stew: "Stew Meat",
    },
    addons: {
      title: "Add-ons",
      disabled: "Add-ons can be selected during checkout",
      delivery: "Delivery Trondheim",
      highway: "Pickup along E6",
      fresh: "Fresh delivery (week 50-51)",
    },
  },

  // Availability section
  availability: {
    title: "Availability",
    boxesAvailable: "Boxes available",
    remainingBoxes: "Few remaining",
    fewLeft: "Few left",
    soldOut: "Sold out",
    soldOutComplete: "Sold out",
    reserveBeforeTooLate: "Reserve before it's too late",
    reserveBeforeLate: "Reserve before it's too late",
    seasonProductionComplete: "Season production complete",
    seasonComplete: "Season production complete",
  },

  // Timeline/How it works
  timeline: {
    title: "How it works",
    subtitle: "From order to delivery",
    tagline: "The pigs grow throughout 2026 â€¢ Fresh delivery in December",
    reserveNow: "Reserve your box now",
    howItWorks: "How it works",
    fromOrderToDelivery: "From order to delivery",
    step1Title: "Reserve your box now",
    step1Desc: "Pay advance payment (50%) with Vipps. Your spot is secured when payment is completed.",
    step1Time: "Week 45",
    step2Title: "Balance payment",
    step2Desc: "By week 46 you pay the remaining 50% of the total amount. You'll receive payment information by email.",
    step2Time: "Week 46-47",
    step3Title: "Slaughter and frozen delivery",
    step3Desc: "The pigs are professionally slaughtered and packed fresh. Then everything is frozen for optimal shelf life and delivered in week 48-49.",
    step3Time: "Week 48-49",
    step4Title: "Fresh delivery (optional)",
    step4Desc: "For a small extra fee you can choose fresh delivery in week 50-51. Perfect if you want the meat completely fresh!",
    step4Time: "Week 50-51",
    optional: "Optional",
    week44: "Week 45: Payment completed",
    week46: "Week 47: Final deadline for changes",
    week48: "Week 49: Delivery and pickup",
    week44Desc: "You'll be notified and complete payment before delivery.",
    week46Desc: "Change size and extras until the deadline, after which the order is locked.",
    week48Desc: "Pickup or delivery according to chosen option.",
  },

  // FAQ
  faq: {
    title: "Questions and answers",
    badge: "FAQ",
    commonQuestions: "Common questions",
    q1: "What do I get in the box?",
    a1: "Fixed structure, small variations are normal. You get ribs, bacon, sausages, pork chops and cooking cuts. Everything is portioned, labeled and vacuum packed.",
    q2: "When will I receive delivery?",
    a2: "Frozen box is delivered in week 48. Fresh box can be chosen for an extra fee and is delivered at the end of week 50 or beginning of week 51.",
    q3: "Can I change my order?",
    a3: "Yes, until week 46. After the deadline the order is locked so we can plan production and packing.",
    q4: "How do I pick up or get delivery?",
    a4: "You can choose delivery along E6 between Levanger and Namsos, or Trondheim. Price is shown in checkout before you confirm.",
  },

  // Checkout/Order page
  checkout: {
    title: "Order",
    pageTitle: "Reserve your box",
    subtitle: "Reserve your box with Vipps",
    selectSize: "Choose size, rib type and extra items. We'll send you a Vipps payment request after ordering.",

    // Steps
    stepSize: "Size",
    stepRibbe: "Ribs",
    stepExtras: "Extras",
    stepDelivery: "Delivery",

    step1Title: "1. Choose box size",
    step2Title: "2. Choose rib type",
    step3Title: "3. Extra meat products (optional)",
    step4Title: "4. Delivery and extras",

    // Size selection
    persons2to3: "2-3 people",
    persons4to6: "4-6 people",
    inBox: "In the box:",
    moreItems: "more",
    
    payNow: "Pay now",
    payLater: "Pay later",
    totalLabel: "Total",
    summary: "Summary",

    // Ribbe selection
    selectRibbeType: "Choose rib type",
    boxContains: "Your box contains approx. {size} kg of ribs. Choose which type:",
    tynnribbe: "Thin ribs",
    tynnribbeDesc: "Classic ribs with rib bones - perfectly crispy rind",
    familieribbe: "Family ribs",
    familieribbeDesc: "Includes the loin with tenderloin - more meat, leaner meat",
    porchetta: "Porchetta",
    porchettaDesc: "Boneless lower belly - Italian style",
    butchersChoice: "Butcher's choice",
    butchersChoiceDesc: "We'll choose a good rib for you based on availability",
    preSelected: "Pre-selected",
    recommended: "Recommended",

    // Extras
    extrasTitle: "Extra meat products (optional)",
    extrasWarning: "Extra products cannot be guaranteed, and availability is very limited. By paying the remaining balance/completing the order, you secure your place in the queue. We fulfill orders based on when the remaining balance/extra orders are paid.",
    quantity: "Quantity:",

    // Delivery
    deliveryOptions: "Delivery options",
    extraOptions: "Extra options",
    pickupFarm: "Pickup at farm",
    pickupFarmAddress: "Tinglemsvegen 91, Namdalseid",
    pickupTrondheim: "Pickup in Trondheim",
    pickupTrondheimAddress: "Veita Mat AS, Jomfrugata",
    deliveryE6: "Delivery along E6",
    deliveryE6Address: "StjÃ¸rdal-Namsos",
    freshDelivery: "Fresh delivery (week 50/51)",
    freshDeliveryDesc: "Receive the box fresh instead of frozen - only at the farm",

    // Summary
    deposit50Percent: "Advance payment (50%)",
    friendDiscount: "Friend discount (-20%)",
    discountCode: "Discount code",
    remainderBeforeDelivery: "Balance before delivery",
    extraProducts: "Extra products",
    onlyOneDiscount: "Only one discount code can be used per order",
    hasDiscountCode: "Discount code?",

    // Terms
    depositNotRefundable: "I understand that the advance payment is non-refundable.",
    triggersProd: "This triggers production planning.",
    agreeToTerms: "I agree to the",
    termsLink: "terms of purchase",

    // Payment
    payWith: "Pay with",
    securePayment: "Secure payment with Vipps",
    contactInfoFromVipps: "Your contact information is automatically retrieved from Vipps",

    // Navigation
    goToRibbeChoice: "Continue to rib selection",
    goToExtras: "Continue to extras",
    goToDelivery: "Continue to delivery",

    // Confirmation
    orderReceived: "Order received!",
    thankYou: "Thank you for your order. We have received your reservation and will send you a Vipps payment request for the 50% advance payment.",
    expectedDelivery: "Expected delivery: week 48-49.",
    orderNumber: "Order number",
    nextSteps: "Next steps:",
    step1: "You will receive a Vipps payment request for the advance payment (50% of total amount)",
    step2: "You'll get a confirmation email when the advance payment is received",
    step3: "Remaining amount is paid at delivery",
    seeMyOrders: "See my orders",

    // Errors
    somethingWentWrong: "Something went wrong. Please try again.",
  },

  // Eggs flows (browse, cart, checkout, orders)
  eggs: {
    common: {
      loading: "Loading...",
      loadingBreeds: "Loading breeds...",
      loadingWeeks: "Loading weeks...",
      loadingBreed: "Loading breed...",
      loadingOrder: "Loading order...",
      close: "Close",
      backToBreeds: "Back to breeds",
      backToCart: "Back to cart",
      backToShipment: "Back to shipment",
      backToOrders: "Back to orders",
      cartAria: "Shopping cart",
      toggleLanguageAria: "Toggle language",
      order: "Order",
      orderNumber: "Order number",
      breed: "Breed",
      breeds: "Breeds",
      week: "Week",
      shipment: "Shipment",
      shippingDate: "Shipping date",
      eggs: "eggs",
      totalEggs: "Total eggs",
      summary: "Summary",
      subtotal: "Subtotal",
      additions: "Additions",
      alreadyPaid: "Already paid",
      deposit: "Deposit",
      remainder: "Remainder",
      total: "Total",
      dueDate: "Due date",
      dueNow: "Due now",
      notPaid: "Not paid",
      daysLeft: "days left",
      continueToPayment: "Continue to payment",
      payWithVipps: "Pay with Vipps",
      addEggs: "Add eggs",
      fallbackBreed: "Eggs",
    },
    errors: {
      loadEggData: "Failed to load egg data.",
      loadBreeds: "Failed to load breeds.",
      loadBreed: "Failed to load breed.",
      orderNotFound: "Order not found.",
      couldNotFindOrder: "We could not find your order.",
      couldNotFetchOrders: "Failed to fetch orders",
      couldNotFetchOrder: "Failed to fetch order",
      couldNotFetchInventory: "Failed to fetch available weeks",
      couldNotSaveAdditions: "Failed to save additions",
      couldNotStartPayment: "Failed to start payment",
      shippingAddressMissing: "Shipping address is missing. Go back and complete the address.",
      vippsLoginFailed: "Failed to start Vipps login. Please try again.",
    },
    breedsPage: {
      subtitle:
        "Four unique breeds with distinctive characteristics. All our chickens are free-range and fed organic feed.",
      browseBreeds: "View breeds",
      breedNotFound: "Breed not found",
      pricePerEgg: "Price per egg",
    },
    activeOrderPrompt: {
      title: "You have an active order",
      description: "Do you want to add more eggs to the same order and week?",
      activeWeek: "Active week",
      eggsInOrderAndLeft: "{inOrder} eggs in order Â· {left} left",
      yesContinue: "Yes, continue",
      noNewOrder: "No, new order",
    },
    cart: {
      title: "Shopping Cart",
      emptyTitle: "Cart is empty",
      emptyDescription: "Add eggs to get started",
      cartEmptyMessage: "Cart is empty",
      weekLabel: "Week",
      perEgg: "egg",
      minimum: "Minimum",
      summaryTitle: "Summary",
      shippingCalculatedNext: "shipping calculated in next step",
      addMoreEggs: "Add more eggs",
      readyForCheckout: "Ready for checkout!",
      mixedInfo:
        "You can adjust quantities anytime. The order proceeds when all requirements are met.",
      goToCheckout: "Go to checkout",
      continueShopping: "Continue shopping",
      mixedOrderTitle: "Build a mixed order",
      mixedOrderDescription: "Add eggs from other breeds to reach the 12-egg minimum.",
      leftThisWeek: "Left this week",
      done: "Done",
      ayamMinimum: "Ayam Cemani: minimum 6 eggs (you have {count})",
      singleBreedMinimum: "Minimum 10 eggs for a single breed (you have {count})",
      mixedMinimum:
        "Minimum 12 eggs total when mixing breeds (unless one breed has 10 eggs, Ayam Cemani 6). You have {count}",
      mixedWeeks: "Choose eggs from the same week for a single shipment.",
      onlyEggsLeftThisWeek: "Only {count} eggs left this week. We suggested {count} eggs.",
    },
    delivery: {
      title: "Shipment",
      subtitle: "Choose how the eggs will be shipped or picked up.",
      postenTitle: "Posten shipment",
      postenDescription: "Shipped with Posten to your nearest pickup point.",
      farmPickupTitle: "Farm pickup",
      farmPickupDescription: "Pick up at Tinglum farm by appointment.",
      e6PickupTitle: "E6 pickup point",
      e6PickupDescription: "Pickup at an agreed E6 meeting point.",
      recommended: "Recommended",
      unavailableThisWeek: "Not available this week.",
      shippingAddressTitle: "Shipping address",
      shippingAddressDescription: "We need your address for Posten shipment.",
      address: "Address",
      addressPlaceholder: "Street address",
      postalCode: "Postal code",
      city: "City",
      cityPlaceholder: "City",
      country: "Country",
      countryPlaceholder: "Norway",
      addressRequired: "Fill in all address fields to continue.",
      methodInfo:
        "Farm pickup and E6 Namsos-Trondheim delivery are wishes that may be arranged after the deposit is paid. Send a message after the deposit, and we will see if it can be arranged.",
    },
    payment: {
      title: "Payment",
      subtitleFullPayment: "Pay the full amount to confirm your order.",
      subtitleDeposit: "Pay the deposit for the eggs to confirm your order.",
      fullPaymentTitle: "Full payment",
      depositTitle: "Deposit",
      fullPaymentDescription: "The order ships soon, so the full amount is due now.",
      depositDescription: "You pay 50% for the eggs now, the rest before shipment.",
      nonRefundableNote:
        "The deposit is non-refundable. We work with live animals, and the order starts production planning.",
      dueNow: "Due now",
      depositDue: "Deposit due",
      securePaymentTitle: "Secure payment",
      securePaymentDescription: "We use Vipps for fast and secure payments.",
      orderTitle: "Order",
      packingAndShipment: "Packing and shipment",
      fullPayment: "Full payment",
      deposit: "Deposit",
    },
    confirmation: {
      orderNotFoundTitle: "Order not found",
      orderNotFoundDescription: "We could not find your order.",
      titleCompleted: "Order confirmed!",
      titleFailed: "Payment failed",
      titlePending: "Waiting for payment confirmation",
      leadCompleted: "We have registered your deposit payment.",
      leadFailed: "The Vipps payment was not completed.",
      leadPending: "We are still waiting for confirmation from Vipps.",
      failedHelp:
        "Payment was not registered as completed. Open \"My orders\" and retry payment.",
      pendingHelp:
        "If payment is completed in Vipps, status updates automatically when confirmation arrives.",
      goToMyOrders: "Go to my orders",
    },
    myOrders: {
      authTitle: "Log in with Vipps",
      authDescription: "Log in to view your hatching egg orders.",
      pageTitle: "My orders",
      pageDescription: "Overview of your hatching egg orders.",
      tabOrders: "Orders",
      tabMessages: "Messages",
      noOrders: "No orders found yet.",
      browseBreeds: "Browse breeds",
      quantity: "Quantity",
      total: "Total",
      delivery: "Shipment",
      payRemainder: "Pay remainder",
      addEggs: "Add eggs",
      timeline: "Timeline",
      duePrefix: "Due",
      shipmentPrefix: "Shipment",
      additionsSuffix: "+{count} additions",
      statusPending: "Pending",
      statusRemainderDue: "Remainder due",
      statusDepositPaid: "Deposit paid",
      statusPaid: "Paid",
      statusPreparing: "Preparing",
      statusShipped: "Shipped",
      statusDelivered: "Delivered",
      statusForfeited: "Forfeited",
      statusCancelled: "Cancelled",
      stepPlaced: "Order placed",
      stepDeposit: "Deposit",
      stepRemainder: "Remainder",
      stepShipment: "Shipment",
      deliveryPosten: "Posten shipment",
      deliveryE6: "E6 pickup",
      deliveryFarm: "Farm pickup",
    },
    remainderPayment: {
      unavailable: "Remainder payment is not available for this order.",
      title: "Pay remainder",
      orderLabel: "Order {orderNumber}",
      depositPaidEggs: "Deposit paid (eggs)",
      addMoreEggsOptional: "Add more eggs (optional)",
      sameShipmentWeek: "Same shipment week",
      additionsClosed: "Additions close at 23:59 on the day before shipment.",
      discountToday: "30% off extra eggs today.",
      noEggsThisWeek: "No available eggs for this week.",
      eggsLeft: "eggs left",
      paymentSummaryTitle: "Payment summary",
      paymentSummaryDescription: "The remainder includes packing and shipment.",
    },
    remainderConfirmation: {
      paymentReceivedTitle: "Payment received!",
      confirmingTitle: "Confirming payment...",
      paymentReceivedLead: "The remainder has been registered.",
      confirmingLead: "This can take a minute. The page will refresh automatically.",
      backToOrders: "Back to orders",
      addEggs: "Add eggs",
    },
    weekSelector: {
      chooseMonth: "Choose month",
      through: "Through {date}",
      weeks: "weeks",
      eggs: "eggs",
      weekShort: "Week",
      weekShortAbbr: "Wk",
      eggShort: "Eggs",
      backToMonths: "Back to months",
      available: "Available",
      status: "Status",
      shipsIn: "Ships in",
      days: "days",
      statusSoldOut: "Sold out",
      statusLowStock: "Low stock",
      statusClosed: "Closed",
      statusLocked: "Locked",
      statusAvailable: "Available",
      statusNotScheduled: "Not scheduled",
      dayLabels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    },
    hatchingTips: {
      title: "Hatching Tips",
      subtitle: "Practical guidance for a safe, successful hatch.",
      note: "Questions? Reach out - we are happy to help.",
      sections: [
        {
          title: "Before incubation",
          items: [
            "Store eggs cool (12-16C) with the point down.",
            "Incubate within 7 days of lay for best results.",
            "Let eggs rest at room temperature 6-8 hours before setting.",
            "Do not wash eggs - dry clean only if needed.",
          ],
        },
        {
          title: "During incubation",
          items: [
            "Stable temperature: 37.5C for most breeds.",
            "Keep humidity around 50-55% days 1-18.",
            "Turn eggs 3-5 times daily (automatic turning preferred).",
            "Vent the incubator briefly after week 2.",
          ],
        },
        {
          title: "Hatching (days 19-21)",
          items: [
            "Increase humidity to 65-70% from day 19.",
            "Stop turning when hatch begins.",
            "Avoid opening the incubator unnecessarily.",
            "Let chicks dry fully before moving.",
          ],
        },
        {
          title: "After hatch",
          items: [
            "Keep chicks warm (32-35C first week).",
            "Provide water and starter feed immediately.",
            "Lower temperature by 2-3C per week.",
            "Monitor activity and appetite - best health indicators.",
          ],
        },
      ],
    },
  },

  terms: {
    back: "Back",
    title: "Terms and Conditions - Tinglum GÃ¥rd",
    intro:
      "These terms apply to purchases of goods from Tinglum GÃ¥rd through our website. By completing a purchase, you confirm that you have read and accepted these terms.",
    sellerLabel: "Seller:",
    buyerParagraph:
      "The buyer is the person who completes the order and is referred to as \"customer\".",
    sections: [
      {
        title: "1. Parties",
        bullets: [
          "Tinglum GÃ¥rd",
          "Organization number: 995 752 328",
          "Address: Tinglemsvegen 91, 7750 NAMDALSEID, Norway",
          "Email: post@tinglum.com",
        ],
      },
      {
        title: "2. Payment",
        paragraphs: [
          "Payment is made via Vipps.",
          "The deposit functions as a reservation of a limited production batch and is binding.",
        ],
        bullets: [
          "Upon ordering, a deposit of 50% of the total amount is paid.",
          "The remaining amount is paid before delivery, according to information provided at the time of order.",
        ],
      },
      {
        title: "3. Delivery",
        paragraphs: [
          "Goods are delivered according to the selected delivery option at checkout, for example:",
          "Delivery time is stated on the product page and may vary based on season and production.",
          "Goods are generally delivered frozen and vacuum-packed, unless otherwise agreed.",
        ],
        bullets: [
          "Pickup at the farm",
          "Delivery to specified areas",
          "Possible delivery in Trondheim",
        ],
      },
      {
        title: "4. Right of Withdrawal",
        paragraphs: [
          "In accordance with Norwegian consumer law Â§ 22, the right of withdrawal does not apply to goods that:",
          "Purchases of meat and meat products from Tinglum GÃ¥rd are therefore not covered by the right of withdrawal.",
        ],
        bullets: [
          "are produced according to customer specifications, or",
          "have a clearly personal character, or",
          "are perishable food items.",
        ],
      },
      {
        title: "5. Returns",
        paragraphs: [
          "Return of goods is not possible, as these are food items delivered frozen or fresh upon order.",
          "If Tinglum GÃ¥rd is unable to deliver as agreed, the paid amount will be refunded in full.",
        ],
      },
      {
        title: "6. Complaints",
        paragraphs: [
          "If the product has a defect, the customer must notify within a reasonable time after the defect was discovered or should have been discovered.",
          "Complaints should be sent in writing to the email address stated under section 1, and should include:",
          "Complaints are handled in accordance with Norwegian consumer purchase law.",
        ],
        bullets: [
          "Order number",
          "Description of the defect",
          "Any documentation (photos)",
        ],
      },
      {
        title: "7. Dispute Resolution",
        paragraphs: [
          "Any disputes will be attempted to be resolved amicably.",
          "If this does not succeed, the customer can take the matter to the Norwegian Consumer Authority or Consumer Complaints Board.",
        ],
      },
    ],
    legalNotice:
      "These terms are intended as information for customers and do not constitute legal advice.",
  },

  // My Orders / Customer Portal
  minSide: {
    title: "My page",
    myOrders: "My orders",
    orders: "Orders",
    referrals: "Friend discount",
    loginRequired: "Log in to see your orders",
    loginDesc: "You must log in with Vipps to view and manage your orders.",
    loginWithVipps: "Log in with Vipps",
    canEditUntil: "You can edit your order until week {week}, {year}",
    editPeriodExpired: "Edit period has expired (week {week}, {year})",
    noOrders: "No orders",
    noOrdersDesc: "You haven't placed any orders yet.",
    goToOrder: "Go to order",
    newOrder: "Place new order",

    // Order status
    completed: "Completed",
    depositPaid: "Deposit paid",
    waitingForPayment: "Waiting for payment",
    payRemainder: "Pay balance",
    seeDetails: "See details",

    // Order details
    order: "ORDER",
    orderNo: "Order",
    box: "Box",
    ribbe: "Ribs",
    delivery: "Delivery",
    freshDeliveryIncluded: "Fresh delivery",
    extraProductsTitle: "EXTRA PRODUCTS",
    deposit: "Deposit",
    remainder: "Balance",
    dueDate: "Due date",
  },

  // Oppdelingsplan (Butcher diagram)
  oppdelingsplan: {
    title: "Butcher diagram",
    subtitle: "Click on each part to see what's in the box and what you can order extra",
    titleFull: "Butcher diagram - Pig",
    clickInfo: "Click on the different parts to see which products are included in the box and what can be ordered extra",
    ourProducts: "Our products",
    inBox: "In the box",
    inBoxDesc: "These products are included in the standard box:",
    canOrder: "Can be ordered extra",
    canOrderDesc: "These products can be added to the order (limited availability):",
    clickForInfo: "Click on a part of the pig to see product information",
    allCuts: "All cuts - Overview",
    inBoxShort: "In the box:",
    extraShort: "Extra:",
    noProductsInBox: "No products from this part in the standard box",
    noExtraProducts: "No extra products available from this part",
    chooseRibbeType: "Choose your rib type",
    ribbeTypeInfo: "All three variants use different parts of the rib side and belly",
    butchersChoiceFull: "Butcher's choice: Not sure? Choose 'Butcher's choice' when ordering, and we'll select based on availability.",
    quickSummary: "Quick summary",
    seeDetailsBelow: "See detailed information about each part below",

    // Cut names and descriptions
    nakke: "Neck",
    nakkeDesc: "The neck is marbled with fat and produces juicy chops and roasts.",
    indrefilet: "Tenderloin",
    indrefiletDesc: "The tenderloin is the most tender meat from the pig.",
    kotelettkam: "Loin",
    kotelettkamDesc: "The loin is from the back and produces tender chops. This area is also used in Family ribs.",
    ribbeside: "Rib side",
    ribbesideDesc: "Rib side and belly produce different types of ribs. Choose between Thin ribs (with rib bones), Family ribs (incl. loin), or Porchetta (boneless lower belly).",
    svinebog: "Shoulder",
    svinebogDesc: "The shoulder is perfect for pulled pork, stews and roasts. This is one of the most versatile cuts.",
    skinke: "Ham/Leg",
    skinkeDesc: "The ham/leg can be used fresh for roasts, stews, or cured. This is a large, lean muscle group.",
    knoke: "Hock",
    knokeDesc: "The hock is suitable for stock and stews, or for roasting. Each box contains 1 hock.",
    labb: "Trotter",
    labbDesc: "The trotter is often used for head cheese and stock soup.",
    polserFarse: "Sausages & Ground meat",
    polserFarseDesc: "Made from trim and smaller pieces. Perfect for everyday meals and holiday food.",
  },

  // Referrals
  referrals: {
    createCode: "Create friend discount code",
    getCredit: "Get 10% credit for each friend who uses your code",
    howItWorks: "How it works:",
    step1: "You create a personal discount code",
    step2: "Friends get 20% off the deposit when they use your code",
    step3: "You get 10% credit of their purchase that can be used on your balance",
    step4: "Maximum 5 friends per order can give you credit",
    chooseCode: "Choose your unique code (4-20 characters, letters and numbers only)",
    exampleCode: "e.g. KENNETH2026",
    creating: "Creating...",
    createButton: "Create code",
    yourCode: "Your friend discount code",
    shareCode: "Share this code with friends and family",
    code: "Your code:",
    copied: "Copied!",
    copyCode: "Copy code",
    shareButton: "Share code",
    friendsGet20: "Friends get 20% off the deposit â€¢ You get 10% credit per referral",
    totalReferrals: "Total referrals",
    availableCredit: "Available credit",
    creditRemaining: "Credit remaining",
    of: "of",
    unusedBonuses: "You have {count} unused bonuses!",
    moreReferrals: "You have referred more friends than you can get credit for with your current order...",
    orderNew: "Order new box",
    yourReferrals: "Your referrals",
    used: "Used",
    available: "Available",

    // Input
    haveCode: "Do you have a friend discount code?",
    haveRebateCode: "Do you have a discount code?",
    enterCode: "Enter code",
    checking: "Checking...",
    useCode: "Use code",
    newCustomersGet20: "New customers get 20% off the deposit when using a friend discount code",
    codeActivated: "Code activated: {code}",
    youGet20Off: "You get 20% off the deposit ({amount} NOK)",
    youSave: "You save {amount} NOK",
    remove: "Remove",
    invalidCode: "Invalid code",
    pleaseEnterCode: "Please enter a code",
    couldNotValidate: "Could not validate the code",
    couldNotCreate: "Could not create code",

    // Share message
    shareMessage: "Order Woolly Pig from Tinglum GÃ¥rd and get 20% off the deposit with my friend discount code: {code}",
  },

  // Admin
  admin: {
    title: "TinglumgÃ¥rd - Admin",
    login: "Admin Login",
    password: "Password",
    wrongPassword: "Wrong password. Try again.",
    loginButton: "Log in",
    logout: "Log out",
    dashboard: "Dashboard",
    refresh: "Refresh",
    noData: "No data available",

    // Tabs
    overview: "Overview",
    orders: "Orders",
    boxConfig: "Box contents",
    rebateCodes: "Discount codes",
    extras: "Extra products",
    notifications: "Notifications",
    analytics: "Analytics",
    emails: "Emails",

    // Order management
    searchOrders: "Search for order, name or email...",
    filter: "Filter",
    exportCSV: "Export CSV",
    ordersSelected: "{count} order(s) selected",
    markReady: "Mark ready",
    lock: "Lock",
    productionPlan: "Production plan",
    noOrdersFound: "No orders found",
    adjustFilters: "Try adjusting your filters",

    // Table headers
    select: "Select",
    orderNo: "Order",
    customer: "Customer",
    box: "Box",
    status: "Status",
    payment: "Payment",
    actions: "Actions",

    // Status options
    pending: "Pending",
    depositPaid: "Deposit paid",
    paid: "Paid",
    locked: "Locked",
    ready: "Ready",
    delivered: "Delivered",

    // Actions
    changeStatusTo: "Change status to '{status}' for {count} orders?",
    lockOrders: "Lock {count} orders? This cannot be undone.",
    ordersUpdated: "{count} orders updated",
    ordersLocked: "{count} orders locked",
    couldNotUpdate: "Could not update orders",
    couldNotLock: "Could not lock orders",
    couldNotExport: "Could not export CSV",
    selectOrders: "Select orders to export",
    couldNotExportPlan: "Could not export production plan",
    couldNotUpdateStatus: "Could not update status",
    couldNotSaveNotes: "Could not save notes",
    noOrdersSelected: "No orders selected",

    // Analytics
    keyMetrics: "Key metrics",
    totalOrders: "Total orders",
    uniqueCustomers: "Unique customers",
    repeatCustomers: "Repeat customers",
    repeatRate: "Repeat rate",
    conversionFunnel: "Conversion funnel",
    popularCombos: "Popular product combinations",
    loadingAnalytics: "Loading analytics data...",

    // Email
    sendEmail: "Send email",
    history: "History",
  },

  // Footer
  footer: {
    farm: "Tinglum GÃ¥rd",
    location: "Namdalseid, TrÃ¸ndelag",
    quality: "Quality from Namdalseid",
    description: "We deliver Norwegian pork of the highest quality, raised on the farm and treated with care from start to finish.",
    localRaised: "Locally raised",
    seasonBased: "Season-based",
    organic: "Woolly Pig, outdoors on pasture, feed containing ingredients from organic production",
    links: "Links",
    productInfo: "Product information",
    myOrders: "My page",
    myPage: "My page",
    admin: "Admin",
    contact: "Contact",
    legal: "Terms and privacy",
    allRightsReserved: "All rights reserved.",
    rights: "All rights reserved",
    norwegianQuality: "Norwegian quality",
    season2026: "Season 2026",
    season: "Season 2026",
  },

  // Contact
  contact: {
    contactUs: "Contact us",
    regardingOrder: "Regarding order {orderNumber}",
    otherWays: "Other ways to contact us:",
    email: "Email: post@tinglum.no",
    phone: "Phone: +47 123 45 678",
    yourMessage: "Your message",
    messagePlaceholder: "e.g.:\n- Questions about delivery time\n- Change delivery address\n- Questions about products",
    responseTime: "We typically respond within 24 hours",
    orderDetails: "Order details:",
    sending: "Sending...",
    sendMessage: "Send message",
    messageSent: "Your message has been sent! We'll contact you soon.",
    couldNotSend: "Could not send message. Try again later.",
    pleaseWriteMessage: "Please write a message",
  },

  // Box contents (fixed items in every box)
  boxContents: {
    ribbe8kg: "approx. 2.0 kg ribs",
    ribbe12kg: "approx. 3.0 kg ribs",
    nakkekoteletter8kg: "approx. 0.75 kg pork chops",
    nakkekoteletter12kg: "approx. 1.0 kg pork chops",
    julepolse8kg: "approx. 0.5 kg Christmas sausage",
    julepolse12kg: "approx. 1.0 kg Christmas sausage",
    svinesteik8kg: "approx. 1.0 kg pork roast",
    svinesteik12kg: "approx. 1.0 kg pork roast",
    medisterfarse8kg: "approx. 1.0 kg pork sausage meat",
    medisterfarse12kg: "approx. 1.5 kg pork sausage meat",
    knoke: "1 hock",
    butchersChoice8kg: "+ Butcher's choice (approx. 2-3 kg)",
    butchersChoice12kg: "+ Butcher's choice (approx. 3.5-4.5 kg)",
  },

  // Product list items (shown in boxes)
  products: {
    ribbe: "Ribs",
    nakkekoteletter: "Pork chops",
    julepolse: "Christmas sausage",
    svinesteik: "Pork roast",
    medisterfarse: "Pork sausage meat",
    knoke: "Hock",
    butchersChoice: "Butcher's choice",
  },

  // Cuts page
  cuts: {
    title: "Butcher diagram",
    hover: "Hover over a cut for info",
    inBox: "In box",
    extraOrder: "Extra",
    shoulder: "Shoulder",
    loin: "Loin",
    belly: "Belly/Ribs",
    leg: "Leg",
  },

  // Messaging/Admin
  messaging: {
    sendMessage: "Send message",
    chooseRecipients: "Choose recipients and send a message to their inbox.",
    allClients: "All clients",
    selectClients: "Select clients",
    filters: "Filters",
    subject: "Subject",
    category: "Category",
    support: "Support",
    inquiry: "Inquiry",
    complaint: "Complaint",
    message: "Message",
    writeAnnouncement: "Write your announcement...",
    awaitingFinalPayment: "Waiting for final payment",
    boxSize: "Box size",
    all: "All",
    hasExtras: "Has extras",
    extrasFilter: "Extras filter",
    previewRecipients: "Preview recipients",
    exclude: "Exclude",
    clearAll: "Clear all",
    send: "Send",
    sendingBroadcast: "Sending...",
    broadcastSent: "Message sent to all recipients!",
    replies: "Replies",
    replyPlaceholder: "Write your reply here...",
    sendReply: "Send reply",
    open: "Open",
    inProgress: "In progress",
    resolved: "Resolved",
    closed: "Closed",
    status: "Status",
    priority: "Priority",
    low: "Low",
    normal: "Normal",
    high: "High",
    urgent: "Urgent",
    noMessages: "No messages",
  },
  // Countdown timer
  countdownTimer: {
    defaultLabel: "Delivery in week 48",
    expired: "Delivery time!",
    days: "Days",
    hours: "Hours",
    minutes: "Min",
    seconds: "Sec",
  },

  // Extra products selector
  extraProductsSelector: {
    quantity: "Quantity",
    unitPieces: "pcs",
    importantInfo: "Important information about extra products",
    warning:
      "Extra products cannot be guaranteed and availability is very limited. By paying the remainder/completing the order, you secure your place in the queue. We fulfill orders based on when remainder and extra orders are paid.",
    onlyLeft: "Only {count} left",
    totalExtras: "Total extra products",
  },

  // Extra product card
  extraProductCard: {
    soldOut: "Sold out",
    onlyLeft: "Only {count} left",
    unitPieces: "pcs",
  },

  // Instagram feed
  instagramFeed: {
    badge: "Follow us on Instagram",
    title: "See life on the farm",
    description: "Follow the pigs growing up, farm life, and season updates",
    fallback: "Could not load Instagram posts. Visit us on Instagram:",
  },

  // Product card
  productCard: {
    waitlistTitle: "Join the waitlist",
    waitlistDescription: "We will notify you when we have more stock.",
    waitlistSuccess: "Thanks! You are now on the waitlist.",
    emailLabel: "Email *",
    emailPlaceholder: "you@email.com",
    nameLabel: "Name (optional)",
    namePlaceholder: "Your name",
    submitWaitlist: "Join waitlist",
    sending: "Sending...",
  },

  // Product page
  productPage: {
    productLabel: "Product",
    packageContents: "Package contents",
    ribbeItem: "2-3 kg ribs, vacuum-packed",
    sausageItem: "1 kg sausages, frozen",
    baconItem: "500 g bacon, sliced",
    chopsItem: "1.5 kg pork neck chops",
    stewItem: "1-2 kg cooking cuts",
  },

  // Cuts page
  cutsPage: {
    diagramLead: "See where each cut is located, and what is usually included in the box versus available as extras.",
    howToUse: "How to use this",
    howToUse1: "Click a region to see the cut name and typical usage.",
    howToUse2: 'Switch between "In box" and "Extra" in the diagram where supported.',
    howToUse3: "Open the product page for full contents and structure.",
    terminology: "Terminology",
  },

  // Confirmation page
  confirmationPage: {
    orderNotFoundTitle: "Order not found",
    orderNotFoundDescription: "We could not find your order.",
    backHome: "Back to home",
    paymentReceived: "Payment received!",
    paymentFailed: "Payment failed",
    paymentWaiting: "Waiting for payment confirmation...",
    orderNumberLabel: "Order number",
    detailsTitle: "Order details",
    boxSizeLabel: "Box size",
    depositLabel: "Deposit",
    statusLabel: "Status",
    nextStepsTitle: "Next steps",
    statusDraft: "Waiting for deposit",
    statusDepositPaid: "Deposit paid - waiting for remainder",
    statusPaid: "Fully paid",
    statusReadyForPickup: "Ready for pickup",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    statusUnknown: "Unknown status",
    pendingTitle: "Waiting for payment confirmation",
    pendingBody: "We have not received confirmation that the deposit payment of {amount} NOK is completed.",
    pendingReasonsTitle: "This may mean:",
    pendingReason1: "Payment is being processed (this usually takes a few seconds)",
    pendingReason2: "You canceled payment in Vipps",
    pendingReason3: "Your bank blocked the transaction",
    pendingFooter:
      "This page updates automatically when confirmation arrives. If payment does not go through within a few minutes, check your Vipps app or contact us.",
    failedBannerTitle: "Payment failed",
    failedBannerBody: "The deposit payment of {amount} NOK could not be completed.",
    failedBannerHelp: "Please try again or contact us for help.",
    syncingTitle: "Updating order status...",
    syncingBody: "Payment received, updating order details...",
    depositConfirmedTitle: "Deposit confirmed!",
    depositConfirmedBody:
      "We have received your deposit. You will receive a reminder for remainder payment about 2 weeks before pickup.",
    fullyPaidTitle: "Fully paid!",
    fullyPaidBody: "Thank you for full payment. Your order will be prepared for pickup.",
    step1DoneTitle: "Deposit paid",
    step1TodoTitle: "Pay deposit",
    step1DoneBody: "Deposit received. You have received an email confirmation.",
    step1TodoBody: "Pay a deposit of {amount} NOK via Vipps.",
    step2Title: "Share friend discount",
    step2Body: "Give friends {give}% discount and get {earn}% credit. Find your code on My page.",
    myPage: "My page",
    step3Title: "The pigs are growing",
    step3Body: "The pigs live on the farm through {year} and are slaughtered locally in December.",
    step4Title: "Remainder payment and delivery",
    step4Body: "The remainder is paid at delivery in December {year}.",
    myOrders: "See my orders",
  },

  // Order status timeline
  orderStatusTimeline: {
    created: "Order created",
    deposit: "Deposit paid",
    remainder: "Fully paid",
    locked: "Order locked",
    ready: "Ready for pickup",
    completed: "Completed",
  },

  // Order timeline modal
  orderTimelineModal: {
    title: "Order history",
    orderPrefix: "Order",
    close: "Close",
    orderCreated: "Order created",
    orderCreatedDesc: "Order {orderNumber} was created",
    depositPaid: "Deposit paid",
    depositPending: "Deposit pending",
    orderModified: "Order updated",
    orderModifiedDesc: "The order was updated",
    orderLocked: "Order locked",
    orderLockedDesc: "The order can no longer be changed",
    remainderPaid: "Remainder paid",
    remainderPending: "Remainder pending",
    inProduction: "In production",
    inProductionDesc: "The order is being prepared",
    readyForPickup: "Ready for pickup",
    readyForPickupDesc: "The order is ready",
    delivered: "Delivered",
    deliveredDesc: "The order is complete",
    paymentDeadlinePassed: "Payment deadline passed",
    paymentDeadlinePassedDesc: "Please pay the remainder as soon as possible",
  },

  // Payment history modal
  paymentHistoryModal: {
    title: "Payment history",
    orderPrefix: "Order",
    totalPaid: "Total paid",
    extrasTitle: "Extra products (included in remainder)",
    extrasTotal: "Extras total",
    noPayments: "No payments registered",
    notPaid: "Not paid",
    transactionId: "Transaction ID",
    close: "Close",
    receipt: "Receipt",
    receiptDesc: "Receipt will be sent to your email",
    downloadReceipt: "Download receipt",
    paymentTypeDeposit: "Deposit",
    paymentTypeRemainder: "Remainder",
    statusCompleted: "Paid",
    statusPending: "Pending",
    statusFailed: "Failed",
  },

  // Extras upsell modal
  extrasUpsellModal: {
    removeWarning:
      "You are removing: {items}.\n\nProduction is tight after the cutoff date. You will NOT be able to add these items back. Are you sure?",
    noChanges: "No changes",
    title: "Add extra products",
    subtitle: "Increase your order before you pay the remainder. All prices are added to your remainder amount.",
    noExtrasAvailable: "No extra products are available right now",
    quantity: "Quantity",
    unitPieces: "pcs",
    selectedExtras: "Selected extras:",
    change: "Change",
    addedToRemainder: "This amount is added to your remainder amount",
    cancel: "Cancel",
    updating: "Updating...",
    saving: "Saving...",
    updateExtrasOrder: "Update extras order ({delta})",
  },

  // Order modification modal
  orderModificationModal: {
    title: "Edit order",
    boxSize: "Box size",
    priceFromAdmin: "Price from admin settings",
    ribChoice: "Rib choice",
    deliveryMethod: "Pickup method",
    pickupFarm: "Pickup at farm",
    pickupFarmFee: "No extra cost",
    pickupE6: "Pickup along E6",
    pickupE6Note: "Pickup day arranged",
    trondheimPickup: "Pickup in Trondheim",
    trondheimNote: "Pickup day that week",
    deliveryType: "Delivery type",
    frozenPickup: "Frozen pickup",
    frozenStandard: "Standard pickup",
    freshPickup: "Fresh pickup",
    freshPickupNote: "Pickup at farm week 50/51",
    freshOnlyFarm: "Available only for farm pickup",
    extrasTitle: "Add extra products (optional)",
    extrasWarning:
      'You changed extra products. Changes are saved when you click "Save changes".',
    cancel: "Cancel",
    saveChanges: "Save changes",
    saving: "Saving...",
    noChanges: "No changes made",
    confirmChanges: "Confirm changes",
    confirmDescription: "Are you sure you want to change the order? This may affect the price.",
    confirm: "Confirm",
    saveSuccessTitle: "Changes saved",
    saveSuccessDescription: "Your order has been updated",
    saveErrorTitle: "Error",
    saveErrorDescription: "Could not save changes. Try again.",
    extrasError: "Could not update extra products",
    quantity: "Quantity",
    unitPieces: "pcs",
    ribOptionTynnribbe: "Thin ribs",
    ribOptionFamilieribbe: "Family ribs",
    ribOptionPorchetta: "Porchetta",
    ribOptionButchersChoice: "Butcher's choice",
  },

  // Customer messaging panel
  customerMessagingPanel: {
    loadError: "Could not load messages",
    emptyReplyTitle: "Empty message",
    emptyReplyDescription: "Reply cannot be empty",
    replySentTitle: "Reply sent",
    replySentDescription: "Your reply has been sent",
    errorTitle: "Error",
    sendReplyFailed: "Could not send reply",
    missingInfoTitle: "Missing information",
    missingInfoDescription: "Subject and message are required",
    messageSentTitle: "Message sent",
    messageSentDescription: "Your message was sent to the administrator",
    sendFailedTitle: "Send failed",
    sendFailedDescription: "Could not send message",
    panelTitle: "Send us a message",
    category: "Category",
    subject: "Subject",
    message: "Message",
    subjectPlaceholder: "e.g. Question about order #12345",
    messagePlaceholder: "How can we help you?",
    successMessage: "Message sent!",
    sending: "Sending...",
    sendMessage: "Send message",
    yourMessages: "Your messages",
    loadingMessages: "Loading messages...",
    noMessages: "No messages yet",
    fromYou: "You",
    fromFarm: "Reply from Tinglum Gard",
    replyPlaceholder: "Write a reply...",
    categorySupport: "Support",
    categoryInquiry: "Inquiry",
    categoryComplaint: "Complaint",
    categoryFeedback: "Feedback",
    categoryReferralQuestion: "Friend discount",
    statusOpen: "Open",
    statusInProgress: "In progress",
    statusResolved: "Resolved",
    statusClosed: "Closed",
  },

  // Order details card
  orderDetailsCard: {
    nextActionCompleted: "Order complete",
    nextActionReady: "Ready for pickup - see details below",
    nextActionPaymentDue: "Remainder payment of {currency} {amount} is due",
    nextActionLocked: "Order locked - waiting for remainder payment",
    nextActionWaitingDeposit: "Waiting for deposit payment",
    nextActionProcessing: "Everything looks good - we will keep you updated",
    deliveryTypePickupFarm: "Pickup at farm",
    deliveryTypePickupE6: "Pickup at E6",
    deliveryTypePickupTrondheim: "Pickup in Trondheim",
    ribChoiceTynnribbe: "Thin ribs",
    ribChoiceFamilieribbe: "Family ribs",
    ribChoicePorchetta: "Porchetta",
    ribChoiceButchersChoice: "Butcher's choice",
    updateError: "Failed to update extras",
    updatedTitle: "Updated",
    updatedExtras: "Updated extra products ({count}).",
    errorTitle: "Error",
    addExtrasError: "Could not add extra products. Try again.",
    saveModificationsError: "Could not save changes",
    reorderConfirm: "Do you want to order the same box again?",
    reorderFailed: "Could not create new order. Try again.",
    reorderCreatedTitle: "New order created",
    reorderCreatedDescription: "Order number: {orderNumber}",
    estimatedReadyNow: "Ready now!",
    estimatedWeekRange: "Week 47-48, 2026",
    payRemainder: "Pay remainder",
    dueDate: "Due date",
    earlyPaymentHint:
      "The earlier you pay the remainder, the better your chance for extra products.",
    statusPaymentRemaining: "Payment remaining",
    statusPaid: "Paid",
    statusDelivered: "Delivered",
    statusCompleted: "Completed",
    statusWaitingDeposit: "Waiting for deposit",
    locked: "Locked",
    ordered: "Ordered",
    downloadReceipt: "Download receipt",
    print: "Print",
    paymentSummary: "Payment summary",
    depositBoxLabel: "Deposit ({size}kg box)",
    boxRemainder: "Box remainder",
    extraProducts: "Extra products",
    remainderTotal: "Remainder total",
    remainderDueDate: "Remainder due date",
    total: "Total",
    orderContents: "Order contents",
    porkBoxLabel: "{size}kg pork box",
    ribChoice: "Rib choice",
    freshDeliveryAddon: "Fresh delivery (+{currency} 200)",
    addExtraProducts: "Add extra products",
    deliveryInfo: "Pickup/delivery information",
    type: "Type",
    farmName: "Tinglum Gard",
    addressByEmail: "Address is sent by email when the order is ready",
    whatToBring: "What to bring:",
    bringCooler: "Cooler bag or cooler box",
    yourNotes: "Your notes:",
    orderActions: "Order actions",
    paymentHistory: "Payment history",
    orderHistory: "Order history",
    contactUs: "Contact us",
    estimatedDeliveryDate: "Estimated delivery date",
    notifyReady: "We will notify you when the order is ready for pickup",
    canStillEdit: "You can still edit your order",
    changesBeforeLock: "Changes must be made before lock time",
    editOrder: "Edit order",
    orderLocked: "Order is locked",
    noMoreChanges: "- no more changes possible",
    happyWithOrder: "Happy with your order?",
    creatingOrder: "Creating order...",
    orderAgain: "Order again",
    reorderSameContents: "Create a new order with the same contents",
    contactDetailsBoxSize: "Box size",
    contactDetailsRibChoice: "Rib choice",
    contactDetailsDeliveryType: "Delivery type",
    contactDetailsStatus: "Status",
    contactDetailsTotalAmount: "Total amount",
    contactEmail: "post@tinglum.no",
    contactPhone: "+47 123 45 678",
  },

  // Remainder payment page
  remainderPaymentPage: {
    fetchOrderError: "Could not fetch order",
    unknownError: "Unknown error",
    backToMyPage: "Back to My page",
    updatedTitle: "Updated",
    soldOutRemovedWithCredit: "Sold-out products removed and credit added.",
    soldOutRemoved: "Sold-out products removed from the order.",
    couldNotUpdate: "Could not update",
    tryAgain: "Try again.",
    missingOrderId: "Missing order ID",
    updateExtrasError: "Could not update extra products",
    updateDeliveryError: "Could not update delivery details",
    changesSaved: "Changes saved",
    startingPayment: "Starting payment...",
    startPaymentError: "Could not start payment (status {status})",
    paymentErrorTitle: "Payment error",
    paymentErrorDescription: "Could not start payment. Try again.",
    soldOutTitle: "Sorry, some extra products are sold out",
    soldOutBody:
      "We do not have enough stock for all extra products chosen at deposit time. You can remove the products or take 110% credit to use on other extras. Unused credit is not refundable.",
    ordered: "Ordered",
    available: "Available",
    removeSoldOut: "Remove sold-out products",
    takeCredit110: "Take 110% credit",
    payRemainderTitle: "Pay remainder",
    orderLabel: "Order",
    dueDate: "Due date",
    earlyPaymentHint:
      "The earlier you pay the remainder, the better your chance of getting extra products.",
    back: "Back",
    extrasTitle: "Extra products (optional)",
    extrasSubtitle:
      "Add extra products before you pay. The price is added to your remainder.",
    quantity: "Quantity",
    unitPieces: "pcs",
    unitKg: "kg",
    youAdd: "You add",
    youReduce: "You reduce the order by",
    toOriginalOrder: "to the original order",
    unsavedChangesWarning:
      'You have unsaved changes. They will be saved when you click "Pay with Vipps".',
    soldOutCreditTitle: "Credit for sold-out products",
    soldOutCreditNote:
      "Credit can be used for extra products and is not refundable.",
    pickupDeliveryTitle: "Pickup and delivery",
    deliveryMethod: "Delivery method",
    pickupFarm: "Pickup at farm",
    pickupFarmLocation: "Tinglum Farm, Sjofossen",
    free: "Free",
    pickupE6: "Pickup at E6",
    pickupE6Point: "Pickup point at E6",
    deliveryTrondheim: "Delivery in Trondheim",
    deliveryAddress: "Delivery to your address",
    extraOption: "Extra option",
    freshDelivery: "Fresh delivery",
    freshDeliveryDescription: "Products are delivered fresh (not frozen)",
    forDeliveryChange: "for delivery change",
    saveOnDeliveryChange: "on delivery change",
    deliveryChangesWarning:
      'You changed delivery details. They will be saved when you click "Pay with Vipps".',
    paymentSummary: "Payment summary",
    depositPaid: "Deposit (paid)",
    boxRemainder: "Box remainder",
    extraProducts: "Extra products",
    extraProductsCredit: "Extra products credit",
    deliveryChange: "Delivery change",
    payNow: "Pay now",
    savingExtras: "Saving extra products...",
    payWithVipps: "Pay {currency} {amount} with Vipps",
  },
};


