export const cutDiagramContent = {
  no: {
    copy: {
      title: 'Oppdelingsguide - Gris',
      subtitle: 'Klikk på delene av grisen for å se informasjon om kuttet og hvilke produkter du får i pakken din.',
      inPackage: 'I pakken',
      usage: 'Bruk',
      noProductsInRegion: 'Ingen spesifikke produkter fra denne delen i våre pakker',
      clickPrompt: 'Klikk på en del av grisen for å se produkter',
      choosePackageSize: 'Velg pakkestørrelse',
      persons8: '2-3 personer',
      persons12: '4-6 personer',
      approx: 'Ca.',
      meatWord: 'kjøtt',
      package8: '8 kg pakke',
      package12: '12 kg pakke',
      packageLead8: 'Perfekt for 2-3 personer',
      packageLead12: 'Ideell for 4-6 personer',
      tableProduct: 'Produkt',
      tableDescription: 'Beskrivelse',
      tableUsage: 'Bruksområde',
      tableAmount: 'Mengde',
      totalMeatInPackage: 'Totalt kjøtt i pakken',
      extrasTitle: 'Tilleggsbestillinger',
      extrasSubtitle: 'Produkter som kan bestilles ekstra utover standardpakken',
      extraBadge: 'Ekstra',
      wantMoreTitle: 'Vil du ha mer av noe spesielt?',
      wantMoreBody:
        'Kontakt oss for å bestille ekstra kutt eller spesialiteter i tillegg til standardpakken. Vi kan også tilpasse innholdet etter dine ønsker.',
    },
    products: [
      { id: 'ribbe', name: 'Ribbe', part: 'buk', kg8Box: 2.5, kg12Box: 4, description: 'Norsk juleribbe med god fettbalanse', usage: 'Steke, rull', category: 'main' },
      { id: 'nakkekoteletter', name: 'Nakkekoteletter', part: 'nakke', kg8Box: 1.5, kg12Box: 2.5, description: 'Saftige koteletter med naturlig fettmarmorering', usage: 'Steke, grille', category: 'main' },
      { id: 'bacon', name: 'Bacon/Sideflesk', part: 'buk', kg8Box: 1, kg12Box: 1.5, description: 'Bacon og stekeflesk', usage: 'Steke', category: 'main' },
      { id: 'skinkesteik', name: 'Skinkesteik', part: 'skinke', kg8Box: 2, kg12Box: 3.5, description: 'Mør steik fra låret', usage: 'Steke, gryte', category: 'main' },
      { id: 'polse', name: 'Grillpølse', part: 'diverse', kg8Box: 1, kg12Box: 1.5, description: 'Hjemmelaget pølse', usage: 'Grille', category: 'main' },
      { id: 'bogstykke', name: 'Bogstykke', part: 'bog', kg8Box: 0, kg12Box: 0, description: 'Perfekt til pulled pork og gryter', usage: 'Langtidsstekt, gryte', category: 'extra' },
      { id: 'ryggkoteletter', name: 'Ryggkoteletter', part: 'kam', kg8Box: 0, kg12Box: 0, description: 'Møre koteletter fra ryggen', usage: 'Steke, grille', category: 'extra' },
      { id: 'indrefilet', name: 'Indrefilet', part: 'kam', kg8Box: 0, kg12Box: 0, description: 'Det møreste kjøttet', usage: 'Medaljonger', category: 'extra' },
    ],
    cutRegions: [
      {
        id: 'hode',
        name: 'Hode',
        label: 'HODE',
        path: 'M 50 140 Q 40 130 40 115 Q 40 95 50 85 Q 55 80 65 78 L 85 80 L 90 110 L 85 145 L 70 148 Z',
        products: [],
        textX: 65,
        textY: 120,
        textRotation: -15,
      },
      {
        id: 'nakke',
        name: 'Nakke',
        label: 'NAKKE',
        path: 'M 85 80 L 140 75 L 145 148 L 90 150 Z',
        products: ['nakkekoteletter'],
        textX: 112,
        textY: 110,
        textRotation: -5,
      },
      {
        id: 'bog',
        name: 'Bog',
        label: 'BOG',
        path: 'M 90 150 L 145 148 L 155 220 L 100 225 Z',
        products: ['bogstykke'],
        textX: 122,
        textY: 185,
      },
      {
        id: 'kam',
        name: 'Kam',
        label: 'KAM',
        path: 'M 140 75 L 350 70 L 355 125 L 145 130 Z',
        products: ['ryggkoteletter', 'indrefilet'],
        textX: 247,
        textY: 100,
      },
      {
        id: 'buk',
        name: 'Buk',
        label: 'BUK',
        path: 'M 145 130 L 355 125 L 365 220 L 155 225 Z',
        products: ['ribbe', 'bacon'],
        textX: 260,
        textY: 172,
      },
      {
        id: 'skinke',
        name: 'Skinke',
        label: 'SKINKE',
        path: 'M 350 70 L 450 75 Q 475 85 475 110 Q 475 140 470 165 L 455 190 L 365 195 L 355 125 Z',
        products: ['skinkesteik'],
        textX: 410,
        textY: 130,
      },
    ],
  },
  en: {
    copy: {
      title: 'Butcher Guide - Pig',
      subtitle: 'Click pig sections to view each cut and what products are included in your package.',
      inPackage: 'In package',
      usage: 'Use',
      noProductsInRegion: 'No specific products from this region in our packages',
      clickPrompt: 'Click a part of the pig to see products',
      choosePackageSize: 'Choose package size',
      persons8: '2-3 people',
      persons12: '4-6 people',
      approx: 'Approx.',
      meatWord: 'meat',
      package8: '8 kg package',
      package12: '12 kg package',
      packageLead8: 'Perfect for 2-3 people',
      packageLead12: 'Ideal for 4-6 people',
      tableProduct: 'Product',
      tableDescription: 'Description',
      tableUsage: 'Usage',
      tableAmount: 'Amount',
      totalMeatInPackage: 'Total meat in package',
      extrasTitle: 'Extra Orders',
      extrasSubtitle: 'Products that can be ordered in addition to the standard package',
      extraBadge: 'Extra',
      wantMoreTitle: 'Want more of something specific?',
      wantMoreBody:
        'Contact us to order extra cuts or specialties in addition to the standard package. We can also tailor content to your preferences.',
    },
    products: [
      { id: 'ribbe', name: 'Ribs', part: 'belly', kg8Box: 2.5, kg12Box: 4, description: 'Classic pork ribs with balanced fat', usage: 'Roast, roll', category: 'main' },
      { id: 'nakkekoteletter', name: 'Neck chops', part: 'neck', kg8Box: 1.5, kg12Box: 2.5, description: 'Juicy chops with natural marbling', usage: 'Pan-fry, grill', category: 'main' },
      { id: 'bacon', name: 'Bacon/Belly', part: 'belly', kg8Box: 1, kg12Box: 1.5, description: 'Bacon and pork belly cuts', usage: 'Pan-fry', category: 'main' },
      { id: 'skinkesteik', name: 'Ham roast', part: 'ham', kg8Box: 2, kg12Box: 3.5, description: 'Tender roast from the leg', usage: 'Roast, stew', category: 'main' },
      { id: 'polse', name: 'Sausage', part: 'misc', kg8Box: 1, kg12Box: 1.5, description: 'Farm-style sausage', usage: 'Grill', category: 'main' },
      { id: 'bogstykke', name: 'Shoulder cut', part: 'shoulder', kg8Box: 0, kg12Box: 0, description: 'Perfect for pulled pork and stews', usage: 'Slow roast, stew', category: 'extra' },
      { id: 'ryggkoteletter', name: 'Loin chops', part: 'loin', kg8Box: 0, kg12Box: 0, description: 'Tender chops from the back', usage: 'Pan-fry, grill', category: 'extra' },
      { id: 'indrefilet', name: 'Tenderloin', part: 'loin', kg8Box: 0, kg12Box: 0, description: 'The most tender cut', usage: 'Medallions', category: 'extra' },
    ],
    cutRegions: [
      {
        id: 'head',
        name: 'Head',
        label: 'HEAD',
        path: 'M 50 140 Q 40 130 40 115 Q 40 95 50 85 Q 55 80 65 78 L 85 80 L 90 110 L 85 145 L 70 148 Z',
        products: [],
        textX: 65,
        textY: 120,
        textRotation: -15,
      },
      {
        id: 'neck',
        name: 'Neck',
        label: 'NECK',
        path: 'M 85 80 L 140 75 L 145 148 L 90 150 Z',
        products: ['nakkekoteletter'],
        textX: 112,
        textY: 110,
        textRotation: -5,
      },
      {
        id: 'shoulder',
        name: 'Shoulder',
        label: 'SHOULDER',
        path: 'M 90 150 L 145 148 L 155 220 L 100 225 Z',
        products: ['bogstykke'],
        textX: 122,
        textY: 185,
      },
      {
        id: 'loin',
        name: 'Loin',
        label: 'LOIN',
        path: 'M 140 75 L 350 70 L 355 125 L 145 130 Z',
        products: ['ryggkoteletter', 'indrefilet'],
        textX: 247,
        textY: 100,
      },
      {
        id: 'belly',
        name: 'Belly',
        label: 'BELLY',
        path: 'M 145 130 L 355 125 L 365 220 L 155 225 Z',
        products: ['ribbe', 'bacon'],
        textX: 260,
        textY: 172,
      },
      {
        id: 'ham',
        name: 'Ham',
        label: 'HAM',
        path: 'M 350 70 L 450 75 Q 475 85 475 110 Q 475 140 470 165 L 455 190 L 365 195 L 355 125 Z',
        products: ['skinkesteik'],
        textX: 410,
        textY: 130,
      },
    ],
  },
} as const;
