import {
  AdminActivity,
  AdminAlert,
  AdminCustomer,
  AdminInventoryItem,
  AdminOrder,
  AdminPayment,
  AdminProduct,
  AdminScheduleWindow,
} from './admin-types'
import { getMondayOfWeek } from './utils'

const week12 = getMondayOfWeek(2026, 12)
const week13 = getMondayOfWeek(2026, 13)
const week14 = getMondayOfWeek(2026, 14)
const week15 = getMondayOfWeek(2026, 15)
const week16 = getMondayOfWeek(2026, 16)
const week48 = getMondayOfWeek(2026, 48)

export const adminAlerts: AdminAlert[] = [
  {
    id: 'alert-1',
    productType: 'eggs',
    level: 'warning',
    message: '3 orders with remainder due in 2 days',
    href: '/admin/orders',
  },
  {
    id: 'alert-2',
    productType: 'eggs',
    level: 'critical',
    message: 'Week 14 Ayam Cemani has only 4 eggs left',
    href: '/admin/schedule',
  },
  {
    id: 'alert-3',
    productType: 'eggs',
    level: 'warning',
    message: '1 forfeiture pending inventory release',
    href: '/admin/activity',
  },
  {
    id: 'alert-4',
    productType: 'pig_box',
    level: 'warning',
    message: 'Slaughter week 48 has only 3 boxes remaining',
    href: '/admin/schedule',
  },
]

export const adminScheduleWindows: AdminScheduleWindow[] = [
  {
    id: 'window-12',
    year: 2026,
    weekNumber: 12,
    startDate: week12,
    entries: [
      {
        id: 'w12-eggs-ayam',
        productType: 'eggs',
        productName: 'Ayam Cemani',
        unitLabel: 'eggs',
        capacity: 50,
        allocated: 32,
        status: 'open',
        accentColor: '#1F2937',
      },
      {
        id: 'w12-eggs-jersey',
        productType: 'eggs',
        productName: 'Jersey Giant',
        unitLabel: 'eggs',
        capacity: 48,
        allocated: 48,
        status: 'sold_out',
        accentColor: '#0F172A',
      },
      {
        id: 'w12-eggs-silverudd',
        productType: 'eggs',
        productName: "Silverudd's",
        unitLabel: 'eggs',
        capacity: 40,
        allocated: 12,
        status: 'open',
        accentColor: '#334155',
      },
      {
        id: 'w12-eggs-legbar',
        productType: 'eggs',
        productName: 'Cream Legbar',
        unitLabel: 'eggs',
        capacity: 60,
        allocated: 0,
        status: 'closed',
        accentColor: '#475569',
      },
    ],
  },
  {
    id: 'window-13',
    year: 2026,
    weekNumber: 13,
    startDate: week13,
    entries: [
      {
        id: 'w13-eggs-ayam',
        productType: 'eggs',
        productName: 'Ayam Cemani',
        unitLabel: 'eggs',
        capacity: 50,
        allocated: 18,
        status: 'open',
        accentColor: '#111827',
      },
      {
        id: 'w13-eggs-jersey',
        productType: 'eggs',
        productName: 'Jersey Giant',
        unitLabel: 'eggs',
        capacity: 48,
        allocated: 8,
        status: 'open',
        accentColor: '#1F2937',
      },
      {
        id: 'w13-eggs-silverudd',
        productType: 'eggs',
        productName: "Silverudd's",
        unitLabel: 'eggs',
        capacity: 40,
        allocated: 28,
        status: 'open',
        accentColor: '#475569',
      },
      {
        id: 'w13-eggs-legbar',
        productType: 'eggs',
        productName: 'Cream Legbar',
        unitLabel: 'eggs',
        capacity: 60,
        allocated: 0,
        status: 'closed',
        accentColor: '#64748B',
      },
    ],
  },
  {
    id: 'window-14',
    year: 2026,
    weekNumber: 14,
    startDate: week14,
    entries: [
      {
        id: 'w14-eggs-ayam',
        productType: 'eggs',
        productName: 'Ayam Cemani',
        unitLabel: 'eggs',
        capacity: 50,
        allocated: 46,
        status: 'open',
        accentColor: '#111827',
      },
      {
        id: 'w14-eggs-jersey',
        productType: 'eggs',
        productName: 'Jersey Giant',
        unitLabel: 'eggs',
        capacity: 48,
        allocated: 41,
        status: 'open',
        accentColor: '#1F2937',
      },
      {
        id: 'w14-eggs-silverudd',
        productType: 'eggs',
        productName: "Silverudd's",
        unitLabel: 'eggs',
        capacity: 40,
        allocated: 36,
        status: 'open',
        accentColor: '#475569',
      },
      {
        id: 'w14-eggs-legbar',
        productType: 'eggs',
        productName: 'Cream Legbar',
        unitLabel: 'eggs',
        capacity: 60,
        allocated: 0,
        status: 'closed',
        accentColor: '#64748B',
      },
    ],
  },
  {
    id: 'window-15',
    year: 2026,
    weekNumber: 15,
    startDate: week15,
    entries: [
      {
        id: 'w15-eggs-ayam',
        productType: 'eggs',
        productName: 'Ayam Cemani',
        unitLabel: 'eggs',
        capacity: 52,
        allocated: 24,
        status: 'open',
        accentColor: '#111827',
      },
      {
        id: 'w15-eggs-jersey',
        productType: 'eggs',
        productName: 'Jersey Giant',
        unitLabel: 'eggs',
        capacity: 48,
        allocated: 12,
        status: 'open',
        accentColor: '#1F2937',
      },
      {
        id: 'w15-eggs-silverudd',
        productType: 'eggs',
        productName: "Silverudd's",
        unitLabel: 'eggs',
        capacity: 40,
        allocated: 16,
        status: 'open',
        accentColor: '#475569',
      },
      {
        id: 'w15-eggs-legbar',
        productType: 'eggs',
        productName: 'Cream Legbar',
        unitLabel: 'eggs',
        capacity: 60,
        allocated: 6,
        status: 'open',
        accentColor: '#64748B',
      },
    ],
  },
  {
    id: 'window-16',
    year: 2026,
    weekNumber: 16,
    startDate: week16,
    entries: [
      {
        id: 'w16-eggs-ayam',
        productType: 'eggs',
        productName: 'Ayam Cemani',
        unitLabel: 'eggs',
        capacity: 52,
        allocated: 18,
        status: 'open',
        accentColor: '#111827',
      },
      {
        id: 'w16-eggs-jersey',
        productType: 'eggs',
        productName: 'Jersey Giant',
        unitLabel: 'eggs',
        capacity: 48,
        allocated: 10,
        status: 'open',
        accentColor: '#1F2937',
      },
      {
        id: 'w16-eggs-silverudd',
        productType: 'eggs',
        productName: "Silverudd's",
        unitLabel: 'eggs',
        capacity: 40,
        allocated: 9,
        status: 'open',
        accentColor: '#475569',
      },
      {
        id: 'w16-eggs-legbar',
        productType: 'eggs',
        productName: 'Cream Legbar',
        unitLabel: 'eggs',
        capacity: 60,
        allocated: 0,
        status: 'closed',
        accentColor: '#64748B',
      },
      {
        id: 'w16-pig-ullgris',
        productType: 'pig_box',
        productName: 'Ullgris',
        unitLabel: 'boxes',
        capacity: 10,
        allocated: 7,
        status: 'open',
      },
    ],
  },
  {
    id: 'window-48',
    year: 2026,
    weekNumber: 48,
    startDate: week48,
    entries: [
      {
        id: 'w48-pig-ullgris',
        productType: 'pig_box',
        productName: 'Ullgris',
        unitLabel: 'boxes',
        capacity: 10,
        allocated: 7,
        status: 'open',
      },
      {
        id: 'w48-eggs-ayam',
        productType: 'eggs',
        productName: 'Ayam Cemani',
        unitLabel: 'eggs',
        capacity: 50,
        allocated: 32,
        status: 'open',
        accentColor: '#111827',
      },
      {
        id: 'w48-eggs-legbar',
        productType: 'eggs',
        productName: 'Cream Legbar',
        unitLabel: 'eggs',
        capacity: 60,
        allocated: 18,
        status: 'open',
        accentColor: '#64748B',
      },
    ],
  },
]

export const adminOrders: AdminOrder[] = [
  {
    id: 'ORD-2026-041',
    orderNumber: 'ORD-2026-041',
    productType: 'eggs',
    productName: 'Ayam Cemani',
    windowLabel: 'Week 13',
    windowDate: week13,
    quantity: 6,
    unitLabel: 'eggs',
    deliveryMethod: 'Posten',
    status: 'deposit_paid',
    depositStatus: 'paid',
    remainderDueDate: new Date(2026, 2, 23),
    remainderDueInDays: 3,
    deliveryDate: week13,
    customerName: 'Kari Lund',
    customerEmail: 'kari@example.com',
  },
  {
    id: 'ORD-2026-045',
    orderNumber: 'ORD-2026-045',
    productType: 'eggs',
    productName: 'Jersey Giant',
    windowLabel: 'Week 13',
    windowDate: week13,
    quantity: 8,
    unitLabel: 'eggs',
    deliveryMethod: 'Farm pickup',
    status: 'fully_paid',
    depositStatus: 'paid',
    remainderDueDate: null,
    remainderDueInDays: null,
    deliveryDate: week13,
    customerName: 'Jonas Rekkedal',
    customerEmail: 'jonas@example.com',
  },
  {
    id: 'ORD-2026-052',
    orderNumber: 'ORD-2026-052',
    productType: 'eggs',
    productName: "Silverudd's",
    windowLabel: 'Week 14',
    windowDate: week14,
    quantity: 12,
    unitLabel: 'eggs',
    deliveryMethod: 'Posten',
    status: 'deposit_paid',
    depositStatus: 'paid',
    remainderDueDate: new Date(2026, 2, 29),
    remainderDueInDays: 2,
    deliveryDate: week14,
    customerName: 'Ragnhild Ottesen',
    customerEmail: 'ragnhild@example.com',
  },
  {
    id: 'ORD-2026-118',
    orderNumber: 'ORD-2026-118',
    productType: 'pig_box',
    productName: 'Ullgris',
    windowLabel: 'Slaughter week 48',
    windowDate: week48,
    quantity: 1,
    unitLabel: 'boxes',
    deliveryMethod: 'Farm pickup',
    status: 'deposit_paid',
    depositStatus: 'paid',
    remainderDueDate: new Date(2026, 10, 20),
    remainderDueInDays: 4,
    deliveryDate: week48,
    customerName: 'Sindre Holmen',
    customerEmail: 'sindre@example.com',
  },
]

export const adminProducts: AdminProduct[] = [
  {
    id: 'prod-eggs-ayam',
    productType: 'eggs',
    name: 'Ayam Cemani',
    status: 'active',
    pricePerUnit: 80,
    unitLabel: 'kr / egg',
    minOrder: 6,
    maxOrder: 24,
    accentColor: '#111827',
    seasonStartWeek: 10,
    seasonEndWeek: 20,
    notes: 'High demand. Keep buffer stock.',
  },
  {
    id: 'prod-eggs-legbar',
    productType: 'eggs',
    name: 'Cream Legbar',
    status: 'active',
    pricePerUnit: 65,
    unitLabel: 'kr / egg',
    minOrder: 6,
    maxOrder: 30,
    accentColor: '#64748B',
    seasonStartWeek: 10,
    seasonEndWeek: 22,
    notes: 'Color variations expected.',
  },
  {
    id: 'prod-pig-ullgris',
    productType: 'pig_box',
    name: 'Ullgris 2026',
    status: 'active',
    pricePerUnit: 4200,
    unitLabel: 'kr / box',
    minOrder: 1,
    maxOrder: 2,
    seasonStartWeek: 46,
    seasonEndWeek: 49,
    notes: 'Slaughter week based.',
  },
]

export const adminInventory: AdminInventoryItem[] = [
  {
    id: 'inv-eggs-ayam-w13',
    productType: 'eggs',
    productName: 'Ayam Cemani',
    windowLabel: 'Week 13',
    windowDate: week13,
    capacity: 50,
    allocated: 32,
    remaining: 18,
    status: 'open',
  },
  {
    id: 'inv-eggs-legbar-w14',
    productType: 'eggs',
    productName: 'Cream Legbar',
    windowLabel: 'Week 14',
    windowDate: week14,
    capacity: 60,
    allocated: 18,
    remaining: 42,
    status: 'open',
  },
  {
    id: 'inv-pig-ullgris-w48',
    productType: 'pig_box',
    productName: 'Ullgris',
    windowLabel: 'Week 48',
    windowDate: week48,
    capacity: 10,
    allocated: 7,
    remaining: 3,
    status: 'open',
  },
]

export const adminPayments: AdminPayment[] = [
  {
    id: 'pay-041-deposit',
    orderNumber: 'ORD-2026-041',
    productType: 'eggs',
    paymentType: 'deposit',
    amount: 390,
    status: 'captured',
    provider: 'Vipps',
    createdAt: new Date(2026, 2, 14, 9, 32),
    isTest: false,
    payloadPreview: '{ "event": "payment.captured", "order": "ORD-2026-041" }',
  },
  {
    id: 'pay-052-deposit',
    orderNumber: 'ORD-2026-052',
    productType: 'eggs',
    paymentType: 'deposit',
    amount: 780,
    status: 'captured',
    provider: 'Vipps',
    createdAt: new Date(2026, 2, 15, 10, 12),
    isTest: false,
    payloadPreview: '{ "event": "payment.captured", "order": "ORD-2026-052" }',
  },
  {
    id: 'pay-118-deposit',
    orderNumber: 'ORD-2026-118',
    productType: 'pig_box',
    paymentType: 'deposit',
    amount: 1200,
    status: 'captured',
    provider: 'Vipps',
    createdAt: new Date(2026, 10, 14, 12, 18),
    isTest: true,
    payloadPreview: '{ "event": "payment.captured", "order": "ORD-2026-118" }',
  },
]

export const adminCustomers: AdminCustomer[] = [
  {
    id: 'cust-1',
    name: 'Kari Lund',
    email: 'kari@example.com',
    phone: '+47 900 00 111',
    ordersCount: 3,
    lastOrderDate: week13,
    status: 'active',
  },
  {
    id: 'cust-2',
    name: 'Jonas Rekkedal',
    email: 'jonas@example.com',
    phone: '+47 900 00 112',
    ordersCount: 1,
    lastOrderDate: week13,
    status: 'active',
  },
  {
    id: 'cust-3',
    name: 'Sindre Holmen',
    email: 'sindre@example.com',
    phone: '+47 900 00 113',
    ordersCount: 1,
    lastOrderDate: week48,
    status: 'active',
  },
]

export const adminActivity: AdminActivity[] = [
  {
    id: 'act-1',
    productType: 'eggs',
    timestamp: new Date(2026, 2, 10, 14, 22),
    adminName: 'kenneth',
    action: 'update_capacity',
    entity: 'weekly_inventory',
    summary: 'Ayam Cemani - Week 13',
    changes: 'capacity: 40 -> 50',
    reason: 'Higher fertility this week',
  },
  {
    id: 'act-2',
    productType: 'eggs',
    timestamp: new Date(2026, 2, 11, 9, 8),
    adminName: 'kenneth',
    action: 'close_window',
    entity: 'weekly_inventory',
    summary: 'Cream Legbar - Week 12',
    changes: 'status: open -> closed',
    reason: 'No eggs available this week',
  },
  {
    id: 'act-3',
    productType: 'eggs',
    timestamp: new Date(2026, 2, 12, 16, 41),
    adminName: 'kenneth',
    action: 'force_forfeit',
    entity: 'order',
    summary: 'ORD-2026-030',
    changes: 'status: deposit_paid -> cancelled',
    reason: 'No payment received by deadline',
  },
  {
    id: 'act-4',
    productType: 'pig_box',
    timestamp: new Date(2026, 10, 1, 11, 14),
    adminName: 'kenneth',
    action: 'open_window',
    entity: 'inventory_window',
    summary: 'Ullgris - Week 48',
    changes: 'status: closed -> open',
    reason: 'Demand confirmed',
  },
]
