import { NextRequest } from 'next/server'
import { getLiveEvent,listLiveParticipants,saveLiveEvent,LiveEvent } from '@/lib/quest/live-store'
import { QuestApiError,questError,requireQuestAdmin } from '@/lib/quest/server'
import { supabaseAdmin } from '@/lib/supabase/server'
import { randomUUID } from 'crypto'
export async function GET(){try{await requireQuestAdmin();const activeEvent=await getLiveEvent();const rows=activeEvent?(await listLiveParticipants()).filter(p=>p.event_id===activeEvent.id):[];const participants=await Promise.all(rows.map(async p=>{const {data}=await supabaseAdmin.auth.admin.getUserById(p.user_id);return{id:p.id,display_name:p.display_name,email:data.user?.email||null,answers:p.answers,answered_count:Object.keys(p.answers).length,current_question:Math.min(25,Object.keys(p.answers).length+1),earned_points:Object.values(p.answers).reduce((sum,key)=>sum+'ABCDE'.indexOf(key),0),section_scores:[0,1,2,3,4].map(i=>Object.entries(p.answers).filter(([id])=>Math.ceil(Number(id.slice(1))/5)-1===i).reduce((sum,[,key])=>sum+'ABCDE'.indexOf(key),0)),last_seen_at:p.last_seen_at,submitted_at:p.submitted_at,feedback:p.feedback||null}}));
  const aggregates=[0,1,2,3,4].map(section=>{const sectionAnswers=rows.flatMap(p=>Object.entries(p.answers).filter(([id])=>Math.ceil(Number(id.slice(1))/5)-1===section).map(([,key])=>'ABCDE'.indexOf(key))).filter(score=>score>=0);const participantCount=rows.filter(p=>Object.keys(p.answers).some(id=>Math.ceil(Number(id.slice(1))/5)-1===section)).length;const projectedAverage=sectionAnswers.length?(sectionAnswers.reduce((sum,score)=>sum+score,0)/sectionAnswers.length)*5:0;return{section:section+1,average:Number(projectedAverage.toFixed(1)),responses:sectionAnswers.length,participants:participantCount}});
  const allAnswers=rows.flatMap(p=>Object.values(p.answers));const answerDistribution='ABCDE'.split('').map((answer,score)=>{const count=allAnswers.filter(value=>value===answer).length;return{answer,score,count,percent:allAnswers.length?Math.round(count/allAnswers.length*100):0}});
  return Response.json({events:activeEvent?[activeEvent]:[],activeEvent,participants,aggregates,answerDistribution,totalAnswers:allAnswers.length})}catch(error){return questError(error)}}
export async function POST(request:NextRequest){try{await requireQuestAdmin();const body=await request.json();const action=String(body.action||'');let event=await getLiveEvent();const now=new Date().toISOString();if(action==='create'){const name=String(body.name||'').trim().slice(0,100);const code=String(body.joinCode||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12);if(!name||code.length<4)throw new QuestApiError('Enter an event name and a code of at least four characters');event={id:randomUUID(),name,join_code_label:code,status:'paused',released_section:0,results_released:false,created_at:now,updated_at:now};await saveLiveEvent(event);return Response.json({event})}if(!event)throw new QuestApiError('Create a session first');if(action==='start-first'){if(event.released_section!==0)throw new QuestApiError('Part 1 has already been started');event.status='active';event.released_section=1}else if(action==='release-next'){if(event.status!=='active'||event.released_section>=5)throw new QuestApiError('The next section cannot be released');event.released_section+=1}else if(action==='status'){if(!['active','paused','ended'].includes(body.status))throw new QuestApiError('Invalid event status');event.status=body.status}else if(action==='release-results'){if(event.released_section!==5)throw new QuestApiError('Release all five sections first');event.results_released=true}else throw new QuestApiError('Unknown admin action');event.updated_at=now;await saveLiveEvent(event);return Response.json({event})}catch(error){return questError(error)}}
