/**
 * Imports Todoist CSV exports into TodoTwo.
 *
 * Dry run by default — it prints what it would do and every difference it found
 * between the weekday copies of a routine. Pass --apply to write.
 *
 *   npm run todotwo:import -- "C:/Users/kenne/Downloads"
 *   npm run todotwo:import -- "C:/Users/kenne/Downloads" --apply
 *
 * People are not imported. AUTHOR and RESPONSIBLE are dropped and reminder rows
 * skipped: the development database holds synthetic data only (rule R5a), and
 * assignment is rebuilt in Phase 3 once Workawayers have accounts.
 */
import fs from 'node:fs'
import path from 'node:path'
import dotenv from 'dotenv'
import { createClient } from '@supabase/supabase-js'

import { parseCsv } from '../../lib/todotwo/domain/csv'
import { buildImportPlan, type ImportPlan, type ImportTask } from '../../lib/todotwo/domain/todoist-import'

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

const PRODUCTION_REFS = new Set(['ryqjwtzgkrrpxpdqgkbn'])

function fail(message: string): never {
  console.error(`\n  ${message}\n`)
  process.exit(1)
}

const args = process.argv.slice(2)
const apply = args.includes('--apply')
const dir = args.find((a) => !a.startsWith('--'))

if (!dir) fail('Usage: npm run todotwo:import -- <directory with the CSV exports> [--apply]')
if (!fs.existsSync(dir)) fail(`Not a directory: ${dir}`)

const files = fs
  .readdirSync(dir)
  .filter((f) => f.toLowerCase().endsWith('.csv'))
  .sort()

if (files.length === 0) fail(`No .csv files in ${dir}`)

const plans: ImportPlan[] = files.map((file) => {
  const text = fs.readFileSync(path.join(dir, file), 'utf8')
  return buildImportPlan(parseCsv(text), file)
})

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------

console.log(`\n  ${apply ? 'IMPORTING' : 'DRY RUN'} — ${files.length} file(s) from ${dir}\n`)

let totalBefore = 0
let totalAfter = 0

for (const plan of plans) {
  const { project, stats } = plan
  totalBefore += stats.tasksBeforeCollapse
  totalAfter += stats.tasksAfterCollapse

  console.log(`  ${project.name}`)
  console.log(`    sections            ${project.sections.length}`)
  console.log(`    tasks in export     ${stats.tasksBeforeCollapse}`)
  console.log(`    after collapsing    ${stats.tasksAfterCollapse}`)
  console.log(`    reminders skipped   ${stats.remindersSkipped}`)

  const series = countSeries(project.sections.flatMap((s) => s.tasks).concat(project.looseTasks))
  console.log(`    recurring routines  ${series}`)
  console.log()
}

console.log(`  TOTAL  ${totalBefore} tasks in Todoist  ->  ${totalAfter} in TodoTwo\n`)

const allDrift = plans.flatMap((p) => p.drift)
if (allDrift.length > 0) {
  console.log(`  ${allDrift.length} difference(s) found between the weekday copies:\n`)
  for (const note of allDrift) {
    console.log(`    [${note.kind}] ${note.project} / ${note.section} / ${note.title}`)
    console.log(`      ${note.detail}`)
  }
  console.log()

  const reportPath = path.resolve(process.cwd(), 'docs/todotwo/IMPORT-DRIFT.md')
  fs.mkdirSync(path.dirname(reportPath), { recursive: true })
  fs.writeFileSync(
    reportPath,
    [
      '# Todoist import — differences found',
      '',
      'Generated by `npm run todotwo:import`. Each entry is a place where the weekday',
      'copies of one routine disagreed. The importer kept the most complete copy; these',
      'are the differences it discarded, for review.',
      '',
      ...allDrift.map(
        (n) => `- **${n.project} / ${n.section} / ${n.title}** (${n.kind})\n  ${n.detail}`
      ),
      '',
    ].join('\n'),
    'utf8'
  )
  console.log(`  Written to docs/todotwo/IMPORT-DRIFT.md\n`)
}

function countSeries(tasks: ImportTask[]): number {
  return tasks.reduce((sum, t) => sum + (t.rrule ? 1 : 0) + countSeries(t.children), 0)
}

if (!apply) {
  console.log('  Nothing written. Re-run with --apply to import.\n')
  process.exit(0)
}

// ---------------------------------------------------------------------------
// Apply
// ---------------------------------------------------------------------------

const url = process.env.NEXT_PUBLIC_TODOTWO_SUPABASE_URL
const serviceRoleKey = process.env.TODOTWO_SUPABASE_SERVICE_ROLE_KEY
if (!url || !serviceRoleKey) fail('Missing TodoTwo Supabase environment. See docs/todotwo/SETUP.md.')

const refMatch = /^https:\/\/([a-z0-9]+)\.supabase\.(co|in)$/i.exec(url.trim())
if (!refMatch) fail(`Not a Supabase project URL: ${url}`)
const connectedRef = refMatch[1]
if (PRODUCTION_REFS.has(connectedRef)) fail(`${connectedRef} is production. Refusing to import.`)

const expectedRef = process.env.TODOTWO_DEV_PROJECT_REF
if (expectedRef && expectedRef !== connectedRef) {
  fail(`Connected project is ${connectedRef} but TODOTWO_DEV_PROJECT_REF says ${expectedRef}.`)
}

const db = createClient(url, serviceRoleKey, {
  db: { schema: 'todotwo' },
  auth: { autoRefreshToken: false, persistSession: false },
})

async function main() {
  for (const plan of plans) {
    const { project } = plan

    const { data: projectRow, error: projectError } = await db
      .from('projects')
      .upsert({ name: project.name, slug: project.slug, kind: 'list' }, { onConflict: 'slug' })
      .select('id')
      .single()

    if (projectError || !projectRow) fail(`project ${project.name}: ${projectError?.message}`)
    const projectId = projectRow.id as string

    let sectionOrder = 0
    for (const section of project.sections) {
      sectionOrder += 10
      const { data: sectionRow, error: sectionError } = await db
        .from('sections')
        .insert({ project_id: projectId, name: section.name, sort_order: sectionOrder })
        .select('id')
        .single()

      if (sectionError || !sectionRow) fail(`section ${section.name}: ${sectionError?.message}`)

      await writeTasks(section.tasks, projectId, sectionRow.id as string)
    }

    await writeTasks(project.looseTasks, projectId, null)
    console.log(`  imported ${project.name}`)
  }

  console.log('\n  Done.\n')
}

async function writeTasks(tasks: ImportTask[], projectId: string, sectionId: string | null) {
  let order = 0
  for (const task of tasks) {
    order += 10

    if (task.rrule) {
      // A recurring routine becomes a series: one text, edited once.
      const { data: series, error } = await db
        .from('task_series')
        .insert({
          project_id: projectId,
          section_id: sectionId,
          title: task.title,
          description: task.description,
          priority: task.priority,
          rrule: task.rrule,
          starts_on: new Date().toISOString().slice(0, 10),
          source_text: task.recurrenceText,
        })
        .select('id')
        .single()

      if (error || !series) fail(`series ${task.title}: ${error?.message}`)

      let stepOrder = 0
      for (const child of task.children) {
        stepOrder += 10
        const { error: stepError } = await db.from('task_series_steps').insert({
          series_id: series.id as string,
          title: child.title,
          description: child.description,
          sort_order: stepOrder,
        })
        if (stepError) fail(`step ${child.title}: ${stepError.message}`)
      }
      continue
    }

    // A one-off task.
    const { data: row, error } = await db
      .from('tasks')
      .insert({
        project_id: projectId,
        section_id: sectionId,
        title: task.title,
        description: task.description,
        priority: task.priority,
        recurrence_text: task.recurrenceText,
        recurrence_lang: task.recurrenceLang,
        sort_order: order,
        status: 'unassigned',
      })
      .select('id')
      .single()

    if (error || !row) fail(`task ${task.title}: ${error?.message}`)

    if (task.children.length > 0) {
      await writeSubtasks(task.children, row.id as string, projectId, sectionId)
    }
  }
}

async function writeSubtasks(
  tasks: ImportTask[],
  parentId: string,
  projectId: string,
  sectionId: string | null
) {
  let order = 0
  for (const task of tasks) {
    order += 10
    const { data: row, error } = await db
      .from('tasks')
      .insert({
        project_id: projectId,
        section_id: sectionId,
        parent_task_id: parentId,
        title: task.title,
        description: task.description,
        priority: task.priority,
        sort_order: order,
        status: 'unassigned',
      })
      .select('id')
      .single()

    if (error || !row) fail(`subtask ${task.title}: ${error?.message}`)
    if (task.children.length > 0) {
      await writeSubtasks(task.children, row.id as string, projectId, sectionId)
    }
  }
}

main().catch((error) => fail(error instanceof Error ? error.message : String(error)))
