-- TodoTwo — rate limiting for sign-in link requests
--
-- Magic links are now generated by TodoTwo and sent through Mailgun, like the
-- rest of the farm's email, rather than by Supabase's built-in mailer. That
-- moves an unauthenticated, side-effecting endpoint into our hands: anyone can
-- POST an address and cause an email to be sent.
--
-- Two things guard it. The route answers identically whether or not the address
-- has access, so it cannot be used to enumerate the household. And this table
-- caps how often anyone can ask.
--
-- Kept in Postgres rather than in memory because the app runs on Netlify
-- functions: an in-process counter resets on every cold start and is not shared
-- between concurrent instances, which makes it decorative.

create table todotwo.auth_link_requests (
  id           bigint generated always as identity primary key,
  email        text not null,
  ip           text,
  requested_at timestamptz not null default now()
);

create index auth_link_requests_email_idx on todotwo.auth_link_requests (lower(email), requested_at desc);
create index auth_link_requests_ip_idx on todotwo.auth_link_requests (ip, requested_at desc);

alter table todotwo.auth_link_requests enable row level security;

-- No policy for anyone. The table is written only by the security-definer
-- function below and read only by the service role, which bypasses RLS.
revoke all on todotwo.auth_link_requests from anon, authenticated;

comment on table todotwo.auth_link_requests is
  'Rate-limit ledger for sign-in link requests. Written only by todotwo.claim_link_request().';

-- ---------------------------------------------------------------------------
-- Records an attempt and says whether it is allowed.
--
-- Deliberately one function rather than a check followed by a write: two
-- statements race, and the race is exactly what an attacker would exploit.
--
-- Not granted to anon or authenticated. Only the route handler's service-role
-- client calls it, which is what keeps the limits meaningful — a caller who
-- could invoke it directly could also just not invoke it.
-- ---------------------------------------------------------------------------

create or replace function todotwo.claim_link_request(
  p_email text,
  p_ip text,
  p_per_email integer default 3,
  p_per_ip integer default 10
)
returns boolean
language plpgsql
security definer
set search_path = todotwo, public
as $$
declare
  v_email_count integer;
  v_ip_count    integer;
begin
  -- Housekeeping: the ledger only needs a rolling window.
  delete from todotwo.auth_link_requests
   where requested_at < now() - interval '24 hours';

  select count(*) into v_email_count
  from todotwo.auth_link_requests
  where lower(email) = lower(trim(p_email))
    and requested_at > now() - interval '15 minutes';

  select count(*) into v_ip_count
  from todotwo.auth_link_requests
  where p_ip is not null
    and ip = p_ip
    and requested_at > now() - interval '1 hour';

  -- Recorded whether or not it is allowed, so hammering the endpoint extends
  -- the lockout instead of resetting it.
  insert into todotwo.auth_link_requests (email, ip) values (trim(p_email), p_ip);

  return v_email_count < p_per_email and v_ip_count < p_per_ip;
end;
$$;

revoke all on function todotwo.claim_link_request(text, text, integer, integer)
  from public, anon, authenticated;

-- ROLLBACK:
--   drop function if exists todotwo.claim_link_request(text, text, integer, integer);
--   drop table if exists todotwo.auth_link_requests;
