CREATE TABLE IF NOT EXISTS communication_flow_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  product_type TEXT NOT NULL CHECK (product_type IN ('mangalitsa', 'eggs')),
  flow_stage TEXT NOT NULL,
  name_no TEXT NOT NULL,
  name_en TEXT NOT NULL,
  subject_no TEXT NOT NULL,
  subject_en TEXT NOT NULL,
  body_no TEXT NOT NULL,
  body_en TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT 'email',
  trigger_event TEXT,
  send_offset_days INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT true,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_comm_flow_templates_product
  ON communication_flow_templates(product_type, active, display_order);

INSERT INTO communication_flow_templates (
  slug, product_type, flow_stage, name_no, name_en,
  subject_no, subject_en, body_no, body_en,
  trigger_event, send_offset_days, active, display_order
) VALUES
  (
    'mangalitsa-order-confirmation',
    'mangalitsa',
    'order_confirmation',
    'Mangalitsa: Ordrebekreftelse',
    'Mangalitsa: Order confirmation',
    'Ordrebekreftelse {ORDER_NUMBER}',
    'Order confirmation {ORDER_NUMBER}',
    '<p>Hei {CUSTOMER_NAME},</p><p>Takk for bestillingen av Mangalitsa-boks. Vi har registrert ordren din ({ORDER_NUMBER}).</p><p>Du får neste oppdatering når sesongen skrider frem.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>Thanks for your Mangalitsa box order. We have registered your order ({ORDER_NUMBER}).</p><p>You will receive the next update as the season progresses.</p>',
    'order_created',
    0,
    true,
    10
  ),
  (
    'mangalitsa-mid-season-update',
    'mangalitsa',
    'mid_season_update',
    'Mangalitsa: Midt i sesongen',
    'Mangalitsa: Mid-season update',
    'Statusoppdatering for {ORDER_NUMBER}',
    'Season update for {ORDER_NUMBER}',
    '<p>Hei {CUSTOMER_NAME},</p><p>En kort oppdatering: grisene vokser godt, og vi følger planen for sesongen.</p><p>Vi sender ny melding nær slakting og levering.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>A short update: the pigs are growing well and we are on plan for the season.</p><p>We will send another message closer to slaughter and delivery.</p>',
    'season_midpoint',
    0,
    true,
    20
  ),
  (
    'mangalitsa-slaughter-week',
    'mangalitsa',
    'slaughter_week_notice',
    'Mangalitsa: Slakteuke',
    'Mangalitsa: Slaughter week',
    'Slakteuke nærmer seg for {ORDER_NUMBER}',
    'Slaughter week approaching for {ORDER_NUMBER}',
    '<p>Hei {CUSTOMER_NAME},</p><p>Vi går inn i slakteuke for din bestilling ({ORDER_NUMBER}).</p><p>Du får informasjon om betaling av restbeløp og levering i neste oppdatering.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>We are entering slaughter week for your order ({ORDER_NUMBER}).</p><p>You will receive remainder payment and delivery details in the next update.</p>',
    'slaughter_week',
    0,
    true,
    30
  ),
  (
    'mangalitsa-delivery-scheduling',
    'mangalitsa',
    'delivery_scheduling',
    'Mangalitsa: Leveringsplanlegging',
    'Mangalitsa: Delivery scheduling',
    'Planlegg levering for {ORDER_NUMBER}',
    'Schedule delivery for {ORDER_NUMBER}',
    '<p>Hei {CUSTOMER_NAME},</p><p>Nå planlegger vi levering/henting for ordren din ({ORDER_NUMBER}).</p><p>Logg inn på Min side for å bekrefte detaljer og eventuelle ekstra produkter.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>We are now planning delivery/pickup for your order ({ORDER_NUMBER}).</p><p>Please sign in to My page to confirm details and any extra products.</p>',
    'delivery_window_open',
    0,
    true,
    40
  ),
  (
    'mangalitsa-feedback-request',
    'mangalitsa',
    'post_delivery_feedback',
    'Mangalitsa: Hvordan var opplevelsen?',
    'Mangalitsa: How was it?',
    'Hvordan var Mangalitsa-boksen din?',
    'How was your Mangalitsa box?',
    '<p>Hei {CUSTOMER_NAME},</p><p>Takk for bestillingen. Vi vil gjerne høre hvordan opplevelsen var.</p><p>Send oss gjerne en kort tilbakemelding på smak, levering og totalopplevelse.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>Thanks for your order. We would love to hear how your experience was.</p><p>Please share quick feedback on taste, delivery, and overall experience.</p>',
    'post_delivery',
    3,
    true,
    50
  ),
  (
    'eggs-order-confirmation',
    'eggs',
    'order_confirmation',
    'Egg: Ordrebekreftelse',
    'Eggs: Order confirmation',
    'Ordrebekreftelse rugeegg {ORDER_NUMBER}',
    'Hatching eggs order confirmation {ORDER_NUMBER}',
    '<p>Hei {CUSTOMER_NAME},</p><p>Vi har registrert bestillingen din ({ORDER_NUMBER}) for rugeegg.</p><p>Du får oppdatering når forsendelsen nærmer seg.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>We have registered your hatching eggs order ({ORDER_NUMBER}).</p><p>You will receive updates as shipment approaches.</p>',
    'order_created',
    0,
    true,
    110
  ),
  (
    'eggs-mid-season-update',
    'eggs',
    'mid_season_update',
    'Egg: Midt i sesongen',
    'Eggs: Mid-season update',
    'Status på rugeegg-sesongen',
    'Hatching season status update',
    '<p>Hei {CUSTOMER_NAME},</p><p>En kort oppdatering fra gården: vi følger plan for klekking og forsendelser.</p><p>Du får detaljert melding nær utsendelse.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>A short update from the farm: we are on track for hatching and shipment weeks.</p><p>You will receive detailed information closer to shipping.</p>',
    'season_midpoint',
    0,
    true,
    120
  ),
  (
    'eggs-slaughter-week',
    'eggs',
    'packing_week_notice',
    'Egg: Pakkeuke nærmer seg',
    'Eggs: Packing week approaching',
    'Pakking av rugeegg for {ORDER_NUMBER}',
    'Packing hatching eggs for {ORDER_NUMBER}',
    '<p>Hei {CUSTOMER_NAME},</p><p>Vi går inn i pakkeuke for ordren din ({ORDER_NUMBER}).</p><p>Du får oppdatert melding når pakken er klar til utsendelse.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>We are entering packing week for your order ({ORDER_NUMBER}).</p><p>You will get another update when shipment is ready.</p>',
    'packing_week',
    0,
    true,
    130
  ),
  (
    'eggs-delivery-scheduling',
    'eggs',
    'delivery_scheduling',
    'Egg: Leveringsplanlegging',
    'Eggs: Delivery scheduling',
    'Leveringsdetaljer for {ORDER_NUMBER}',
    'Delivery details for {ORDER_NUMBER}',
    '<p>Hei {CUSTOMER_NAME},</p><p>Nå planlegger vi utsendelse av ordren din ({ORDER_NUMBER}).</p><p>Kontroller kontaktinformasjon og leveringsdetaljer på Min side.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>We are now scheduling shipment for your order ({ORDER_NUMBER}).</p><p>Please verify contact and delivery details on My page.</p>',
    'shipment_window_open',
    0,
    true,
    140
  ),
  (
    'eggs-feedback-request',
    'eggs',
    'post_delivery_feedback',
    'Egg: Hvordan gikk klekkingen?',
    'Eggs: How did hatching go?',
    'Tilbakemelding på rugeegg-batch',
    'Feedback on your hatching eggs batch',
    '<p>Hei {CUSTOMER_NAME},</p><p>Takk for bestillingen av rugeegg.</p><p>Vi setter stor pris på tilbakemelding om klekkingsresultat og levering.</p>',
    '<p>Hi {CUSTOMER_NAME},</p><p>Thank you for ordering hatching eggs.</p><p>We would greatly appreciate feedback on hatch rate and delivery quality.</p>',
    'post_delivery',
    3,
    true,
    150
  )
ON CONFLICT (slug) DO NOTHING;
