-- TodoTwo — password sign-in and WebAuthn passkeys
--
-- Adds a `password_set` flag so the callback flow can force a first-time
-- password before someone reaches the app, plus a table of registered
-- WebAuthn credentials for passkey login.
--
-- webauthn_credentials has no insert/update policy for `authenticated`: every
-- write goes through the security-definer save_webauthn_credential function
-- below, so a compromised or buggy client can never write an attacker-supplied
-- public key directly. Reading a credential by its id during login (before
-- anyone is signed in) goes through the service-role exception in
-- lib/todotwo/auth-admin.ts instead — not through a new SQL function — because
-- credential_id is a large random value generated by authenticator hardware,
-- not a guessable human input like an email address, and adding a second
-- anon-callable lookup function here would repeat the F1 membership-oracle
-- mistake fixed in 20260903090400_todotwo_security_hardening.sql.

alter table todotwo.people add column if not exists password_set boolean not null default false;

create or replace function todotwo.mark_password_set()
returns void
language plpgsql
security definer
set search_path = todotwo, public, pg_temp
as $$
begin
  update todotwo.people set password_set = true where id = todotwo.current_person_id();
end;
$$;

revoke all on function todotwo.mark_password_set() from public, anon;
grant execute on function todotwo.mark_password_set() to authenticated;

create table if not exists todotwo.webauthn_credentials (
  id uuid primary key default gen_random_uuid(),
  person_id uuid not null references todotwo.people(id) on delete cascade,
  credential_id text not null unique,
  public_key text not null,
  counter bigint not null default 0,
  transports text[],
  device_label text,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);

create index if not exists webauthn_credentials_person_id_idx
  on todotwo.webauthn_credentials (person_id);

alter table todotwo.webauthn_credentials enable row level security;

create policy webauthn_select_own on todotwo.webauthn_credentials
  for select
  using (person_id = todotwo.current_person_id());

create policy webauthn_delete_own on todotwo.webauthn_credentials
  for delete
  using (person_id = todotwo.current_person_id());

-- Deliberately no insert/update policy for authenticated: writes only happen
-- through save_webauthn_credential below.

create or replace function todotwo.save_webauthn_credential(
  p_credential_id text,
  p_public_key text,
  p_counter bigint,
  p_transports text[],
  p_device_label text
)
returns uuid
language plpgsql
security definer
set search_path = todotwo, public, pg_temp
as $$
declare
  v_person_id uuid;
  v_id uuid;
begin
  v_person_id := todotwo.current_person_id();
  if v_person_id is null then
    raise exception 'not signed in';
  end if;

  insert into todotwo.webauthn_credentials
    (person_id, credential_id, public_key, counter, transports, device_label)
  values
    (v_person_id, p_credential_id, p_public_key, p_counter, p_transports, p_device_label)
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function todotwo.save_webauthn_credential(text, text, bigint, text[], text) from public, anon;
grant execute on function todotwo.save_webauthn_credential(text, text, bigint, text[], text) to authenticated;

grant select, delete on todotwo.webauthn_credentials to authenticated;
revoke all on todotwo.webauthn_credentials from anon;

-- ROLLBACK:
--   revoke execute on function todotwo.save_webauthn_credential(text, text, bigint, text[], text) from authenticated;
--   drop function if exists todotwo.save_webauthn_credential(text, text, bigint, text[], text);
--   drop policy if exists webauthn_delete_own on todotwo.webauthn_credentials;
--   drop policy if exists webauthn_select_own on todotwo.webauthn_credentials;
--   drop table if exists todotwo.webauthn_credentials;
--   revoke execute on function todotwo.mark_password_set() from authenticated;
--   drop function if exists todotwo.mark_password_set();
--   alter table todotwo.people drop column if exists password_set;
