-- Add full Mangalitsa special-cut extras catalog for checkout selection.
-- Idempotent: safe to run multiple times.

-- Ensure premium content columns exist across environments.
ALTER TABLE extras_catalog
  ADD COLUMN IF NOT EXISTS description_premium_no TEXT,
  ADD COLUMN IF NOT EXISTS description_premium_en TEXT,
  ADD COLUMN IF NOT EXISTS chef_term_no TEXT,
  ADD COLUMN IF NOT EXISTS chef_term_en TEXT,
  ADD COLUMN IF NOT EXISTS recipe_suggestions JSONB,
  ADD COLUMN IF NOT EXISTS preparation_tips_no TEXT,
  ADD COLUMN IF NOT EXISTS preparation_tips_en TEXT,
  ADD COLUMN IF NOT EXISTS product_type TEXT DEFAULT 'pig_box',
  ADD COLUMN IF NOT EXISTS default_quantity NUMERIC(10,2) DEFAULT 1.0;

INSERT INTO extras_catalog (
  slug,
  name_no,
  name_en,
  description_no,
  description_en,
  description_premium_no,
  description_premium_en,
  chef_term_no,
  chef_term_en,
  recipe_suggestions,
  preparation_tips_no,
  preparation_tips_en,
  price_nok,
  pricing_type,
  default_quantity,
  active,
  display_order,
  product_type,
  consumes_inventory_kg,
  kg_per_unit,
  updated_at
)
VALUES
  (
    'extra-guanciale',
    'Svinekinn (guanciale)',
    'Pork jowl (guanciale)',
    'Kun to kinn per gris. Dyp smak og sterk marmorering.',
    'Only two jowls per pig. Deep flavor and heavy marbling.',
    'Restaurantkutt med hoy verdi per gram. Perfekt til carbonara og amatriciana.',
    'Restaurant-grade cut with very high value per gram. Ideal for carbonara and amatriciana.',
    'Guanciale',
    'Guanciale',
    '[
      {"title_no":"Carbonara med guanciale","title_en":"Carbonara with guanciale","description_no":"Spr hostede biter med eggeplommer og pecorino","description_en":"Crisped cubes with egg yolks and pecorino","future_slug":"carbonara-guanciale"},
      {"title_no":"Amatriciana","title_en":"Amatriciana","description_no":"Tomat, chili og guanciale","description_en":"Tomato, chili and guanciale","future_slug":"amatriciana"}
    ]'::jsonb,
    'Salt lett, stek hardt, og bruk fettet i sausen.',
    'Salt lightly, sear hard, and use the rendered fat in sauce.',
    790,
    'per_kg',
    0.50,
    true,
    30,
    'pig_box',
    true,
    0,
    NOW()
  ),
  (
    'extra-coppa',
    'Nakkekam (coppa)',
    'Neck collar (coppa)',
    'Nakkekam med dyp marmorering.',
    'Neck collar with deep marbling.',
    'Egner seg til speking som coppa eller tykke biffer pa grill.',
    'Ideal for curing as coppa or thick steaks on high heat.',
    'Coppa',
    'Coppa',
    '[
      {"title_no":"Coppa-prosjekt","title_en":"Coppa project","description_no":"Torrsalting og langtidsmodning","description_en":"Dry curing and long maturation","future_slug":"coppa-project"},
      {"title_no":"Nakkebiff","title_en":"Neck steak","description_no":"Hard varme, rosa kjerne","description_en":"High heat, pink center","future_slug":"neck-steak"}
    ]'::jsonb,
    'Skjaer tykt, stek hardt, hvil 5 minutter.',
    'Cut thick, sear hard, rest for 5 minutes.',
    545,
    'per_kg',
    1.00,
    true,
    31,
    'pig_box',
    true,
    0,
    NOW()
  ),
  (
    'extra-secreto-presa-pluma',
    'Slakterbiff (secreto, presa, pluma)',
    'Butcher steak (secreto, presa, pluma)',
    'Smakstette, skjulte muskler med mye intramuskulart fett.',
    'Hidden butcher cuts with dense flavor and high intramuscular fat.',
    'Dette er de mest ettertraktede sma-kuttene pa gris.',
    'These are the most sought-after small butcher cuts on pork.',
    'Secreto/Presa/Pluma',
    'Secreto/Presa/Pluma',
    '[
      {"title_no":"Secreto pa plancha","title_en":"Secreto a la plancha","description_no":"2-3 min per side pa hard varme","description_en":"2-3 min per side on high heat","future_slug":"secreto-plancha"},
      {"title_no":"Presa med urter","title_en":"Presa with herbs","description_no":"Rask steking og hvile","description_en":"Quick sear and rest","future_slug":"presa-herbs"}
    ]'::jsonb,
    'Kort steketid og alltid hvile for servering.',
    'Keep cook time short and always rest before slicing.',
    890,
    'per_kg',
    0.50,
    true,
    32,
    'pig_box',
    true,
    0,
    NOW()
  ),
  (
    'extra-spekk',
    'Ryggspekk (lardo)',
    'Back fat (lardo)',
    'Rent ryggfett fra ullgris.',
    'Pure back fat from woolly pig.',
    'Perfekt til lardo, stekefett eller confit.',
    'Perfect for lardo, cooking fat, or confit.',
    'Lardo',
    'Lardo',
    '[
      {"title_no":"Lardo crostini","title_en":"Lardo crostini","description_no":"Tynne skiver pa ristet brod","description_en":"Thin slices on toasted bread","future_slug":"lardo-crostini"},
      {"title_no":"Smeltet smult","title_en":"Rendered lard","description_no":"Langsom utsmelting til glass","description_en":"Slow render into jarred fat","future_slug":"rendered-lard"}
    ]'::jsonb,
    'Skjaer tynt for servering eller smelt ned pa lav varme.',
    'Slice thin for serving or render on low heat.',
    345,
    'per_kg',
    1.00,
    true,
    33,
    'pig_box',
    true,
    0,
    NOW()
  ),
  (
    'extra-tomahawk',
    'Tomahawk-kotelett',
    'Tomahawk chop',
    'Tykke koteletter med langt bein og fettkappe.',
    'Thick chops with long bone and fat cap.',
    'Steakhouse-kutt med wow-effekt pa fjola.',
    'Steakhouse cut with serious wow-factor.',
    'Tomahawk',
    'Tomahawk',
    '[
      {"title_no":"Tomahawk pa grill","title_en":"Tomahawk on grill","description_no":"Direkte + indirekte varme","description_en":"Direct + indirect heat","future_slug":"tomahawk-grill"}
    ]'::jsonb,
    'Sear hard first, then finish gently to medium.',
    'Sear hard first, then finish gently to medium.',
    465,
    'per_kg',
    1.00,
    true,
    34,
    'pig_box',
    true,
    0,
    NOW()
  ),
  (
    'extra-svine-entrecote',
    'Svine-entrecote',
    'Pork ribeye',
    'Marmorerte biffer fra nakke/kam-omradet.',
    'Marbled steaks from neck/loin area.',
    'Mye smak, mye saftighet, best med rosa kjerne.',
    'Big flavor and juiciness, best with a pink center.',
    'Ribeye',
    'Ribeye',
    '[
      {"title_no":"Entrecote i panne","title_en":"Ribeye in pan","description_no":"Hoy varme og rask hvile","description_en":"High heat and short rest","future_slug":"pork-ribeye-pan"}
    ]'::jsonb,
    'Stek 2-3 min per side pa hoy varme, hvil kort.',
    'Cook 2-3 min per side on high heat, rest briefly.',
    495,
    'per_kg',
    1.00,
    true,
    35,
    'pig_box',
    true,
    0,
    NOW()
  ),
  (
    'extra-pancetta',
    'Buklist (pancetta)',
    'Pork belly strip (pancetta)',
    'Buklist med fettlag og dybde i smaken.',
    'Belly strip with rich fat layers and deep flavor.',
    'Ideell til hjemmelaget pancetta eller premium bacon.',
    'Ideal for homemade pancetta or premium bacon.',
    'Pancetta',
    'Pancetta',
    '[
      {"title_no":"Pancetta-prosjekt","title_en":"Pancetta project","description_no":"Salt, krydder og lufting","description_en":"Salt, spices and air-drying","future_slug":"pancetta-project"}
    ]'::jsonb,
    'Saltes og rulles for curing, eller stekes sakte.',
    'Salt and roll for curing, or slow-roast.',
    399,
    'per_kg',
    1.00,
    true,
    36,
    'pig_box',
    true,
    0,
    NOW()
  ),
  (
    'extra-skinke-speking',
    'Hel skinke med fettkappe',
    'Whole ham with fat cap',
    'Stor skinke egnet for speking eller langsteking.',
    'Large ham ideal for curing or slow roasting.',
    'Hovedkuttet for eget spekeprosjekt.',
    'Primary cut for a home curing project.',
    'Prosciutto style ham',
    'Prosciutto style ham',
    '[
      {"title_no":"Speke skinke","title_en":"Cure a ham","description_no":"Lang modning 6-12 mnd","description_en":"Long cure 6-12 months","future_slug":"cure-ham"}
    ]'::jsonb,
    'Hold fettkappen pa under lagring for bedre resultat.',
    'Keep the fat cap on during curing for better results.',
    449,
    'per_kg',
    1.00,
    true,
    37,
    'pig_box',
    true,
    0,
    NOW()
  ),
  (
    'extra-knoke',
    'Knoke',
    'Knuckle',
    'Knoke med ben, kollagen og kraftsmak.',
    'Knuckle with bone, collagen, and broth depth.',
    'Perfekt for rik kraft, supper og braisering.',
    'Perfect for rich stock, soups, and braises.',
    'Shank/knuckle',
    'Shank/knuckle',
    '[
      {"title_no":"Kraft av knoke","title_en":"Knuckle stock","description_no":"Langkok med aromater","description_en":"Long simmer with aromatics","future_slug":"knuckle-stock"}
    ]'::jsonb,
    'Kok 4-6 timer for kraft, eller braiser til mork tekstur.',
    'Simmer 4-6 hours for stock, or braise until tender.',
    149,
    'per_unit',
    1.00,
    true,
    38,
    'pig_box',
    true,
    1.00,
    NOW()
  ),
  (
    'extra-smult',
    'Smult (ferdig utsmeltet)',
    'Rendered lard (jar)',
    'Ferdig utsmeltet fett klart til steking.',
    'Ready-rendered fat for high-flavor cooking.',
    'Ren smak og hoy varmebestandighet pa kjokkenet.',
    'Clean flavor and high heat performance in the kitchen.',
    'Rendered lard',
    'Rendered lard',
    '[
      {"title_no":"Stek i smult","title_en":"Fry in lard","description_no":"Gir ekstra skorpe og smak","description_en":"Builds crust and flavor","future_slug":"fry-in-lard"}
    ]'::jsonb,
    'Bruk som stekefett til koteletter, biffer og poteter.',
    'Use as cooking fat for chops, steaks, and potatoes.',
    129,
    'per_unit',
    1.00,
    true,
    39,
    'pig_box',
    false,
    0,
    NOW()
  )
ON CONFLICT (slug) DO UPDATE SET
  name_no = EXCLUDED.name_no,
  name_en = EXCLUDED.name_en,
  description_no = EXCLUDED.description_no,
  description_en = EXCLUDED.description_en,
  description_premium_no = EXCLUDED.description_premium_no,
  description_premium_en = EXCLUDED.description_premium_en,
  chef_term_no = EXCLUDED.chef_term_no,
  chef_term_en = EXCLUDED.chef_term_en,
  recipe_suggestions = EXCLUDED.recipe_suggestions,
  preparation_tips_no = EXCLUDED.preparation_tips_no,
  preparation_tips_en = EXCLUDED.preparation_tips_en,
  price_nok = EXCLUDED.price_nok,
  pricing_type = EXCLUDED.pricing_type,
  default_quantity = EXCLUDED.default_quantity,
  active = EXCLUDED.active,
  display_order = EXCLUDED.display_order,
  product_type = EXCLUDED.product_type,
  consumes_inventory_kg = EXCLUDED.consumes_inventory_kg,
  kg_per_unit = EXCLUDED.kg_per_unit,
  updated_at = NOW();

