-- ============================================================================
-- Add 6 globally inspired Mangalitsa recipes to increase variety
-- Date: 2026-02-26
-- ============================================================================

INSERT INTO recipes (
  slug, title_no, title_en,
  intro_no, intro_en,
  ingredients_no, ingredients_en,
  steps_no, steps_en,
  tips_no, tips_en,
  mangalitsa_tip_no, mangalitsa_tip_en,
  difficulty, prep_time_minutes, cook_time_minutes, servings,
  image_url, related_extra_slugs, display_order, active
) VALUES
(
  'tomahawk-chimichurri',
  'Tomahawk av ullgris med chimichurri og grillet sitron',
  'Wool Pig Tomahawk with Chimichurri and Grilled Lemon',
  'En kraftig steak-opplevelse med urtefrisk chimichurri og sotet sitron. Helt annen profil enn klassisk norsk husmann.',
  'A bold steak experience with herb-forward chimichurri and charred lemon. A completely different profile from classic Nordic comfort food.',
  '[
    {"amount":"1,2 kg","item":"tomahawk av ullgris"},
    {"amount":"1 ss","item":"noytral olje"},
    {"amount":"","item":"salt og sort pepper"},
    {"amount":"1 bunt","item":"bladpersille, finhakket"},
    {"amount":"1 ss","item":"oregano, finhakket"},
    {"amount":"2 fedd","item":"hvitlok, finhakket"},
    {"amount":"2 ss","item":"rodvinseddik"},
    {"amount":"1 dl","item":"olivenolje"},
    {"amount":"1 ts","item":"chiliflak"},
    {"amount":"1 stk","item":"sitron, delt i to"}
  ]'::jsonb,
  '[
    {"amount":"1.2 kg","item":"wool pig tomahawk"},
    {"amount":"1 tbsp","item":"neutral oil"},
    {"amount":"","item":"salt and black pepper"},
    {"amount":"1 bunch","item":"flat-leaf parsley, finely chopped"},
    {"amount":"1 tbsp","item":"oregano, finely chopped"},
    {"amount":"2 cloves","item":"garlic, finely chopped"},
    {"amount":"2 tbsp","item":"red wine vinegar"},
    {"amount":"100 ml","item":"olive oil"},
    {"amount":"1 tsp","item":"chili flakes"},
    {"amount":"1","item":"lemon, halved"}
  ]'::jsonb,
  '[
    "Temperer kjottet i 30-45 minutter. Krydre godt med salt og pepper.",
    "Stek eller grill tomahawk pa hoy varme 3-4 minutter per side for stekeskorpe.",
    "Flytt til indirekte varme eller 160 C ovn til kjernetemperatur 58-60 C.",
    "Bland persille, oregano, hvitlok, eddik, olivenolje og chiliflak til chimichurri.",
    "Grill sitronflatene raskt til lett sotet overflate.",
    "La kjottet hvile i 10 minutter. Skjaer i skiver og server med chimichurri og grillet sitron."
  ]'::jsonb,
  '[
    "Bring the meat to room temperature for 30-45 minutes. Season well with salt and pepper.",
    "Sear or grill over high heat for 3-4 minutes per side to build crust.",
    "Move to indirect heat or a 160 C oven until internal temperature reaches 58-60 C.",
    "Mix parsley, oregano, garlic, vinegar, olive oil, and chili flakes into chimichurri.",
    "Grill lemon halves quickly until lightly charred.",
    "Rest meat for 10 minutes. Slice and serve with chimichurri and grilled lemon."
  ]'::jsonb,
  'Skjaer alltid pa tvers av fibrene, ellers mister du morkheten i skivene.',
  'Always slice across the grain to keep the meat tender.',
  'Tomahawk av ullgris har tydelig marmorering som holder stykket saftig selv med hard stekeskorpe.',
  'Wool pig tomahawk has distinct marbling that keeps it juicy even with an aggressive sear.',
  'medium', 20, 30, 4,
  '/recipes/tomahawk-chimichurri.jpg',
  ARRAY['extra-tomahawk'],
  24,
  true
),
(
  'secreto-miso-sesam',
  'Secreto av ullgris med miso, sesam og lime',
  'Wool Pig Secreto with Miso, Sesame and Lime',
  'Rask japansk-inspirert oppskrift der miso gir dyp umami og lime kutter gjennom fettet.',
  'A fast Japanese-inspired recipe where miso brings deep umami and lime cuts through richness.',
  '[
    {"amount":"900 g","item":"secreto av ullgris"},
    {"amount":"2 ss","item":"hvit miso"},
    {"amount":"2 ss","item":"soyasaus"},
    {"amount":"1 ss","item":"honning"},
    {"amount":"1 ss","item":"sesamolje"},
    {"amount":"1 ss","item":"revet ingefaer"},
    {"amount":"1 stk","item":"lime, finrevet skall + saft"},
    {"amount":"1 ss","item":"ristede sesamfro"},
    {"amount":"1 neve","item":"koriander"}
  ]'::jsonb,
  '[
    {"amount":"900 g","item":"wool pig secreto"},
    {"amount":"2 tbsp","item":"white miso"},
    {"amount":"2 tbsp","item":"soy sauce"},
    {"amount":"1 tbsp","item":"honey"},
    {"amount":"1 tbsp","item":"sesame oil"},
    {"amount":"1 tbsp","item":"grated ginger"},
    {"amount":"1","item":"lime, zest + juice"},
    {"amount":"1 tbsp","item":"toasted sesame seeds"},
    {"amount":"1 handful","item":"coriander"}
  ]'::jsonb,
  '[
    "Ror sammen miso, soyasaus, honning, sesamolje, ingefaer og halvparten av limesaften.",
    "Vend secreto i marinaden og la trekke i 20 minutter.",
    "Stek i glovarm panne 2-3 minutter per side til tydelig stekeskorpe.",
    "Skru ned varmen siste minutt og pensle med restmarinaden.",
    "La hvile i 5-7 minutter, skjaer i tynne skiver.",
    "Topp med sesamfro, koriander og resten av limesaften."
  ]'::jsonb,
  '[
    "Whisk miso, soy sauce, honey, sesame oil, ginger, and half of the lime juice.",
    "Coat secreto in the marinade and rest for 20 minutes.",
    "Cook in a very hot pan for 2-3 minutes per side until deeply seared.",
    "Lower heat for the final minute and brush with remaining marinade.",
    "Rest 5-7 minutes, then slice thinly.",
    "Finish with sesame seeds, coriander, and the rest of the lime juice."
  ]'::jsonb,
  'Bruk hoy varme og kort tid. Secreto blir best nar det fortsatt er saftig i kjernen.',
  'Use high heat and short cooking time. Secreto is best when still juicy at the center.',
  'Secreto fra ullgris har fettlag som smelter raskt og gir en nesten smoraktig munnfolelse.',
  'Wool pig secreto has fat layers that render quickly and create an almost buttery mouthfeel.',
  'easy', 20, 10, 4,
  '/recipes/secreto-miso-sesam.jpg',
  ARRAY['extra-secreto-presa-pluma'],
  25,
  true
),
(
  'koteletter-harissa-yoghurt',
  'Ullgris-koteletter med harissa, yoghurt og mynte',
  'Wool Pig Chops with Harissa, Yogurt and Mint',
  'Nord-afrikansk inspirert kotelettrett med varme krydder, frisk yoghurt og urter.',
  'North African-inspired chop dish with warm spices, cool yogurt, and fresh herbs.',
  '[
    {"amount":"4 stk","item":"koteletter av ullgris"},
    {"amount":"2 ss","item":"harissa"},
    {"amount":"2 ss","item":"olivenolje"},
    {"amount":"1 ts","item":"spisskummen"},
    {"amount":"300 g","item":"gresk yoghurt"},
    {"amount":"1 fedd","item":"hvitlok, finrevet"},
    {"amount":"1 ss","item":"sitronsaft"},
    {"amount":"1 neve","item":"mynte, grovhakket"},
    {"amount":"","item":"salt og sort pepper"}
  ]'::jsonb,
  '[
    {"amount":"4","item":"wool pig chops"},
    {"amount":"2 tbsp","item":"harissa"},
    {"amount":"2 tbsp","item":"olive oil"},
    {"amount":"1 tsp","item":"ground cumin"},
    {"amount":"300 g","item":"Greek yogurt"},
    {"amount":"1 clove","item":"garlic, finely grated"},
    {"amount":"1 tbsp","item":"lemon juice"},
    {"amount":"1 handful","item":"mint, roughly chopped"},
    {"amount":"","item":"salt and black pepper"}
  ]'::jsonb,
  '[
    "Bland harissa, olivenolje, spisskummen, salt og pepper. Gni kotelettene inn.",
    "La kotelettene marinere i minst 20 minutter.",
    "Ror yoghurt med hvitlok, sitronsaft og halvparten av mynten.",
    "Stek kotelettene 3-4 minutter per side i varm panne til 62-64 C kjernetemperatur.",
    "La hvile i 5 minutter.",
    "Server med yoghurtdressing og resten av mynten over."
  ]'::jsonb,
  '[
    "Mix harissa, olive oil, cumin, salt, and pepper. Rub onto the chops.",
    "Marinate for at least 20 minutes.",
    "Stir yogurt with garlic, lemon juice, and half the mint.",
    "Cook chops 3-4 minutes per side in a hot pan to 62-64 C internal temperature.",
    "Rest for 5 minutes.",
    "Serve with yogurt dressing and remaining mint on top."
  ]'::jsonb,
  'Ikke overstek. Koteletter med fettkant blir best nar de far hvile og sa skjaeres med saften i behold.',
  'Do not overcook. Fat-capped chops are best when rested before slicing.',
  'Marmoreringen i ullgris-koteletter tar opp krydder godt og gir ekstra saftig resultat under sterk varme.',
  'Marbling in wool pig chops absorbs spices well and stays juicy under high heat.',
  'easy', 20, 15, 4,
  '/recipes/koteletter-harissa-yoghurt.jpg',
  ARRAY['koteletter'],
  26,
  true
),
(
  'bog-carnitas-lime',
  'Spro carnitas av ullgris-bog med lime og koriander',
  'Crispy Wool Pig Shoulder Carnitas with Lime and Coriander',
  'Langtidsbakt bog som trekkes fra hverandre og stekes spro i eget fett. Perfekt til tortilla, ris eller salat.',
  'Slow-roasted shoulder pulled apart and crisped in its own fat. Perfect for tortillas, rice, or salad.',
  '[
    {"amount":"1,8 kg","item":"bog av ullgris i store biter"},
    {"amount":"2 ts","item":"flaksalt"},
    {"amount":"1 ts","item":"sort pepper"},
    {"amount":"1 ts","item":"spisskummen"},
    {"amount":"1 ts","item":"torket oregano"},
    {"amount":"1 ts","item":"rokt paprika"},
    {"amount":"3 dl","item":"appelsinjuice"},
    {"amount":"1 dl","item":"limesaft"},
    {"amount":"4 fedd","item":"hvitlok, knust"},
    {"amount":"1 neve","item":"koriander"}
  ]'::jsonb,
  '[
    {"amount":"1.8 kg","item":"wool pig shoulder, large chunks"},
    {"amount":"2 tsp","item":"flaky salt"},
    {"amount":"1 tsp","item":"black pepper"},
    {"amount":"1 tsp","item":"ground cumin"},
    {"amount":"1 tsp","item":"dried oregano"},
    {"amount":"1 tsp","item":"smoked paprika"},
    {"amount":"300 ml","item":"orange juice"},
    {"amount":"100 ml","item":"lime juice"},
    {"amount":"4 cloves","item":"garlic, crushed"},
    {"amount":"1 handful","item":"coriander"}
  ]'::jsonb,
  '[
    "Krydre bogbitene med salt, pepper, spisskummen, oregano og rokt paprika.",
    "Legg i ildfast form med hvitlok, appelsinjuice og halvparten av limesaften.",
    "Dekk tett og bak pa 150 C i 3-3,5 timer til kjottet faller fra hverandre.",
    "Riv kjottet med to gafler.",
    "Stek det revne kjottet hardt i panne eller under grillfunksjon til kantene blir spro.",
    "Vend inn resten av limesaften og topp med koriander."
  ]'::jsonb,
  '[
    "Season shoulder with salt, pepper, cumin, oregano, and smoked paprika.",
    "Place in a roasting tray with garlic, orange juice, and half the lime juice.",
    "Cover tightly and roast at 150 C for 3-3.5 hours until pull-apart tender.",
    "Shred with two forks.",
    "Crisp the shredded meat hard in a pan or under the broiler.",
    "Finish with remaining lime juice and coriander."
  ]'::jsonb,
  'Stek alltid kjottet spro helt til slutt. Det gir stor kontrast mot den saftige kjernen.',
  'Always crisp the meat at the end. The texture contrast is the whole point.',
  'Bog fra ullgris har kollagen og fett som gir silkemyk tekstur etter lang steketid, men kan fortsatt bli spro i overflaten.',
  'Wool pig shoulder has collagen and fat for silky long-cooked texture, yet still crisps beautifully on the edges.',
  'medium', 20, 210, 6,
  '/recipes/bog-carnitas-lime.jpg',
  ARRAY['bogsteik'],
  27,
  true
),
(
  'kjottdeig-kofta-tahini',
  'Ullgris-kofta med tahini, sitron og mynte',
  'Wool Pig Kofta with Tahini, Lemon and Mint',
  'Midtostlig inspirert hverdagsrett med krydret kofta og kremet tahinisaus.',
  'Middle Eastern-inspired weeknight dish with spiced kofta and creamy tahini sauce.',
  '[
    {"amount":"800 g","item":"grov kjottdeig av ullgris"},
    {"amount":"1 stk","item":"egg"},
    {"amount":"2 fedd","item":"hvitlok, finhakket"},
    {"amount":"1 ts","item":"spisskummen"},
    {"amount":"1 ts","item":"koriander, malt"},
    {"amount":"1 ts","item":"paprikapulver"},
    {"amount":"1 ss","item":"mynte, finhakket"},
    {"amount":"3 ss","item":"tahini"},
    {"amount":"2 ss","item":"gresk yoghurt"},
    {"amount":"1 ss","item":"sitronsaft"},
    {"amount":"","item":"salt og sort pepper"}
  ]'::jsonb,
  '[
    {"amount":"800 g","item":"coarse wool pig mince"},
    {"amount":"1","item":"egg"},
    {"amount":"2 cloves","item":"garlic, finely chopped"},
    {"amount":"1 tsp","item":"ground cumin"},
    {"amount":"1 tsp","item":"ground coriander"},
    {"amount":"1 tsp","item":"paprika"},
    {"amount":"1 tbsp","item":"mint, finely chopped"},
    {"amount":"3 tbsp","item":"tahini"},
    {"amount":"2 tbsp","item":"Greek yogurt"},
    {"amount":"1 tbsp","item":"lemon juice"},
    {"amount":"","item":"salt and black pepper"}
  ]'::jsonb,
  '[
    "Bland kjottdeig, egg, hvitlok, krydder og mynte. Form 10-12 avlange kofta.",
    "Stek kofta i medium varm panne med litt olje i 4-5 minutter per side.",
    "Ror sammen tahini, yoghurt, sitronsaft og en liten skvett vann til silkemyk saus.",
    "Smak sausen til med salt og pepper.",
    "Server kofta med tahinisaus, ekstra mynte og varme lefser eller ris."
  ]'::jsonb,
  '[
    "Mix mince, egg, garlic, spices, and mint. Shape into 10-12 oblong kofta.",
    "Cook in a medium-hot pan with a little oil for 4-5 minutes per side.",
    "Whisk tahini, yogurt, lemon juice, and a splash of water into a silky sauce.",
    "Season sauce with salt and pepper.",
    "Serve with tahini sauce, extra mint, and warm flatbread or rice."
  ]'::jsonb,
  'Hvis farsen kjennes los, la den hvile 10 minutter i kjoleskap for bedre binding.',
  'If the mixture feels loose, chill for 10 minutes before cooking for better binding.',
  'Fettet i ullgris-kjottdeig gir saftige kofta uten behov for brodsmuler eller ekstra fettstoff.',
  'The fat in wool pig mince keeps kofta juicy without breadcrumbs or extra fat binders.',
  'easy', 20, 18, 4,
  '/recipes/kjottdeig-kofta-tahini.jpg',
  ARRAY['kjottdeig'],
  28,
  true
),
(
  'polser-currywurst-kimchi',
  'Ullgris-polser med currywurst-saus og kimchi',
  'Wool Pig Sausages with Currywurst Sauce and Kimchi',
  'Tysk street food mote koreansk syre: fyldig tomat-currysaus, spro stekeskorpe og frisk kimchi.',
  'German street food meets Korean acidity: rich tomato-curry sauce, crisp sear, and bright kimchi.',
  '[
    {"amount":"800 g","item":"ullgris-polser"},
    {"amount":"2 ss","item":"tomatpure"},
    {"amount":"2 dl","item":"passata"},
    {"amount":"1 ss","item":"honning"},
    {"amount":"1 ss","item":"mild curry"},
    {"amount":"1 ts","item":"rokt paprika"},
    {"amount":"1 ts","item":"worcestershire saus"},
    {"amount":"1 ss","item":"rodvinseddik"},
    {"amount":"2 ss","item":"smor"},
    {"amount":"200 g","item":"kimchi"}
  ]'::jsonb,
  '[
    {"amount":"800 g","item":"wool pig sausages"},
    {"amount":"2 tbsp","item":"tomato paste"},
    {"amount":"200 ml","item":"passata"},
    {"amount":"1 tbsp","item":"honey"},
    {"amount":"1 tbsp","item":"mild curry powder"},
    {"amount":"1 tsp","item":"smoked paprika"},
    {"amount":"1 tsp","item":"Worcestershire sauce"},
    {"amount":"1 tbsp","item":"red wine vinegar"},
    {"amount":"2 tbsp","item":"butter"},
    {"amount":"200 g","item":"kimchi"}
  ]'::jsonb,
  '[
    "Stek polsene i smor pa medium varme til de er gjennomvarme og gylne.",
    "Ta polsene ut av pannen. Tilsett tomatpure og stek i 1 minutt.",
    "Ror inn passata, honning, curry, paprika, worcestershire og eddik.",
    "La sausen sma koke i 6-8 minutter til den blir tykk og blank.",
    "Skjaer polsene i biter, vend i sausen og server med kimchi ved siden av."
  ]'::jsonb,
  '[
    "Pan-fry sausages in butter over medium heat until cooked through and golden.",
    "Remove sausages. Add tomato paste and cook for 1 minute.",
    "Stir in passata, honey, curry, paprika, Worcestershire, and vinegar.",
    "Simmer 6-8 minutes until thick and glossy.",
    "Slice sausages, coat in sauce, and serve with kimchi on the side."
  ]'::jsonb,
  'Vil du ha ekstra spro overflate, trekk polsene raskt under grill de siste 2 minuttene.',
  'For extra crust, finish sausages under a broiler for 2 minutes.',
  'Ullgris-polser beholder saftigheten selv ved dobbel varmebehandling, noe som passer perfekt til currywurst-stil.',
  'Wool pig sausages stay juicy even with two-step cooking, perfect for currywurst style.',
  'easy', 10, 20, 4,
  '/recipes/polser-currywurst-kimchi.jpg',
  ARRAY['polser'],
  29,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  title_no = EXCLUDED.title_no,
  title_en = EXCLUDED.title_en,
  intro_no = EXCLUDED.intro_no,
  intro_en = EXCLUDED.intro_en,
  ingredients_no = EXCLUDED.ingredients_no,
  ingredients_en = EXCLUDED.ingredients_en,
  steps_no = EXCLUDED.steps_no,
  steps_en = EXCLUDED.steps_en,
  tips_no = EXCLUDED.tips_no,
  tips_en = EXCLUDED.tips_en,
  mangalitsa_tip_no = EXCLUDED.mangalitsa_tip_no,
  mangalitsa_tip_en = EXCLUDED.mangalitsa_tip_en,
  difficulty = EXCLUDED.difficulty,
  prep_time_minutes = EXCLUDED.prep_time_minutes,
  cook_time_minutes = EXCLUDED.cook_time_minutes,
  servings = EXCLUDED.servings,
  image_url = EXCLUDED.image_url,
  related_extra_slugs = EXCLUDED.related_extra_slugs,
  display_order = EXCLUDED.display_order,
  active = EXCLUDED.active,
  updated_at = NOW();
